In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import streamlit as st
import os

In [ ]:
import pandas as pd
import numpy as np
cleaned_ipl_data = "https://drive.google.com/uc?export=download&id=1e2-twd_ih87O2bmXWZpEGJR5KMLiIEMA"
df = pd.read_csv(url)
df.head()

C:\Users\karan\AppData\Local\Temp\ipykernel_420\454187388.py:4: DtypeWarning: Columns (19,20,21,22,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,...,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,...,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,1,...,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,0,...,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,1,...,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,1,...,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
df=pd.read_csv("D:\ipl\IPL.csv")

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\4278241017.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("D:\ipl\IPL.csv")

In [ ]:
df.shape

(278205, 64)

In [ ]:
df.tail(5)

,index,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,19.2,Shashank Singh,6,0,1,JR Hazlewood,1,0,0,0,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,19.3,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,19.4,Shashank Singh,6,4,1,JR Hazlewood,1,0,4,4,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,19.5,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,19.6,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

In [ ]:
df['match_id'].nunique()

1169

1. the data is of 1169 ipl matches from 2008-2025
2. average matches per season is 69

In [ ]:
df.isnull().sum()

index                     0
match_id                  0
date                      0
match_type                0
event_name                0
innings                   0
batting_team              0
bowling_team              0
over                      0
ball                      0
ball_no                   0
batter                    0
bat_pos                   0
runs_batter               0
balls_faced               0
bowler                    0
valid_ball                0
runs_extras               0
runs_total                0
runs_bowler               0
runs_not_boundary         0
extra_type           263072
non_striker               0
non_striker_pos           0
wicket_kind          264382
player_out           264382
fielders             268192
runs_target          144302
review_batter        277333
team_reviewed        277333
review_decision      277333
umpire               277333
umpires_call              0
player_of_match           0
match_won_by              0
win_outcome            4702
toss_winner               0
toss_decision             0
venue                     0
city                      0
day                       0
month                     0
year                      0
season                    0
gender                    0
team_type                 0
superover_winner     274309
result_type          273503
method               274315
balls_per_over            0
overs                     0
event_match_no            0
stage                     0
match_number              0
team_runs                 0
team_balls                0
team_wicket               0
new_batter           264884
batter_runs               0
batter_balls              0
bowler_wicket             0
batting_partners          0
next_batter          264884
striker_out               0
dtype: int64

there are plenty of missing value but most of them are maybe due to data error .we can resolve that using the map function

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   index              278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  object
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), object(35)
memory usage: 130.3+ MB

In [ ]:
df.duplicated().sum()

np.int64(0)

# data cleaning

In [ ]:
train_df=df.copy()

In [ ]:
train_df.tail()

,index,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,19.2,Shashank Singh,6,0,1,JR Hazlewood,1,0,0,0,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,19.3,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,19.4,Shashank Singh,6,4,1,JR Hazlewood,1,0,4,4,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,19.5,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,19.6,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

droping the index ,match type, event name : as these are same for all the mathes.and  ipl are of 20 overs

In [ ]:
train_df.drop(columns=['index','match_type','event_name'],inplace=True)

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

inning is defining the which club is playing first/bating  and which club is bowling

replacing the names of batting team into the sort form (example "Kolkata Knight Riders"-kkr) and so on

In [ ]:
train_df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

some of the teams are have 2 value so we will convert these into lower case teams

In [ ]:
train_df['batting_team'].nunique()

19

In [ ]:
# batting_dic={
#             'Kolkata Knight Riders':'KKR',
#             'Royal Challengers Bangalore':'RCB',
#             'Chennai Super Kings':'CSK',
#             'Kings XI Punjab':'KXP',
#             'Rajasthan Royals':'RR',
#             'Delhi Daredevils':'DC',
#             'Mumbai Indians':'MI',
#             'Deccan Chargers':'DEC',
#             'Kochi Tuskers Kerala':'KTK',
#             'Pune Warriors':"PW",
#             'Sunrisers Hyderabad':'SRH',
#             'Rising Pune Supergiants':'RPS',
#             'Gujarat Lions':'GL',
#             'Rising Pune Supergiant':'RPS',
#             'Delhi Capitals':'DC',
#             'Punjab Kings':'KXP',
#             'Lucknow Super Giants':'LSG',
#             'Gujarat Titans':'GT',
#             'Royal Challengers Bengaluru':'RCB'}

In [ ]:
# # train_df.apply(lambda x : x .replace(batting_dic))
# # this process can be slow so insted of using lamda we are going to use the replace function of pandas which is faster or the map function 
# # Create a list of columns that contain team names
# team_cols = ['batting_team', 'bowling_team' ,'match_won_by','toss_winner','superover_winner'] 

# # Option A: Using replace (Great for whole DataFrames or specific columns)
# # Strip spaces and replace names for both columns efficiently
# for col in team_cols:
#     train_df[col] = train_df[col].str.strip().replace(batting_dic)# we added the strip fuction so that the there is no extrea space in
# # the daataset which can cause problem in the future

In [ ]:
train_df.head(8)

,match_id,date,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,0.5,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
6,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,0.6,BB McCullum,2,0,1,P Kumar,1,1,1,0,False,legbyes,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,6,0,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False
7,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,1.1,BB McCullum,2,0,1,Z Khan,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,7,0,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
train_df[['match_id','ball','ball_no']].head(20)

    match_id  ball  ball_no
0     335982     1      0.1
1     335982     2      0.2
2     335982     3      0.3
3     335982     3      0.3
4     335982     4      0.4
5     335982     5      0.5
6     335982     6      0.6
7     335982     1      1.1
8     335982     2      1.2
9     335982     3      1.3
10    335982     4      1.4
11    335982     5      1.5
12    335982     6      1.6
13    335982     1      2.1
14    335982     2      2.2
15    335982     3      2.3
16    335982     4      2.4
17    335982     5      2.5
18    335982     6      2.6
19    335982     1      3.1

we dont need both ball and ball no so we are removingthe ball as the ball_no is same but better than ball

In [ ]:
train_df.drop('ball',axis=1,inplace=True)

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

bat_pos define the order on which the batsman have enter the ground and contains 1-11 number a

In [ ]:
train_df['bat_pos'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# pos_stats

In [ ]:
# Group the data for checking the most succeful positon for batsman
pos_stats = train_df.groupby(['batter', 'bat_pos'])['runs_batter'].sum().reset_index()

# Filter: Only show positions where the player has scored at least 30 runs
# This keeps your charts from looking cluttered with '1' or '0' run bars
pos_stats['batter']=pos_stats['batter'].apply(lambda x : x.lower())
pos_stats = pos_stats[pos_stats['runs_batter'] > 30]

In [ ]:
pos_stats.sort_values('runs_batter',ascending=False).head(20)

              batter  bat_pos  runs_batter
1825        s dhawan        2         5225
1927        sk raina        3         4942
496        da warner        1         4270
637     f du plessis        2         3411
1002        kl rahul        1         3362
2051       sv samson        3         3096
2237         v kohli        3         2815
2120    shubman gill        2         2788
2235         v kohli        1         2626
164        am rahane        1         2497
2236         v kohli        2         2393
1701       rg sharma        4         2392
426         ch gayle        2         2277
2247        v sehwag        2         2241
425         ch gayle        1         2235
657        g gambhir        2         2219
92    ab de villiers        3         2188
2013    sr tendulkar        2         2120
1776      rv uthappa        1         2086
1742         rr pant        4         2012

we are droping the duplicated columns were the data is already given and we are picking the best position for the batsman so we are keeping the first cocuurence . to avoid takingthe second best value

In [ ]:
pos_stats.sort_values('runs_batter',ascending=False).drop_duplicates(subset=['batter'],keep='first').head(20)

              batter  bat_pos  runs_batter
1825        s dhawan        2         5225
1927        sk raina        3         4942
496        da warner        1         4270
637     f du plessis        2         3411
1002        kl rahul        1         3362
2051       sv samson        3         3096
2237         v kohli        3         2815
2120    shubman gill        2         2788
164        am rahane        1         2497
1701       rg sharma        4         2392
426         ch gayle        2         2277
2247        v sehwag        2         2241
657        g gambhir        2         2219
92    ab de villiers        3         2188
2013    sr tendulkar        2         2120
1776      rv uthappa        1         2086
1742         rr pant        4         2012
494        da miller        5         2002
833       jc buttler        2         1993
348      bb mccullum        2         1992

we can use the same code for worst batting postion

In [ ]:
train_df['batter']=train_df['batter'].apply(lambda x : x.lower())

runs_batter define the run made by the batsman in matches

In [ ]:
train_df.groupby('batter')['runs_batter'].sum().sort_values(ascending=False).tail(500)

batter
y nagar                    285
gh vihari                  284
vvs laxman                 282
b chipli                   280
a ashish reddy             280
mj lumb                    278
jp inglis                  278
pbb rajapaksa              277
pk garg                    273
mj guptill                 271
hv patel                   270
r sathish                  270
jc archer                  262
atharva taide              260
m kaif                     259
jo holder                  259
v suryavanshi              252
k gowtham                  247
harpreet brar              244
sm katich                  241
a mhatre                   240
bcj cutting                238
md mishra                  237
aniket verma               236
mohammad nabi              221
k goel                     218
ramandeep singh            217
aa jhunjhunwala            217
k rabada                   215
r dhawan                   210
ut yadav                   208
ca ingram                  205
pd collingwood             203
kuldeep yadav              201
ks bharat                  199
sk warne                   198
jd unadkat                 197
sp fleming                 196
as raut                    194
bj rohrer                  193
salman butt                193
yv takawale                192
hc brook                   190
bipul sharma               187
r shepherd                 185
fy fazal                   183
sd hope                    183
ms wade                    183
sikandar raza              182
cr brathwaite              181
ac voges                   181
s gopal                    180
ab agarkar                 179
mf maharoof                177
c munro                    177
sameer rizvi               172
dh yagnik                  170
cm gautam                  169
dw steyn                   167
mn van wyk                 167
mg johnson                 167
pa reddy                   164
n jagadeesan               162
mn samuels                 161
re van der merwe           159
r mclaren                  159
ad hales                   148
d wiese                    148
sm pollock                 147
s vidyut                   145
sachin baby                144
v nigam                    142
m jansen                   141
n saini                    140
sb dubey                   139
anmolpreet singh           139
s anirudha                 136
sb styris                  131
w jaffer                   130
rd chahar                  129
kamran akmal               128
p dogra                    127
tk curran                  127
ut khawaja                 127
ss prabhudessai            126
m morkel                   126
bb samantray               125
mc juneja                  125
mm sharma                  125
b lee                      124
ab mcdonald                123
harpreet singh             123
dl vettori                 121
nk patel                   121
tg southee                 120
ac blizzard                120
arshad khan                119
rj harris                  117
mw short                   117
misbah-ul-haq              117
dl chahar                  117
z khan                     117
kk cooper                  116
aman hakim khan            115
djm short                  115
m kartik                   113
mohammed siraj             112
dj harris                  111
ma starc                   111
mj santner                 110
jdp oram                   106
lj wright                  106
ds kulkarni                104
rj quiney                  103
azmatullah omarzai          99
sd chitnis                  99
ms gony                     99
cj ferguson                 98
mj clarke                   98
pn mankad                   97
dj jacobs                   92
phkd mendis                 92
jds neesham                 92
pr shah                     92
rt ponting                  91
aj tye                      91
s rana                      91
ad nath                     90
iqbal abdulla               88
sl malinga                  88
ankit sharma                87
ap majumdar                 87
ta boult                    85
mj mcclenaghan              85
mohammed shami              84
re levi                     83
nm coulter-nile             82
pwh de silva                81
la carseldine               81
cj jordan                   81
shahid afridi               81
wpujc vaas                  81
rv patel                    80
ad mascarenhas              79
jr philippe                 78
cr woakes                   78
ir jaggi                    76
b akhil                     76
tr birt                     75
m klinger                   73
rr sarwan                   73
lh ferguson                 72
sk rasheed                  71
j suchith                   70
aa bilakhia                 69
vivrant sharma              69
urvil patel                 68
jj bumrah                   68
jg bethell                  67
rr powar                    67
r sharma                    66
hr shokeen                  66
wd parnell                  65
gd phillips                 65
ka jamieson                 65
mohammad hafeez             64
anirudh singh               63
a flintoff                  62
avesh khan                  62
sp jackson                  61
sandeep sharma              60
s aravind                   59
harshit rana                59
mg bracewell                58
i sharma                    57
wa mota                     56
vishnu vinod                56
m rawat                     55
a chopra                    53
dj willey                   53
pvd chameera                53
rp singh                    52
shoaib malik                52
r rampaul                   51
of smith                    51
swapnil singh               51
kb arun karthik             51
shivam mavi                 51
rv gomez                    50
vr aaron                    50
sb bangar                   49
a nortje                    49
ag paunikar                 49
as yadav                    49
m markande                  48
t kohler-cadmore            48
yashpal singh               47
c bosch                     47
ravi bishnoi                45
d pretorius                 44
dr sams                     44
sunny singh                 43
sk trivedi                  42
ab barath                   42
a nehra                     41
rasikh salam                40
lpc silva                   40
br dunk                     40
j yadav                     40
auk pathan                  39
s nadeem                    39
umar gul                    39
dj thornely                 39
mm patel                    39
ys chahal                   37
s narwal                    37
an ahmed                    36
sohail tanvir               36
kw richardson               36
l balaji                    36
anureet singh               36
joginder sharma             36
a kumble                    35
m ashwin                    35
b sumanth                   35
l ronchi                    34
ap dole                     34
a mithun                    34
s sreesanth                 34
d salunkhe                  33
imran tahir                 33
navdeep saini               33
at carey                    32
rj peterson                 32
basil thampi                32
arshdeep singh              31
t taibu                     31
g coetzee                   31
s sriram                    31
ns naik                     31
j syed mohammad             29
vh zol                      29
sb jakati                   28
tu deshpande                28
as joseph                   27
jm kemp                     26
as roy                      26
as rajpoot                  26
pj sangwan                  26
nl mccullum                 26
dj malan                    26
md shanaka                  26
tl seifert                  26
ab dinda                    26
cv varun                    26
sanvir singh                25
akash deep                  25
mohsin khan                 25
s chanderpaul               25
a choudhary                 25
er dwivedi                  24
aj turner                   24
tanush kotian               24
kc cariappa                 24
ma khote                    24
p dubey                     23
j arunkumar                 23
umran malik                 23
af milne                    23
bmaj mendis                 23
sw tait                     23
au rashid                   22
gb hogg                     22
sediqullah atal             22
sa abbott                   22
yudhvir singh               22
he van der dussen           22
kl nagarkoti                22
b indrajith                 21
de bollinger                21
s kaul                      20
ac thomas                   20
noor ahmad                  20
m muralitharan              20
bkg mendis                  20
c sakariya                  20
nj maddinson                20
rr raje                     20
p sahu                      19
p ray barman                19
y gnaneswara rao            19
r bishnoi                   19
nt ellis                    19
ra bawa                     19
dr martyn                   19
a mukund                    19
jr hazlewood                19
r shukla                    19
gulbadin naib               19
bj haddin                   18
naveen-ul-haq               18
t banton                    18
kma paul                    18
ds lehmann                  18
harmeet singh               18
sumit kumar                 18
saurav chauhan              18
r sai kishore               18
pv tambe                    18
jj van der wath             18
parvez rasool               17
m theekshana                17
ja richardson               17
aj hosein                   16
yv dhull                    16
a kamboj                    16
pp ojha                     16
ck kapugedera               16
ks sharma                   16
virat singh                 15
a zampa                     15
vy mahesh                   15
c madan                     15
i udana                     15
jl pattinson                15
gr napier                   15
sd lad                      15
j overton                   15
mdkj perera                 14
fa allen                    14
f behardien                 14
vijaykumar vyshak           14
mp breetzke                 14
arjun tendulkar             13
mustafizur rahman           13
dt patil                    13
dr shorey                   13
s badree                    13
kartik tyagi                13
kj abbott                   13
mujeeb ur rahman            12
t thushara                  12
daj bracewell               12
ma wood                     12
karanveer singh             12
dg nalkande                 12
ar bawne                    12
k kartikeya                 12
k upadhyay                  12
aa chavan                   12
xc bartlett                 11
t henderson                 11
m ntini                     11
t kohli                     11
dnt zoysa                   11
x thalaivan sargunam        10
td paine                    10
d du preez                  10
mukesh kumar                10
je root                     10
ag murtaza                  10
kaj roach                   10
smsm senanayake             10
simarjeet singh             10
j theron                    10
bb sran                     10
rk bhui                     10
m prasidh krishna            9
pwa mulder                   9
vg arora                     9
d ferreira                   9
aa kulkarni                  9
aa noffke                    9
sm harwood                   9
l wood                       9
akash madhwal                8
ts mills                     8
p chopra                     8
ck langeveldt                8
jpr scantlebury-searles      8
jaskaran singh               8
kt maphaka                   8
sh johnson                   8
tm srivastava                8
cj mckay                     8
oc mccoy                     8
suryansh shedge              7
ua birla                     7
vs malik                     7
i malhotra                   7
pankaj singh                 7
an ghosh                     7
ankit soni                   7
v viyaskanth                 7
is sodhi                     7
mukesh choudhary             6
ss shaikh                    6
sb joshi                     6
r minz                       6
dm bravo                     6
ba bhatt                     6
jp behrendorff               6
psp handscomb                6
sj srivastava                5
b stanlake                   5
b laughlin                   5
prince yadav                 5
p awana                      5
kmdn kulasekara              5
fazalhaq farooqi             5
shivam sharma                5
arshad khan (2)              5
vrv singh                    4
crd fernando                 4
gd mcgrath                   4
liton das                    4
rs sodhi                     4
fh edwards                   4
dp nannes                    4
a uniyal                     4
a tomar                      4
a dananjaya                  4
yash dayal                   4
a chandila                   4
younis khan                  3
baw mendis                   3
je taylor                    3
gc viljoen                   3
kumar kushagra               3
kamran khan                  3
mohammad asif                3
m tiwari                     3
rjw topley                   3
r ninan                      3
t natarajan                  3
s tyagi                      3
d kalyankrishna              3
kp appanna                   2
rs gavaskar                  2
kk ahmed                     2
vs yeligati                  2
br sharath                   2
s randiv                     2
sb wagh                      2
shivam singh                 2
shoaib akhtar                2
a singh                      2
t shamsi                     2
mohammad ashraful            2
mashrafe mortaza             2
rj gleeson                   2
rg more                      2
ghs garton                   2
h das                        2
abdul basith                 1
dj muthuswami                1
se bond                      1
shoaib ahmed                 1
dp vijaykumar                1
ds rathi                     1
m de lange                   1
mohit rathee                 1
mj suthar                    1
p parameswaran               1
sz mulani                    1
pvsn raju                    1
nj rimmington                1
ms bhandage                  1
hf gurney                    1
pm sarvesh kumar             1
le plunkett                  1
lb williams                  1
be hendricks                 1
ka maharaj                   1
y prithvi raj                0
ya abdulla                   0
sunny gupta                  0
ss cottrell                  0
rp meredith                  0
s lamichhane                 0
s kaushik                    0
rr bhatkal                   0
s ladda                      0
r sanjay yadav               0
u kaul                       0
mayank dagar                 0
mj owen                      0
musheer khan                 0
nd doshi                     0
l ngidi                      0
kr sen                       0
ks rathore                   0
v pratap singh               0
jl denly                     0
km asif                      0
k yadav                      0
l ablish                     0
ic pandey                    0
c nanda                      0
abdur razzak                 0
Name: runs_batter, dtype: int64

# wide_balls

In [ ]:
wide_balls=train_df[train_df['balls_faced']==0]

In [ ]:
wide_balls['extra_type'].value_counts()

extra_type
wides             9079
penalty, wides       1
Name: count, dtype: int64

In [ ]:
wide_balls[wide_balls['extra_type']!='wides'].head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
98231,729309,2014-04-27,2,Delhi Daredevils,Mumbai Indians,4,4.2,m vijay,2,0,0,SL Malinga,0,7,7,2,False,"penalty, wides",Q de Kock,1,NaN,NaN,NaN,126.0,NaN,NaN,NaN,NaN,False,M Vijay,Delhi Daredevils,6 wickets,Mumbai Indians,bat,Sharjah Cricket Stadium,Unknown,27,4,2014,2014,male,club,NaN,NaN,NaN,6,20,16,Unknown,Unknown,30,25,0,NaN,8,12,0,"('M Vijay', 'Q de Kock')",NaN,False

there is only 1 penalty ball so we can say the balled_faced into wide balls

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

ball faced

In [ ]:
train_df['balls_faced'].nunique()

2

In [ ]:
train_df.groupby('batter')['balls_faced'].sum().sort_values(ascending=False).head(10)

batter
v kohli       6523
rg sharma     5337
s dhawan      5326
da warner     4702
sk raina      4046
am rahane     4025
ms dhoni      3957
kl rahul      3848
rv uthappa    3801
kd karthik    3580
Name: balls_faced, dtype: int64

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
train_df['bowler'].unique()

array(['P Kumar', 'Z Khan', 'AA Noffke', 'JH Kallis', 'SB Joshi',
       'CL White', 'AB Dinda', 'I Sharma', 'AB Agarkar', 'SC Ganguly',
       'LR Shukla', 'B Lee', 'S Sreesanth', 'JR Hopes', 'IK Pathan',
       'K Goel', 'PP Chawla', 'WA Mota', 'JDP Oram', 'MS Gony',
       'M Muralitharan', 'P Amarnath', 'Joginder Sharma', 'GD McGrath',
       'B Geeves', 'MF Maharoof', 'R Bhatia', 'DL Vettori', 'MM Patel',
       'SR Watson', 'SK Trivedi', 'SK Warne', 'YK Pathan', 'D Salunkhe',
       'R Vinay Kumar', 'B Akhil', 'A Nehra', 'SM Pollock', 'DS Kulkarni',
       'ST Jayasuriya', 'Harbhajan Singh', 'AM Nayar', 'M Kartik',
       'Mohammad Hafeez', 'DJ Hussey', 'WPUJC Vaas', 'RP Singh',
       'SB Styris', 'SB Bangar', 'A Symonds', 'PP Ojha', 'Pankaj Singh',
       'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi', 'DJ Bravo',
       'VS Yeligati', 'MA Khote', 'D Kalyankrishna', 'VRV Singh',
       'Sohail Tanvir', 'A Kumble', 'DNT Zoysa', 'SD Chitnis',
       'Yuvraj Singh', 'Shoaib Malik', 'DW Steyn', 'JA Morkel',
       'CRD Fernando', 'V Kohli', 'V Sehwag', 'Gagandeep Singh',
       'Y Venugopal Rao', 'Umar Gul', 'PJ Sangwan', 'M Ntini',
       'DP Vijaykumar', 'DJ Thornely', 'RR Raje', 'SK Raina', 'S Vidyut',
       'L Balaji', 'CK Kapugedera', 'AD Mascarenhas', 'A Mishra',
       'Shoaib Akhtar', 'Iqbal Abdulla', 'PM Sarvesh Kumar', 'RR Powar',
       'Abdur Razzak', 'RA Jadeja', 'TM Dilshan', 'DR Smith', 'RG Sharma',
       'A Nel', 'DB Ravi Teja', 'LPC Silva', 'BAW Mendis', 'T Thushara',
       'A Flintoff', 'SL Malinga', 'Kamran Khan', 'T Henderson',
       'JD Ryder', 'DP Nannes', 'AM Salvi', 'YA Abdulla', 'VS Malik',
       'FH Edwards', 'Harmeet Singh', 'CH Gayle', 'MC Henriques',
       'KP Pietersen', 'LRPL Taylor', 'RS Bopara', 'MK Tiwary',
       'Anureet Singh', 'RR Bose', 'KP Appanna', 'Shoaib Ahmed',
       'BJ Hodge', 'SR Tendulkar', 'RE van der Merwe', 'JP Duminy',
       'S Tyagi', 'GR Napier', 'SM Harwood', 'AS Raut', 'SB Jakati',
       'D du Preez', 'RJ Harris', 'TL Suman', 'A Singh', 'M Morkel',
       'LA Carseldine', 'A Mithun', 'C Nanda', 'SS Sarkar', 'AD Mathews',
       'AM Rahane', 'J Botha', 'Mashrafe Mortaza', 'AB McDonald',
       'Y Nagar', 'CK Langeveldt', 'R Ashwin', 'RA Shaikh',
       'Jaskaran Singh', 'SW Tait', 'A Uniyal', 'AA Jhunjhunwala',
       'R McLaren', 'AG Murtaza', 'R Sathish', 'RS Gavaskar', 'JM Kemp',
       'S Ladda', 'Bipul Sharma', 'SE Bond', 'KA Pollard', 'S Narwal',
       'UT Yadav', 'SJ Srivastava', 'AC Voges', 'R Sharma', 'J Theron',
       'NLTC Perera', 'KAJ Roach', 'PD Collingwood', 'C Ganapathy',
       'MB Parmar', 'SB Wagh', 'DE Bollinger', 'JD Unadkat', 'AP Dole',
       'AN Ahmed', 'FY Fazal', 'MR Marsh', 'L Ablish', 'S Sriram',
       'AJ Finch', 'STR Binny', 'ND Doshi', 'TG Southee', 'S Randiv',
       'AL Menaria', 'DT Christian', 'AUK Pathan', 'RV Gomez',
       'JEC Franklin', 'AC Thomas', 'WD Parnell', 'M Manhas',
       'NJ Rimmington', 'RN ten Doeschate', 'S Nadeem', 'BA Bhatt',
       'JJ van der Wath', 'S Aravind', 'R Ninan', 'Shakib Al Hasan',
       'PC Valthaty', 'S Dhawan', 'J Syed Mohammad', 'VR Aaron',
       'NL McCullum', 'JE Taylor', 'KMDN Kulasekara', 'P Parameswaran',
       'I Malhotra', 'B Chipli', 'B Kumar', 'AA Kazi', 'Anand Rajan',
       'P Prasanth', 'Y Gnaneswara Rao', 'AA Chavan', 'S Rana',
       'JP Faulkner', 'SS Mundhe', 'RW Price', 'GJ Maxwell', 'M de Lange',
       'MN Samuels', 'KK Cooper', 'DAJ Bracewell', 'HV Patel',
       'Ankit Sharma', 'DJ Harris', 'TP Sudhindra', 'F du Plessis',
       'SP Narine', 'GB Hogg', 'RR Bhatkal', 'P Awana', 'CJ McKay',
       'V Pratap Singh', 'Azhar Mahmood', 'A Chandila', 'P Negi',
       'LJ Wright', 'RJ Peterson', 'A Ashish Reddy', 'R Shukla',
       'MJ Clarke', 'BW Hilfenhaus', 'SPD Smith', 'AD Russell',
       'K Upadhyay', 'Sunny Gupta', 'MG Johnson', 'JJ Bumrah', 'S Badree',
       'AS Rajpoot', 'B Laughlin', 'GH Vihari', 'Mohammed Shami',
       'BMAJ Mendis', 'CH Morris', 'S Kaul', 'R Dhawan', 'MM Sharma',
       'R Rampaul', 'KV Sharma', 'SMSM Senanayake', 'JO Holder',
       'IC Pandey', 'YS Chahal', 'DJG Sammy', 'KW Richardson', 'P Suyal',
       'MG Neser', 'PV Tambe', 'BJ Rohrer', 'Parvez Rasool',
       'Sandeep Sharma', 'NM Coulter-Nile', 'AC Gilchrist', 'CJ Anderson',
       'MA Starc', 'JDS Neesham', 'AR Patel', 'M Vijay', 'R Tewatia',
       'SA Yadav', 'Shivam Sharma', 'Imran Tahir', 'V Shankar',
       'LMP Simmons', 'BCJ Cutting', 'K Santokie', 'S Gopal',
       'BE Hendricks', 'PJ Cummins', 'JW Hastings', 'Karanveer Singh',
       'DJ Muthuswami', 'TA Boult', 'SA Abbott', 'KC Cariappa',
       'DJ Hooda', 'J Suchith', 'D Wiese', 'MJ McClenaghan', 'HH Pandya',
       'RG More', 'SN Thakur', 'GS Sandhu', 'Gurkeerat Singh', 'J Yadav',
       'BB Sran', 'M Ashwin', 'C Munro', 'CR Brathwaite', 'MP Stoinis',
       'P Sahu', 'Mustafizur Rahman', 'AF Milne', 'Kuldeep Yadav',
       'KH Pandya', 'KJ Abbott', 'T Shamsi', 'S Kaushik', 'SM Boland',
       'Swapnil Singh', 'CJ Jordan', 'A Zampa', 'Sachin Baby', 'N Rana',
       'DL Chahar', 'KS Williamson', 'TS Mills', 'A Choudhary', 'TM Head',
       'Rashid Khan', 'BA Stokes', 'CR Woakes', 'T Natarajan',
       'RD Chahar', 'B Stanlake', 'Tejas Baroka', 'Basil Thampi',
       'C de Grandhomme', 'AJ Tye', 'LH Ferguson', 'Mohammad Nabi',
       'Mohammed Siraj', 'K Rabada', 'Washington Sundar', 'SS Agarwal',
       'NB Singh', 'RA Tripathi', 'Ankit Soni', 'MJ Henry', 'Avesh Khan',
       'MA Wood', 'M Markande', 'Mujeeb Ur Rahman', 'K Khejroliya',
       'K Gowtham', 'DJM Short', 'TK Curran', 'A Dananjaya',
       'Shivam Mavi', 'JC Archer', 'LE Plunkett', 'IS Sodhi', 'MK Lomror',
       'L Ngidi', 'KM Asif', 'DJ Willey', 'M Prasidh Krishna', 'MM Ali',
       'JPR Scantlebury-Searles', 'S Lamichhane', 'CJ Dala', 'KK Ahmed',
       'Navdeep Saini', 'S Dube', 'Rasikh Salam', 'KMA Paul', 'SM Curran',
       'CV Varun', 'GC Viljoen', 'Mandeep Singh', 'P Ray Barman',
       'MJ Santner', 'JP Behrendorff', 'SC Kuggeleijn', 'AS Joseph',
       'HF Gurney', 'S Midhun', 'R Parag', 'LS Livingstone', 'SN Khan',
       'Abhishek Sharma', 'Arshdeep Singh', 'SE Rutherford',
       'Harpreet Brar', 'Y Prithvi Raj', 'O Thomas', 'AS Roy',
       'S Sandeep Warrier', 'JL Pattinson', 'SS Cottrell', 'Ravi Bishnoi',
       'A Nortje', 'JR Hazlewood', 'KL Nagarkoti', 'I Udana',
       'Abdul Samad', 'Kartik Tyagi', 'TU Deshpande', 'CJ Green',
       'Shahbaz Ahmed', 'DR Sams', 'Monu Kumar', 'DA Warner', 'P Dubey',
       'KA Jamieson', 'M Jansen', 'C Sakariya', 'JA Richardson',
       'RP Meredith', 'LI Meriwala', 'Lalit Yadav', 'Jalaj S Saxena',
       'FA Allen', 'PWH de Silva', 'IC Porel', 'AU Rashid', 'NT Ellis',
       'VR Iyer', 'AK Markram', 'GHS Garton', 'Akash Singh',
       'GD Phillips', 'Umran Malik', 'K Yadav', 'RV Patel', 'OF Smith',
       'Akash Deep', 'PVD Chameera', 'Mohsin Khan', 'R Shepherd',
       'Mukesh Choudhary', 'D Pretorius', 'VG Arora', 'YBK Jaiswal',
       'Tilak Varma', 'DG Nalkande', 'M Theekshana', 'D Brevis',
       'R Powell', 'KR Sen', 'Yash Dayal', 'Shashank Singh',
       'Aman Hakim Khan', 'OC McCoy', 'HR Shokeen', 'A Badoni',
       'DJ Mitchell', 'Harshit Rana', 'SS Iyer', 'K Kartikeya',
       'Simarjeet Singh', 'Fazalhaq Farooqi', 'R Sai Kishore',
       'Ramandeep Singh', 'PH Solanki', 'M Pathirana', 'R Sanjay Yadav',
       'J Little', 'RS Hangargekar', 'Sikandar Raza', 'Mukesh Kumar',
       'KR Mayers', 'NA Saini', 'RJW Topley', 'MG Bracewell',
       'Arshad Khan', 'C Green', 'Yash Thakur', 'Suyash Sharma',
       'SSB Magala', 'Mohit Rathee', 'MW Short', 'Vijaykumar Vyshak',
       'Yudhvir Singh', 'Arjun Tendulkar', 'D Jansen', 'Noor Ahmad',
       'Naveen-ul-Haq', 'Mayank Dagar', 'Gurnoor Brar', 'AJ Hosein',
       'Akash Madhwal', 'R Goyal', 'T Stubbs', 'Vivrant Sharma',
       'JE Root', 'Nithish Kumar Reddy', 'H Sharma', 'Sumit Kumar',
       'N Burger', 'L Wood', 'SZ Mulani', 'Naman Dhir', 'G Coetzee',
       'Azmatullah Omarzai', 'SH Johnson', 'KT Maphaka', 'M Siddharth',
       'MP Yadav', 'R Ravindra', 'KA Maharaj', 'WG Jacks', 'S Joseph',
       'Arshad Khan (2)', 'M Shahrukh Khan', 'N Thushara', 'LB Williams',
       'RJ Gleeson', 'MJ Suthar', 'A Kamboj', 'V Viyaskanth',
       'V Kaverappa', 'Gulbadin Naib', 'N Wadhera', 'Atharva Taide',
       'PVSN Raju', 'V Puthur', 'V Nigam', 'DS Rathi', 'Prince Yadav',
       'Ishan Kishan', 'Zeeshan Ansari', 'PWA Mulder', 'J Overton',
       'Ashwani Kumar', 'PHKD Mendis', 'E Malinga', 'XC Bartlett',
       'C Bosch', 'Karim Janat', 'Suryansh Shedge', 'M Tiwari',
       'Harsh Dubey', "W O'Rourke", 'Musheer Khan'], dtype=object)

In [ ]:
train_df['bowler']=train_df['bowler'].apply(lambda x:x.lower())

In [ ]:
train_df.groupby('bowler')['valid_ball'].value_counts().reset_index().sort_values(by='count',ascending=False).head(10)

               bowler  valid_ball  count
679          r ashwin           1   4710
872         sp narine           1   4351
132           b kumar           1   4222
712         ra jadeja           1   4056
664         pp chawla           1   3850
1001        ys chahal           1   3791
296   harbhajan singh           1   3416
13           a mishra           1   3371
370         jj bumrah           1   3359
98           ar patel           1   3321

here the bowler defines the name of the bowler[50] total number of bowler and weather the balll is valid or not

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
train_df['runs_extras'].unique()

array([1, 0, 5, 4, 2, 3, 7])

DEFINES THE EXTRA RUNS A BOLLWER GETS

In [ ]:
train_df.groupby('bowler')['runs_extras'].sum().sort_values(ascending=False).head(10)

bowler
b kumar           320
sl malinga        292
r ashwin          263
mohammed siraj    261
dj bravo          258
ut yadav          257
i sharma          247
hv patel          243
jj bumrah         238
p kumar           236
Name: runs_extras, dtype: int64

runs_extra defines the extra run which are faced by the bowler inclide[legby,wide,freehit....]

In [ ]:
train_df.head(13
              )

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.5,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
6,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.6,bb mccullum,2,0,1,p kumar,1,1,1,0,False,legbyes,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,6,0,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False
7,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.1,bb mccullum,2,0,1,z khan,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,7,0,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False
8,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.2,bb mccullum,2,4,1,z khan,1,0,4,4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,7,8,0,NaN,4,7,0,"('BB McCullum', 'SC Ganguly')",NaN,False
9,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.3,bb mccullum,2,4,1,z khan,1,0,4,4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,11,9,0,NaN,8,8,0,"('BB McCullum', 'SC Ganguly')",NaN,False
10,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.4,bb mccullum,2,6,1,z khan,1,0,6,6,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,17,10,0,NaN,14,9,0,"('BB McCullum', 'SC Ganguly')",NaN,False
11,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.5,bb mccullum,2,4,1,z khan,1,0,4,4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,21,11,0,NaN,18,10,0,"('BB McCullum', 'SC Ganguly')",NaN,False
12,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.6,bb mccullum,2,0,1,z khan,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,21,12,0,NaN,18,11,0,"('BB McCullum', 'SC Ganguly')",NaN,False

the runs total is defines as the sumition of extra runs and runbatter

In [ ]:
train_df['runs_total'].value_counts()

runs_total
1    115711
0     95778
4     32502
2     18349
6     14259
3       954
5       557
7        95
Name: count, dtype: int64

In [ ]:
train_df[['runs_batter','runs_extras','runs_total']].tail(30)

        runs_batter  runs_extras  runs_total
278175            1            0           1
278176            6            0           6
278177            0            1           1
278178            0            1           1
278179            1            0           1
278180            6            0           6
278181            0            0           0
278182            0            0           0
278183            6            0           6
278184            0            0           0
278185            1            0           1
278186            1            0           1
278187            0            1           1
278188            0            0           0
278189            0            1           1
278190            2            0           2
278191            1            0           1
278192            0            0           0
278193            6            0           6
278194            0            0           0
278195            0            0           0
278196            4            0           4
278197            2            0           2
278198            1            0           1
278199            0            0           0
278200            0            0           0
278201            6            0           6
278202            4            0           4
278203            6            0           6
278204            6            0           6

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

the runs_total will help us decid the overall runs of that match

In [ ]:
train_df.groupby(['match_id', 'batting_team'])['runs_total'].sum()

match_id  batting_team
335982    Kolkata Knight Riders          222
          Royal Challengers Bangalore     82
335983    Chennai Super Kings            240
          Kings XI Punjab                207
335984    Delhi Daredevils               132
          Rajasthan Royals               129
335985    Mumbai Indians                 165
          Royal Challengers Bangalore    166
335986    Deccan Chargers                110
          Kolkata Knight Riders          112
335987    Kings XI Punjab                166
          Rajasthan Royals               168
335988    Deccan Chargers                142
          Delhi Daredevils               143
335989    Chennai Super Kings            208
          Mumbai Indians                 202
335990    Deccan Chargers                214
          Rajasthan Royals               217
335991    Kings XI Punjab                182
          Mumbai Indians                 116
335992    Rajasthan Royals               138
          Royal Challengers Bangalore    135
335993    Chennai Super Kings            152
          Kolkata Knight Riders          147
335994    Deccan Chargers                155
          Mumbai Indians                 154
335995    Delhi Daredevils               158
          Kings XI Punjab                162
335996    Chennai Super Kings            178
          Royal Challengers Bangalore    165
335997    Kolkata Knight Riders          137
          Mumbai Indians                 138
335998    Delhi Daredevils               191
          Royal Challengers Bangalore    181
335999    Deccan Chargers                164
          Kings XI Punjab                167
336000    Kolkata Knight Riders          151
          Rajasthan Royals               196
336001    Chennai Super Kings            169
          Delhi Daredevils               172
336002    Deccan Chargers                165
          Royal Challengers Bangalore    171
336003    Kings XI Punjab                178
          Kolkata Knight Riders          169
336004    Delhi Daredevils               133
          Mumbai Indians                 162
336005    Chennai Super Kings            109
          Rajasthan Royals               110
336006    Kings XI Punjab                127
          Royal Challengers Bangalore    126
336007    Chennai Super Kings            144
          Deccan Chargers                148
336008    Mumbai Indians                 104
          Rajasthan Royals               103
336009    Chennai Super Kings            188
          Delhi Daredevils               187
336010    Kolkata Knight Riders          129
          Royal Challengers Bangalore    124
336011    Deccan Chargers                140
          Rajasthan Royals               141
336012    Mumbai Indians                 126
          Royal Challengers Bangalore    122
336013    Chennai Super Kings            181
          Kings XI Punjab                163
336014    Deccan Chargers                181
          Kolkata Knight Riders          204
336015    Delhi Daredevils               156
          Rajasthan Royals               159
336016    Kings XI Punjab                144
          Royal Challengers Bangalore    143
336017    Delhi Daredevils               110
          Kolkata Knight Riders          133
336018    Chennai Super Kings            156
          Mumbai Indians                 158
336019    Kings XI Punjab                221
          Rajasthan Royals               180
336020    Deccan Chargers                182
          Delhi Daredevils               194
336021    Kolkata Knight Riders           67
          Mumbai Indians                  68
336022    Delhi Daredevils               118
          Kings XI Punjab                 94
336023    Rajasthan Royals               197
          Royal Challengers Bangalore    132
336024    Deccan Chargers                153
          Mumbai Indians                 178
336025    Chennai Super Kings             55
          Kolkata Knight Riders          149
336026    Delhi Daredevils               158
          Royal Challengers Bangalore    154
336027    Kolkata Knight Riders          147
          Rajasthan Royals               150
336028    Kings XI Punjab                189
          Mumbai Indians                 188
336029    Chennai Super Kings            112
          Royal Challengers Bangalore    126
336031    Deccan Chargers                175
          Kings XI Punjab                178
336032    Delhi Daredevils               179
          Mumbai Indians                 176
336033    Chennai Super Kings            201
          Rajasthan Royals               211
336034    Deccan Chargers                153
          Royal Challengers Bangalore    156
336035    Kings XI Punjab                174
          Kolkata Knight Riders          175
336036    Mumbai Indians                 145
          Rajasthan Royals               146
336037    Chennai Super Kings            148
          Deccan Chargers                147
336038    Delhi Daredevils                87
          Rajasthan Royals               192
336039    Chennai Super Kings            116
          Kings XI Punjab                112
336040    Chennai Super Kings            163
          Rajasthan Royals               164
392181    Chennai Super Kings            146
          Mumbai Indians                 165
392182    Rajasthan Royals                58
          Royal Challengers Bangalore    133
392183    Delhi Daredevils                58
          Kings XI Punjab                104
392184    Deccan Chargers                104
          Kolkata Knight Riders          101
392185    Chennai Super Kings            179
          Royal Challengers Bangalore     87
392186    Kings XI Punjab                158
          Kolkata Knight Riders           79
392188    Deccan Chargers                184
          Royal Challengers Bangalore    160
392189    Chennai Super Kings            180
          Delhi Daredevils               189
392190    Kolkata Knight Riders          165
          Rajasthan Royals               168
392191    Kings XI Punjab                173
          Royal Challengers Bangalore    168
392192    Deccan Chargers                168
          Mumbai Indians                 156
392194    Delhi Daredevils               150
          Royal Challengers Bangalore    149
392195    Kings XI Punjab                139
          Rajasthan Royals               112
392196    Chennai Super Kings            165
          Deccan Chargers                169
392197    Kolkata Knight Riders           95
          Mumbai Indians                 187
392198    Delhi Daredevils               143
          Rajasthan Royals               147
392199    Kolkata Knight Riders          139
          Royal Challengers Bangalore    143
392200    Kings XI Punjab                119
          Mumbai Indians                 116
392201    Deccan Chargers                148
          Delhi Daredevils               150
392202    Chennai Super Kings            164
          Rajasthan Royals               126
392203    Kolkata Knight Riders          139
          Mumbai Indians                 148
392204    Kings XI Punjab                137
          Royal Challengers Bangalore    145
392205    Deccan Chargers                141
          Rajasthan Royals               142
392206    Chennai Super Kings            163
          Delhi Daredevils               145
392207    Kings XI Punjab                154
          Kolkata Knight Riders          153
392208    Mumbai Indians                 149
          Royal Challengers Bangalore    150
392209    Chennai Super Kings            178
          Deccan Chargers                100
392210    Kings XI Punjab                133
          Rajasthan Royals               211
392211    Delhi Daredevils               157
          Kolkata Knight Riders          154
392212    Deccan Chargers                145
          Mumbai Indians                 126
392213    Rajasthan Royals               107
          Royal Challengers Bangalore    105
392214    Chennai Super Kings            185
          Kings XI Punjab                174
392215    Delhi Daredevils               118
          Mumbai Indians                 116
392216    Deccan Chargers                168
          Kings XI Punjab                169
392217    Chennai Super Kings            141
          Rajasthan Royals               140
392218    Mumbai Indians                 157
          Royal Challengers Bangalore    141
392219    Delhi Daredevils               125
          Kolkata Knight Riders          123
392220    Deccan Chargers                166
          Rajasthan Royals               113
392221    Kolkata Knight Riders          173
          Royal Challengers Bangalore    176
392222    Kings XI Punjab                119
          Mumbai Indians                 122
392223    Deccan Chargers                161
          Delhi Daredevils               173
392224    Chennai Super Kings            129
          Royal Challengers Bangalore    132
392225    Mumbai Indians                 143
          Rajasthan Royals               145
392226    Delhi Daredevils               120
          Kings XI Punjab                123
392227    Chennai Super Kings            151
          Mumbai Indians                 147
392228    Deccan Chargers                166
          Kolkata Knight Riders          160
392229    Deccan Chargers                133
          Kings XI Punjab                134
392230    Delhi Daredevils               150
          Rajasthan Royals               136
392231    Chennai Super Kings            188
          Kolkata Knight Riders          189
392232    Delhi Daredevils               134
          Royal Challengers Bangalore    135
392233    Kolkata Knight Riders          102
          Rajasthan Royals               101
392234    Chennai Super Kings            116
          Kings XI Punjab                 92
392235    Delhi Daredevils               166
          Mumbai Indians                 165
392236    Deccan Chargers                158
          Royal Challengers Bangalore    170
392237    Deccan Chargers                154
          Delhi Daredevils               153
392238    Chennai Super Kings            146
          Royal Challengers Bangalore    149
392239    Deccan Chargers                143
          Royal Challengers Bangalore    137
419106    Deccan Chargers                150
          Kolkata Knight Riders          161
419107    Mumbai Indians                 212
          Rajasthan Royals               208
419108    Delhi Daredevils               146
          Kings XI Punjab                142
419109    Kolkata Knight Riders          136
          Royal Challengers Bangalore    135
419110    Chennai Super Kings            159
          Deccan Chargers                190
419111    Delhi Daredevils               142
          Rajasthan Royals               141
419112    Kings XI Punjab                203
          Royal Challengers Bangalore    204
419113    Chennai Super Kings            164
          Kolkata Knight Riders          109
419114    Delhi Daredevils               120
          Mumbai Indians                 218
419115    Rajasthan Royals                92
          Royal Challengers Bangalore     93
419116    Chennai Super Kings            190
          Delhi Daredevils               185
419117    Deccan Chargers                170
          Kings XI Punjab                164
419118    Kolkata Knight Riders          134
          Rajasthan Royals               168
419119    Mumbai Indians                 151
          Royal Challengers Bangalore    155
419120    Deccan Chargers                171
          Delhi Daredevils               161
419121    Chennai Super Kings            145
          Kings XI Punjab                146
419122    Kolkata Knight Riders          155
          Mumbai Indians                 156
419123    Chennai Super Kings            135
          Royal Challengers Bangalore    171
419124    Kings XI Punjab                152
          Rajasthan Royals               183
419125    Chennai Super Kings            180
          Mumbai Indians                 181
419126    Deccan Chargers                148
          Rajasthan Royals               151
419127    Kings XI Punjab                144
          Kolkata Knight Riders          183
419128    Delhi Daredevils               183
          Royal Challengers Bangalore    166
419129    Chennai Super Kings            160
          Rajasthan Royals               177
419130    Deccan Chargers                131
          Mumbai Indians                 172
419131    Delhi Daredevils               177
          Kolkata Knight Riders          137
419132    Kings XI Punjab                163
          Mumbai Indians                 164
419133    Chennai Super Kings            162
          Royal Challengers Bangalore    161
419134    Delhi Daredevils               188
          Rajasthan Royals               121
419135    Deccan Chargers                157
          Kolkata Knight Riders          181
419136    Kings XI Punjab                181
          Royal Challengers Bangalore    184
419137    Chennai Super Kings            246
          Rajasthan Royals               223
419138    Deccan Chargers                115
          Mumbai Indians                 178
419139    Kings XI Punjab                204
          Kolkata Knight Riders          200
419140    Delhi Daredevils               184
          Royal Challengers Bangalore    147
419141    Deccan Chargers                157
          Rajasthan Royals               159
419142    Chennai Super Kings            165
          Mumbai Indians                 141
419143    Kings XI Punjab                153
          Rajasthan Royals               157
419144    Delhi Daredevils               167
          Kolkata Knight Riders          181
419145    Deccan Chargers                186
          Royal Challengers Bangalore    184
419146    Kings XI Punjab                158
          Mumbai Indians                 154
419147    Chennai Super Kings            138
          Deccan Chargers                139
419148    Kolkata Knight Riders          160
          Royal Challengers Bangalore    162
419149    Delhi Daredevils               111
          Kings XI Punjab                112
419150    Mumbai Indians                 174
          Rajasthan Royals               137
419151    Deccan Chargers                151
          Royal Challengers Bangalore    138
419152    Delhi Daredevils               144
          Mumbai Indians                 183
419153    Chennai Super Kings            143
          Kolkata Knight Riders          139
419154    Rajasthan Royals               130
          Royal Challengers Bangalore    132
419155    Chennai Super Kings            112
          Delhi Daredevils               113
419156    Deccan Chargers                178
          Kings XI Punjab                174
419157    Mumbai Indians                 191
          Royal Challengers Bangalore    134
419158    Kolkata Knight Riders          133
          Rajasthan Royals               132
419159    Chennai Super Kings            195
          Kings XI Punjab                192
419160    Deccan Chargers                145
          Delhi Daredevils               134
419161    Kolkata Knight Riders          135
          Mumbai Indians                 133
419162    Mumbai Indians                 184
          Royal Challengers Bangalore    149
419163    Chennai Super Kings            142
          Deccan Chargers                104
419164    Deccan Chargers                 82
          Royal Challengers Bangalore     86
419165    Chennai Super Kings            168
          Mumbai Indians                 146
501198    Chennai Super Kings            153
          Kolkata Knight Riders          151
501199    Deccan Chargers                137
          Rajasthan Royals               141
501200    Kochi Tuskers Kerala           161
          Royal Challengers Bangalore    162
501201    Delhi Daredevils                95
          Mumbai Indians                  99
501202    Kings XI Punjab                112
          Pune Warriors                  113
501203    Deccan Chargers                154
          Kolkata Knight Riders          163
501204    Delhi Daredevils               151
          Rajasthan Royals               152
501205    Mumbai Indians                 143
          Royal Challengers Bangalore    140
501206    Chennai Super Kings            188
          Kings XI Punjab                193
501207    Kochi Tuskers Kerala           148
          Pune Warriors                  151
501208    Deccan Chargers                175
          Royal Challengers Bangalore    142
501209    Kolkata Knight Riders          160
          Rajasthan Royals               159
501210    Kochi Tuskers Kerala           184
          Mumbai Indians                 182
501211    Chennai Super Kings            183
          Royal Challengers Bangalore    162
501212    Deccan Chargers                165
          Kings XI Punjab                166
501213    Delhi Daredevils               190
          Pune Warriors                  187
501214    Kolkata Knight Riders           85
          Rajasthan Royals                81
501215    Chennai Super Kings            131
          Kochi Tuskers Kerala           135
501216    Deccan Chargers                168
          Delhi Daredevils               152
501218    Mumbai Indians                 124
          Pune Warriors                  118
501219    Kochi Tuskers Kerala           132
          Kolkata Knight Riders          126
501220    Kings XI Punjab                195
          Rajasthan Royals               147
501221    Chennai Super Kings            156
          Mumbai Indians                 164
501222    Kolkata Knight Riders          171
          Royal Challengers Bangalore    175
501223    Delhi Daredevils               231
          Kings XI Punjab                202
501224    Deccan Chargers                135
          Mumbai Indians                 172
501225    Kochi Tuskers Kerala           109
          Rajasthan Royals               111
501226    Chennai Super Kings            142
          Pune Warriors                  117
501227    Delhi Daredevils               160
          Royal Challengers Bangalore    161
501228    Chennai Super Kings            145
          Pune Warriors                  141
501229    Deccan Chargers                129
          Kochi Tuskers Kerala            74
501230    Delhi Daredevils               131
          Kolkata Knight Riders          148
501231    Mumbai Indians                  94
          Rajasthan Royals                95
501232    Pune Warriors                  155
          Royal Challengers Bangalore    181
501233    Delhi Daredevils               157
          Kochi Tuskers Kerala           119
501234    Kings XI Punjab                119
          Kolkata Knight Riders          120
501235    Pune Warriors                  143
          Rajasthan Royals               144
501236    Chennai Super Kings            165
          Deccan Chargers                146
501237    Kings XI Punjab                136
          Mumbai Indians                 159
501238    Delhi Daredevils               140
          Kochi Tuskers Kerala           141
501239    Deccan Chargers                149
          Kolkata Knight Riders          169
501240    Chennai Super Kings            149
          Rajasthan Royals               147
501241    Mumbai Indians                 160
          Pune Warriors                  139
501242    Kochi Tuskers Kerala           156
          Kolkata Knight Riders          139
501243    Deccan Chargers                175
          Delhi Daredevils               179
501244    Kings XI Punjab                120
          Royal Challengers Bangalore    205
501245    Chennai Super Kings            114

In [ ]:
train_df.sample()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
88556,598064,2013-05-06,2,Kings XI Punjab,Royal Challengers Bangalore,7,7.5,da miller,5,1,1,m kartik,1,0,1,1,False,NaN,DJ Hussey,4,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,DA Miller,Kings XI Punjab,6 wickets,Kings XI Punjab,field,"Punjab Cricket Association Stadium, Mohali",Chandigarh,6,5,2013,2013,male,club,NaN,NaN,NaN,6,20,51,Unknown,Unknown,52,47,3,DA Miller,1,1,0,"('DA Miller', 'DJ Hussey')",NaN,False

we adding the 1 to the runs total as we are givoin the target so it is going to 1 +

In [ ]:
innings_totals = train_df.groupby(['match_id', 'innings'])['runs_total'].sum().reset_index()

# 2. Pivot or filter to get only Innings 1 totals (this is the base for the target)
target_map = innings_totals[innings_totals['innings'] == 1].set_index('match_id')['runs_total'] + 1

In [ ]:
innings_totals.head()

   match_id  innings  runs_total
0    335982        1         222
1    335982        2          82
2    335983        1         240
3    335983        2         207
4    335984        1         129

In [ ]:
target_map.head()

match_id
335982    223
335983    241
335984    130
335985    166
335986    111
Name: runs_total, dtype: int64

In [ ]:
# 3. Map that target back to the main dataframe
train_df['target_score'] = train_df['match_id'].map(target_map)

# 4. Calculate 'chased_score' (Total runs made by the team batting second)
chase_map = innings_totals[innings_totals['innings'] == 2].set_index('match_id')['runs_total']
train_df['chased_score'] = train_df['match_id'].map(chase_map).fillna(0)

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

# runs_bowler

In [ ]:
train_df['runs_bowler'].nunique()

8

In [ ]:
train_df['runs_bowler'].unique()

array([0, 1, 4, 6, 5, 2, 3, 7])

who are the top 10  bowler with most runs in ipl history

most expensive overs in an ipl match overs

In [ ]:
train_df.groupby(['match_id','bowler'])['runs_bowler'].sum().sort_values(ascending=False).reset_index().head(10)

   match_id            bowler  runs_bowler
0   1473439         jc archer           76
1   1473464    mohammed shami           75
2   1473507        w o'rourke           74
3   1426278         mm sharma           73
4   1136611      basil thampi           70
5   1359487        yash dayal           69
6   1426268        rjw topley           68
7   1426281            l wood           68
8   1422126        kt maphaka           66
9   1178423  mujeeb ur rahman           66

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

runs_not boundry

In [ ]:
train_df['runs_not_boundary'].unique()

array([False,  True])

In [ ]:
train_df['runs_not_boundary'].value_counts()

runs_not_boundary
False    278177
True         28
Name: count, dtype: int64

ther is no error in this perticular section as it define the runs made by running and not by hitting the boundary

In [ ]:
train_df[train_df['runs_not_boundary']==True].head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
7415,336014,2008-05-11,1,Kolkata Knight Riders,Deccan Chargers,19,19.6,lr shukla,6,6,1,rp singh,1,0,6,6,True,NaN,DJ Hussey,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,SC Ganguly,Kolkata Knight Riders,23 runs,Kolkata Knight Riders,bat,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,11,5,2008,2007/08,male,club,NaN,NaN,NaN,6,20,32,Unknown,Unknown,204,120,4,NaN,14,3,0,"('DJ Hussey', 'LR Shukla')",NaN,False,205,181.0
23804,392226,2009-05-15,2,Kings XI Punjab,Delhi Daredevils,1,1.3,sm katich,2,4,1,pj sangwan,1,0,4,4,True,NaN,S Sohal,1,NaN,NaN,NaN,121.0,NaN,NaN,NaN,NaN,False,B Lee,Kings XI Punjab,6 wickets,Kings XI Punjab,field,OUTsurance Oval,Bloemfontein,15,5,2009,2009,male,club,NaN,NaN,NaN,6,20,46,Unknown,Unknown,10,9,0,NaN,9,4,0,"('S Sohal', 'SM Katich')",NaN,False,121,123.0
47910,501225,2011-04-24,2,Rajasthan Royals,Kochi Tuskers Kerala,4,4.4,r dravid,2,4,1,r vinay kumar,1,0,4,4,True,NaN,SR Watson,1,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,False,SK Warne,Rajasthan Royals,8 wickets,Rajasthan Royals,field,Sawai Mansingh Stadium,Jaipur,24,4,2011,2011,male,club,NaN,NaN,NaN,6,20,28,Unknown,Unknown,32,28,0,NaN,18,16,0,"('R Dravid', 'SR Watson')",NaN,False,110,111.0
54289,501252,2011-05-11,2,Royal Challengers Bangalore,Rajasthan Royals,5,5.1,ch gayle,1,4,1,j botha,1,0,4,4,True,NaN,TM Dilshan,2,NaN,NaN,NaN,147.0,NaN,NaN,NaN,NaN,False,S Aravind,Royal Challengers Bangalore,9 wickets,Royal Challengers Bangalore,field,Sawai Mansingh Stadium,Jaipur,11,5,2011,2011,male,club,NaN,NaN,NaN,6,20,55,Unknown,Unknown,54,31,0,NaN,21,13,0,"('CH Gayle', 'TM Dilshan')",NaN,False,147,151.0
55278,501257,2011-05-15,1,Kings XI Punjab,Delhi Daredevils,2,2.3,pc valthaty,1,4,1,ik pathan,1,0,4,4,True,NaN,AC Gilchrist,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,PP Chawla,Kings XI Punjab,29 runs,Delhi Daredevils,field,Himachal Pradesh Cricket Association Stadium,Dharamsala,15,5,2011,2011,male,club,NaN,NaN,NaN,6,20,60,Unknown,Unknown,11,15,0,NaN,5,8,0,"('AC Gilchrist', 'PC Valthaty')",NaN,False,171,141.0

In [ ]:
train_df.iloc[:,15:].head()

,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

extra runs

In [ ]:
train_df['extra_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty',
       'penalty, wides', 'byes, noballs', 'legbyes, noballs'],
      dtype=object)

In [ ]:
train_df['extra_type'].value_counts()

extra_type
wides               9079
legbyes             4203
noballs             1136
byes                 686
byes, noballs         15
legbyes, noballs      12
penalty, wides         1
penalty                1
Name: count, dtype: int64

In [ ]:
train_df[train_df['extra_type']=='wides'].groupby('bowler')['extra_type'].value_counts().reset_index().sort_values('count',ascending=False
                                                                                                                   ).head()

             bowler extra_type  count
100        dj bravo      wides    167
306        r ashwin      wides    154
60          b kumar      wides    144
257  mohammed siraj      wides    140
386      sl malinga      wides    128

In [ ]:
train_df['extra_type'].fillna('no_extra_runs',inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\267448785.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['extra_type'].fillna('no_extra_runs',inplace=True)

In [ ]:
train_df['extra_type'].value_counts()

extra_type
no_extra_runs       263072
wides                 9079
legbyes               4203
noballs               1136
byes                   686
byes, noballs           15
legbyes, noballs        12
penalty, wides           1
penalty                  1
Name: count, dtype: int64

In [ ]:
train_df.isnull().sum()

match_id                  0
date                      0
innings                   0
batting_team              0
bowling_team              0
over                      0
ball_no                   0
batter                    0
bat_pos                   0
runs_batter               0
balls_faced               0
bowler                    0
valid_ball                0
runs_extras               0
runs_total                0
runs_bowler               0
runs_not_boundary         0
extra_type                0
non_striker               0
non_striker_pos           0
wicket_kind          264382
player_out           264382
fielders             268192
runs_target          144302
review_batter        277333
team_reviewed        277333
review_decision      277333
umpire               277333
umpires_call              0
player_of_match           0
match_won_by              0
win_outcome            4702
toss_winner               0
toss_decision             0
venue                     0
city                      0
day                       0
month                     0
year                      0
season                    0
gender                    0
team_type                 0
superover_winner     274309
result_type          273503
method               274315
balls_per_over            0
overs                     0
event_match_no            0
stage                     0
match_number              0
team_runs                 0
team_balls                0
team_wicket               0
new_batter           264884
batter_runs               0
batter_balls              0
bowler_wicket             0
batting_partners          0
next_batter          264884
striker_out               0
target_score              0
chased_score              0
dtype: int64

In [ ]:
train_df.iloc[:,16:].head()

,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,False,no_extra_runs,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,False,no_extra_runs,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,False,no_extra_runs,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

In [ ]:
train_df['non_striker'].nunique()

692

In [ ]:
train_df['non_striker']=train_df['non_striker'].apply(lambda x:x.lower())

In [ ]:
train_df['non_striker_pos'].nunique()

11

In [ ]:
train_df['non_striker_pos'].unique()

array([ 2,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
train_df['wicket_kind'].nunique()

10

In [ ]:
train_df['wicket_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [ ]:
train_df['wicket_kind'].value_counts()

wicket_kind
caught                   8665
bowled                   2345
run out                  1153
lbw                       853
caught and bowled         388
stumped                   376
hit wicket                 18
retired hurt               17
retired out                 5
obstructing the field       3
Name: count, dtype: int64

In [ ]:
train_df['wicket_kind'].fillna("not out",inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\1949907871.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['wicket_kind'].fillna("not out",inplace=True)

In [ ]:
train_df['wicket_kind'].value_counts()

wicket_kind
not out                  264382
caught                     8665
bowled                     2345
run out                    1153
lbw                         853
caught and bowled           388
stumped                     376
hit wicket                   18
retired hurt                 17
retired out                   5
obstructing the field         3
Name: count, dtype: int64

In [ ]:
train_df.iloc[:,20:].head()

,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,not out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,not out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,not out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,not out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,not out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

In [ ]:
train_df['player_out'].value_counts()

player_out
RG Sharma                  237
V Kohli                    219
S Dhawan                   193
KD Karthik                 184
RV Uthappa                 180
SK Raina                   171
AM Rahane                  165
DA Warner                  164
AT Rayudu                  155
SV Samson                  153
MS Dhoni                   142
G Gambhir                  136
F du Plessis               136
MK Pandey                  135
AB de Villiers             130
PA Patel                   126
SR Watson                  126
CH Gayle                   126
SA Yadav                   124
KA Pollard                 121
WP Saha                    121
MA Agarwal                 120
GJ Maxwell                 118
RA Jadeja                  117
KL Rahul                   115
Yuvraj Singh               111
SS Iyer                    110
YK Pathan                  110
Q de Kock                  109
RR Pant                    104
JC Buttler                 104
BB McCullum                104
N Rana                     103
Ishan Kishan               103
M Vijay                    101
SP Narine                  101
V Sehwag                    99
HH Pandya                   98
Shubman Gill                98
AD Russell                  95
RA Tripathi                 88
DA Miller                   87
AR Patel                    87
JH Kallis                   85
DJ Hooda                    85
DR Smith                    84
AJ Finch                    84
Mandeep Singh               82
KH Pandya                   81
PP Shaw                     79
R Dravid                    77
AC Gilchrist                76
NV Ojha                     75
SPD Smith                   72
MP Stoinis                  72
D Padikkal                  71
KK Nair                     71
SR Tendulkar                69
N Pooran                    69
DJ Bravo                    69
Abhishek Sharma             67
KC Sangakkara               65
DPMD Jayawardene            64
R Ashwin                    64
YBK Jaiswal                 64
SE Marsh                    63
RD Gaikwad                  62
EJG Morgan                  62
R Parag                     61
S Dube                      61
KS Williamson               60
MK Tiwary                   59
PP Chawla                   56
Harbhajan Singh             55
KM Jadhav                   54
SC Ganguly                  53
MM Ali                      53
IK Pathan                   53
SS Tiwary                   52
MEK Hussey                  51
SO Hetmyer                  51
JP Duminy                   51
P Simran Singh              51
DJ Hussey                   49
M Vohra                     49
VR Iyer                     49
R Tewatia                   48
JM Bairstow                 48
MR Marsh                    47
S Badrinath                 47
V Shankar                   47
AK Markram                  46
STR Binny                   46
Y Venugopal Rao             44
TM Dilshan                  43
Rashid Khan                 42
BJ Hodge                    42
Shakib Al Hasan             41
JA Morkel                   40
SM Curran                   40
Tilak Varma                 40
LS Livingstone              40
LRPL Taylor                 40
JM Sharma                   39
Abdul Samad                 39
CA Lynn                     39
BA Stokes                   38
P Kumar                     38
MS Bisla                    38
AM Nayar                    38
B Kumar                     38
H Klaasen                   37
RM Patidar                  36
CL White                    36
B Sai Sudharsan             36
RK Singh                    36
MC Henriques                36
A Badoni                    36
M Shahrukh Khan             34
Washington Sundar           33
TM Head                     33
A Mishra                    32
HH Gibbs                    32
TL Suman                    32
PD Salt                     31
DT Christian                31
ML Hayden                   31
AD Mathews                  31
PJ Cummins                  30
R Bhatia                    30
Shahbaz Ahmed               29
HV Patel                    29
MK Lomror                   29
JD Ryder                    28
CH Morris                   28
ST Jayasuriya               28
R Vinay Kumar               28
SN Thakur                   28
KP Pietersen                28
LR Shukla                   27
LMP Simmons                 27
N Wadhera                   27
A Symonds                   27
GJ Bailey                   27
JP Faulkner                 26
Abishek Porel               26
SW Billings                 26
KV Sharma                   26
SN Khan                     26
P Negi                      26
GC Smith                    26
TH David                    26
DP Conway                   25
AP Tare                     24
E Lewis                     24
Gurkeerat Singh             24
Dhruv Jurel                 24
M Manhas                    23
DW Steyn                    22
NLTC Perera                 22
PC Valthaty                 22
CJ Anderson                 22
UT Yadav                    21
JO Holder                   21
AL Menaria                  21
RR Rossouw                  20
SK Warne                    20
J Botha                     20
SP Goswami                  20
SA Asnodkar                 20
R Powell                    20
S Sohal                     20
UBT Chand                   20
GH Vihari                   20
CA Pujara                   19
JJ Roy                      19
A Manohar                   19
JC Archer                   19
VVS Laxman                  19
Shashank Singh              19
Azhar Mahmood               19
DB Ravi Teja                19
M Kaif                      18
Priyansh Arya               18
PK Garg                     18
MM Sharma                   18
RS Bopara                   18
K Gowtham                   18
K Rabada                    18
Rahmanullah Gurbaz          17
R Ravindra                  17
C Green                     17
Nithish Kumar Reddy         17
WG Jacks                    17
Mohammad Nabi               17
T Stubbs                    17
R Sathish                   17
SL Malinga                  16
JD Unadkat                  16
Anuj Rawat                  16
SE Rutherford               16
C de Grandhomme             16
RD Chahar                   16
A Raghuvanshi               16
JR Hopes                    16
Lalit Yadav                 16
MD Mishra                   16
D Brevis                    16
RP Singh                    15
K Goel                      15
J Fraser-McGurk             15
A Ashish Reddy              15
DJG Sammy                   15
OA Shah                     15
Kuldeep Yadav               15
PWH de Silva                15
B Chipli                    15
Ashutosh Sharma             14
S Nadeem                    14
S Gopal                     14
Y Nagar                     14
MV Boucher                  14
Z Khan                      14
MS Wade                     14
Naman Dhir                  14
DB Das                      14
R Sharma                    14
RN ten Doeschate            14
Mohammed Shami              14
RD Rickelton                13
HM Amla                     13
CR Brathwaite               13
TG Southee                  13
MG Johnson                  13
DJ Mitchell                 13
KR Mayers                   13
PBB Rajapaksa               13
AA Jhunjhunwala             13
MN Samuels                  13
MJ McClenaghan              13
MJ Lumb                     12
CA Ingram                   12
C Munro                     12
MJ Guptill                  12
Harpreet Brar               12
RJ Harris                   12
PP Ojha                     12
JEC Franklin                11
M Jansen                    11
LA Pomersbach               11
M Morkel                    11
RE van der Merwe            11
Ramandeep Singh             11
R Dhawan                    11
MA Starc                    11
BCJ Cutting                 11
NM Coulter-Nile             11
P Dogra                     11
DH Yagnik                   10
PA Reddy                    10
N Saini                     10
WD Parnell                  10
B Lee                       10
Atharva Taide               10
MS Gony                     10
AD Nath                     10
CJ Jordan                   10
CM Gautam                   10
FY Fazal                    10
Ravi Bishnoi                10
SM Katich                   10
AB Dinda                    10
MF Maharoof                 10
AB Agarkar                  10
SS Prabhudessai             10
Mohammed Siraj              10
DR Sams                      9
N Jagadeesan                 9
JDS Neesham                  9
SP Fleming                   9
Aman Hakim Khan              9
Anmolpreet Singh             9
AS Raut                      9
Aniket Verma                 9
RT Ponting                   9
AJ Tye                       9
Sachin Baby                  9
TA Boult                     9
Shivam Mavi                  9
M Ashwin                     9
AD Mascarenhas               9
DS Kulkarni                  9
JP Inglis                    9
KK Cooper                    9
HC Brook                     9
Shahid Afridi                8
MJ Santner                   8
YV Takawale                  8
PJ Sangwan                   8
PR Shah                      8
Noor Ahmad                   8
SD Hope                      8
JDP Oram                     8
Bipul Sharma                 8
WPUJC Vaas                   8
Azmatullah Omarzai           8
SM Pollock                   8
DL Vettori                   8
DL Chahar                    8
S Anirudha                   8
L Balaji                     8
W Jaffer                     8
R McLaren                    8
S Vidyut                     8
SD Chitnis                   7
V Suryavanshi                7
JJ Bumrah                    7
V Nigam                      7
Sameer Rizvi                 7
YS Chahal                    7
A Nehra                      7
DJM Short                    7
SK Trivedi                   7
Mohammad Hafeez              7
BJ Rohrer                    7
GD Phillips                  7
Salman Butt                  7
M Kartik                     7
SB Bangar                    7
R Shepherd                   7
DJ Jacobs                    7
SB Styris                    7
Harpreet Singh               7
AC Blizzard                  7
Ankit Sharma                 7
MC Juneja                    7
Sikandar Raza                7
A Mhatre                     7
RJ Quiney                    7
KS Bharat                    7
Misbah-ul-Haq                7
MM Patel                     6
SB Dubey                     6
UT Khawaja                   6
Sandeep Sharma               6
AD Hales                     6
SP Jackson                   6
B Akhil                      6
I Sharma                     6
A Chopra                     6
A Nortje                     6
C Sakariya                   6
Vishnu Vinod                 6
Arshdeep Singh               6
M Muralitharan               6
CR Woakes                    6
MW Short                     6
MJ Clarke                    6
G Coetzee                    6
RE Levi                      6
CJ Ferguson                  6
Harshit Rana                 6
WA Mota                      6
KB Arun Karthik              5
RV Gomez                     5
Arshad Khan                  5
AUK Pathan                   5
Kamran Akmal                 5
TR Birt                      5
AS Yadav                     5
VR Aaron                     5
AG Paunikar                  5
R Rampaul                    5
BB Samantray                 5
LJ Wright                    5
RV Patel                     5
A Mithun                     5
PD Collingwood               5
Rasikh Salam                 5
IR Jaggi                     5
M Rawat                      5
D Wiese                      5
KMA Paul                     5
SK Rasheed                   5
AS Rajpoot                   5
S Badree                     5
A Zampa                      5
Swapnil Singh                5
KK Ahmed                     5
AJ Turner                    5
AB McDonald                  5
TK Curran                    5
AA Bilakhia                  5
L Ronchi                     5
M Klinger                    4
DJ Harris                    4
K Kartikeya                  4
AS Roy                       4
AP Majumdar                  4
Sunny Singh                  4
Yudhvir Singh                4
S Rana                       4
S Sreesanth                  4
Imran Tahir                  4
Anirudh Singh                4
KL Nagarkoti                 4
JR Philippe                  4
CV Varun                     4
AC Voges                     4
KA Jamieson                  4
Kartik Tyagi                 4
Joginder Sharma              4
Shoaib Malik                 4
VG Arora                     4
Harmeet Singh                4
PVD Chameera                 4
RR Sarwan                    4
D Pretorius                  4
NT Ellis                     4
LA Carseldine                4
NS Naik                      4
J Yadav                      4
NK Patel                     4
Anureet Singh                4
A Singh                      4
Navdeep Saini                4
RK Bhui                      4
J Suchith                    4
S Aravind                    4
Yashpal Singh                4
AF Milne                     4
S Kaul                       4
TS Mills                     4
R Sai Kishore                4
PHKD Mendis                  4
D Ferreira                   3
Saurav Chauhan               3
Kumar Kushagra               3
T Kohler-Cadmore             3
Suryansh Shedge              3
R Bishnoi                    3
M Markande                   3
SA Abbott                    3
KC Cariappa                  3
MN van Wyk                   3
RR Powar                     3
Mujeeb Ur Rahman             3
M Prasidh Krishna            3
J Arunkumar                  3
I Udana                      3
Sohail Tanvir                3
T Taibu                      3
BR Dunk                      3
CK Kapugedera                3
SW Tait                      3
NJ Maddinson                 3
TL Seifert                   3
Avesh Khan                   3
BMAJ Mendis                  3
Umar Gul                     3
KW Richardson                3
A Kumble                     3
JA Richardson                3
S Narwal                     3
OF Smith                     3
Akash Deep                   3
HR Shokeen                   3
GB Hogg                      3
RJ Peterson                  3
Mohsin Khan                  3
KS Sharma                    3
YV Dhull                     3
Urvil Patel                  3
T Kohli                      3
PN Mankad                    3
M Theekshana                 3
Simarjeet Singh              3
DJ Thornely                  3
S Chanderpaul                3
B Indrajith                  3
Yash Dayal                   3
LH Ferguson                  3
JM Kemp                      2
Iqbal Abdulla                2
AN Ghosh                     2
BAW Mendis                   2
DS Lehmann                   2
SB Wagh                      2
Vijaykumar Vyshak            2
D Salunkhe                   2
AB Barath                    2
CK Langeveldt                2
AP Dole                      2
HE van der Dussen            2
S Sriram                     2
DJ Willey                    2
RA Bawa                      2
Parvez Rasool                2
T Thushara                   2
T Banton                     2
VH Zol                       2
PV Tambe                     2
VY Mahesh                    2
LPC Silva                    2
DR Shorey                    2
GC Viljoen                   2
IS Sodhi                     2
Ankit Soni                   2
Mustafizur Rahman            2
Shoaib Ahmed                 2
MA Wood                      2
TD Paine                     2
AA Chavan                    2
Sumit Kumar                  2
DG Nalkande                  2
A Kamboj                     2
C Bosch                      2
JG Bethell                   2
A Mukund                     2
F Behardien                  2
Pankaj Singh                 2
SB Joshi                     2
R Minz                       2
A Flintoff                   2
T Henderson                  2
AA Kulkarni                  2
ER Dwivedi                   2
AC Thomas                    2
MA Khote                     2
Sanvir Singh                 2
MD Shanaka                   2
J Syed Mohammad              2
VRV Singh                    2
B Laughlin                   2
MDKJ Perera                  2
J Theron                     2
FA Allen                     2
P Awana                      2
TU Deshpande                 2
Mohammad Asif                2
DT Patil                     2
Virat Singh                  2
AT Carey                     2
JJ van der Wath              2
MG Bracewell                 2
Umran Malik                  2
AU Rashid                    2
RR Raje                      1
D du Preez                   1
BE Hendricks                 1
M de Lange                   1
R Shukla                     1
Shivam Sharma                1
Karanveer Singh              1
FH Edwards                   1
S Lamichhane                 1
JL Denly                     1
SD Lad                       1
A Uniyal                     1
GR Napier                    1
VS Yeligati                  1
Mayank Dagar                 1
Gulbadin Naib                1
AA Noffke                    1
PWA Mulder                   1
Mukesh Kumar                 1
BR Sharath                   1
S Kaushik                    1
MS Bhandage                  1
MJ Suthar                    1
Arshad Khan (2)              1
Tanush Kotian                1
KA Maharaj                   1
KJ Abbott                    1
Kamran Khan                  1
DJ Muthuswami                1
H Das                        1
Shoaib Akhtar                1
PSP Handscomb                1
SB Jakati                    1
P Sahu                       1
A Choudhary                  1
A Nel                        1
BB Sran                      1
Basil Thampi                 1
Younis Khan                  1
LE Plunkett                  1
JPR Scantlebury-Searles      1
P Chopra                     1
P Ray Barman                 1
AN Ahmed                     1
SS Cottrell                  1
JL Pattinson                 1
S Tyagi                      1
C Nanda                      1
C Madan                      1
AS Joseph                    1
SE Bond                      1
RS Gavaskar                  1
AG Murtaza                   1
IC Pandey                    1
Jaskaran Singh               1
KP Appanna                   1
VS Malik                     1
KAJ Roach                    1
TM Srivastava                1
SMSM Senanayake              1
Mohammad Ashraful            1
DJ Malan                     1
UA Birla                     1
X Thalaivan Sargunam         1
M Ntini                      1
GD McGrath                   1
SJ Srivastava                1
S Ladda                      1
SS Shaikh                    1
GHS Garton                   1
DR Martyn                    1
DP Nannes                    1
D Kalyankrishna              1
DNT Zoysa                    1
A Tomar                      1
R Sanjay Yadav               1
Arjun Tendulkar              1
Liton Das                    1
R Ninan                      1
ND Doshi                     1
Y Gnaneswara Rao             1
BA Bhatt                     1
DE Bollinger                 1
B Sumanth                    1
OC McCoy                     1
V Pratap Singh               1
RR Bhatkal                   1
CJ McKay                     1
Sunny Gupta                  1
Mukesh Choudhary             1
XC Bartlett                  1
Naveen-ul-Haq                1
Vivrant Sharma               1
P Dubey                      1
JE Root                      1
KM Asif                      1
S Randiv                     1

In [ ]:
train_df['player_out'].fillna("not out",inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\2841821842.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['player_out'].fillna("not out",inplace=True)

In [ ]:
train_df['player_out'].value_counts()

player_out
not out                    264382
RG Sharma                     237
V Kohli                       219
S Dhawan                      193
KD Karthik                    184
RV Uthappa                    180
SK Raina                      171
AM Rahane                     165
DA Warner                     164
AT Rayudu                     155
SV Samson                     153
MS Dhoni                      142
F du Plessis                  136
G Gambhir                     136
MK Pandey                     135
AB de Villiers                130
CH Gayle                      126
SR Watson                     126
PA Patel                      126
SA Yadav                      124
KA Pollard                    121
WP Saha                       121
MA Agarwal                    120
GJ Maxwell                    118
RA Jadeja                     117
KL Rahul                      115
Yuvraj Singh                  111
SS Iyer                       110
YK Pathan                     110
Q de Kock                     109
RR Pant                       104
JC Buttler                    104
BB McCullum                   104
Ishan Kishan                  103
N Rana                        103
M Vijay                       101
SP Narine                     101
V Sehwag                       99
HH Pandya                      98
Shubman Gill                   98
AD Russell                     95
RA Tripathi                    88
DA Miller                      87
AR Patel                       87
DJ Hooda                       85
JH Kallis                      85
AJ Finch                       84
DR Smith                       84
Mandeep Singh                  82
KH Pandya                      81
PP Shaw                        79
R Dravid                       77
AC Gilchrist                   76
NV Ojha                        75
MP Stoinis                     72
SPD Smith                      72
KK Nair                        71
D Padikkal                     71
SR Tendulkar                   69
DJ Bravo                       69
N Pooran                       69
Abhishek Sharma                67
KC Sangakkara                  65
YBK Jaiswal                    64
DPMD Jayawardene               64
R Ashwin                       64
SE Marsh                       63
EJG Morgan                     62
RD Gaikwad                     62
R Parag                        61
S Dube                         61
KS Williamson                  60
MK Tiwary                      59
PP Chawla                      56
Harbhajan Singh                55
KM Jadhav                      54
MM Ali                         53
SC Ganguly                     53
IK Pathan                      53
SS Tiwary                      52
P Simran Singh                 51
SO Hetmyer                     51
JP Duminy                      51
MEK Hussey                     51
M Vohra                        49
DJ Hussey                      49
VR Iyer                        49
R Tewatia                      48
JM Bairstow                    48
V Shankar                      47
S Badrinath                    47
MR Marsh                       47
STR Binny                      46
AK Markram                     46
Y Venugopal Rao                44
TM Dilshan                     43
Rashid Khan                    42
BJ Hodge                       42
Shakib Al Hasan                41
LS Livingstone                 40
SM Curran                      40
JA Morkel                      40
LRPL Taylor                    40
Tilak Varma                    40
CA Lynn                        39
JM Sharma                      39
Abdul Samad                    39
B Kumar                        38
AM Nayar                       38
MS Bisla                       38
P Kumar                        38
BA Stokes                      38
H Klaasen                      37
RM Patidar                     36
CL White                       36
B Sai Sudharsan                36
RK Singh                       36
A Badoni                       36
MC Henriques                   36
M Shahrukh Khan                34
Washington Sundar              33
TM Head                        33
HH Gibbs                       32
A Mishra                       32
TL Suman                       32
PD Salt                        31
DT Christian                   31
AD Mathews                     31
ML Hayden                      31
PJ Cummins                     30
R Bhatia                       30
MK Lomror                      29
Shahbaz Ahmed                  29
HV Patel                       29
KP Pietersen                   28
R Vinay Kumar                  28
SN Thakur                      28
ST Jayasuriya                  28
CH Morris                      28
JD Ryder                       28
A Symonds                      27
LR Shukla                      27
N Wadhera                      27
GJ Bailey                      27
LMP Simmons                    27
JP Faulkner                    26
P Negi                         26
KV Sharma                      26
Abishek Porel                  26
GC Smith                       26
TH David                       26
SN Khan                        26
SW Billings                    26
DP Conway                      25
Gurkeerat Singh                24
Dhruv Jurel                    24
E Lewis                        24
AP Tare                        24
M Manhas                       23
DW Steyn                       22
NLTC Perera                    22
PC Valthaty                    22
CJ Anderson                    22
JO Holder                      21
UT Yadav                       21
AL Menaria                     21
UBT Chand                      20
S Sohal                        20
SA Asnodkar                    20
R Powell                       20
GH Vihari                      20
SP Goswami                     20
RR Rossouw                     20
J Botha                        20
SK Warne                       20
VVS Laxman                     19
JC Archer                      19
CA Pujara                      19
JJ Roy                         19
DB Ravi Teja                   19
A Manohar                      19
Azhar Mahmood                  19
Shashank Singh                 19
RS Bopara                      18
Priyansh Arya                  18
PK Garg                        18
MM Sharma                      18
M Kaif                         18
K Gowtham                      18
K Rabada                       18
Mohammad Nabi                  17
R Sathish                      17
WG Jacks                       17
Nithish Kumar Reddy            17
C Green                        17
T Stubbs                       17
Rahmanullah Gurbaz             17
R Ravindra                     17
JR Hopes                       16
A Raghuvanshi                  16
Lalit Yadav                    16
D Brevis                       16
Anuj Rawat                     16
RD Chahar                      16
C de Grandhomme                16
MD Mishra                      16
SE Rutherford                  16
SL Malinga                     16
JD Unadkat                     16
K Goel                         15
J Fraser-McGurk                15
PWH de Silva                   15
RP Singh                       15
A Ashish Reddy                 15
B Chipli                       15
Kuldeep Yadav                  15
DJG Sammy                      15
OA Shah                        15
Y Nagar                        14
RN ten Doeschate               14
Ashutosh Sharma                14
MS Wade                        14
Z Khan                         14
S Nadeem                       14
Naman Dhir                     14
DB Das                         14
MV Boucher                     14
S Gopal                        14
R Sharma                       14
Mohammed Shami                 14
PBB Rajapaksa                  13
TG Southee                     13
MJ McClenaghan                 13
RD Rickelton                   13
CR Brathwaite                  13
KR Mayers                      13
DJ Mitchell                    13
MN Samuels                     13
MG Johnson                     13
AA Jhunjhunwala                13
HM Amla                        13
CA Ingram                      12
RJ Harris                      12
PP Ojha                        12
Harpreet Brar                  12
MJ Lumb                        12
MJ Guptill                     12
C Munro                        12
RE van der Merwe               11
JEC Franklin                   11
M Morkel                       11
R Dhawan                       11
NM Coulter-Nile                11
MA Starc                       11
LA Pomersbach                  11
P Dogra                        11
BCJ Cutting                    11
M Jansen                       11
Ramandeep Singh                11
DH Yagnik                      10
Atharva Taide                  10
SM Katich                      10
SS Prabhudessai                10
B Lee                          10
Ravi Bishnoi                   10
N Saini                        10
PA Reddy                       10
AB Agarkar                     10
MF Maharoof                    10
MS Gony                        10
WD Parnell                     10
AB Dinda                       10
FY Fazal                       10
AD Nath                        10
CJ Jordan                      10
CM Gautam                      10
Mohammed Siraj                 10
RT Ponting                      9
JP Inglis                       9
Aniket Verma                    9
AD Mascarenhas                  9
SP Fleming                      9
DR Sams                         9
N Jagadeesan                    9
Aman Hakim Khan                 9
HC Brook                        9
Anmolpreet Singh                9
TA Boult                        9
M Ashwin                        9
AS Raut                         9
Shivam Mavi                     9
AJ Tye                          9
Sachin Baby                     9
JDS Neesham                     9
DS Kulkarni                     9
KK Cooper                       9
W Jaffer                        8
Noor Ahmad                      8
Bipul Sharma                    8
JDP Oram                        8
WPUJC Vaas                      8
R McLaren                       8
Shahid Afridi                   8
Azmatullah Omarzai              8
DL Chahar                       8
L Balaji                        8
S Anirudha                      8
DL Vettori                      8
S Vidyut                        8
MJ Santner                      8
PR Shah                         8
YV Takawale                     8
SD Hope                         8
SM Pollock                      8
PJ Sangwan                      8
YS Chahal                       7
Sikandar Raza                   7
Mohammad Hafeez                 7
R Shepherd                      7
Ankit Sharma                    7
BJ Rohrer                       7
MC Juneja                       7
Harpreet Singh                  7
AC Blizzard                     7
JJ Bumrah                       7
M Kartik                        7
RJ Quiney                       7
KS Bharat                       7
SB Bangar                       7
A Nehra                         7
DJM Short                       7
SK Trivedi                      7
A Mhatre                        7
SB Styris                       7
DJ Jacobs                       7
Salman Butt                     7
GD Phillips                     7
Misbah-ul-Haq                   7
V Suryavanshi                   7
SD Chitnis                      7
V Nigam                         7
Sameer Rizvi                    7
UT Khawaja                      6
C Sakariya                      6
CJ Ferguson                     6
Vishnu Vinod                    6
SP Jackson                      6
MW Short                        6
MM Patel                        6
Harshit Rana                    6
MJ Clarke                       6
SB Dubey                        6
B Akhil                         6
WA Mota                         6
Sandeep Sharma                  6
A Nortje                        6
Arshdeep Singh                  6
M Muralitharan                  6
G Coetzee                       6
AD Hales                        6
CR Woakes                       6
I Sharma                        6
RE Levi                         6
A Chopra                        6
Arshad Khan                     5
KB Arun Karthik                 5
AB McDonald                     5
D Wiese                         5
A Zampa                         5
Kamran Akmal                    5
VR Aaron                        5
Rasikh Salam                    5
RV Gomez                        5
IR Jaggi                        5
AJ Turner                       5
L Ronchi                        5
AS Yadav                        5
RV Patel                        5
KK Ahmed                        5
BB Samantray                    5
AA Bilakhia                     5
S Badree                        5
KMA Paul                        5
Swapnil Singh                   5
AS Rajpoot                      5
TK Curran                       5
AUK Pathan                      5
M Rawat                         5
LJ Wright                       5
SK Rasheed                      5
R Rampaul                       5
AG Paunikar                     5
A Mithun                        5
TR Birt                         5
PD Collingwood                  5
S Rana                          4
A Singh                         4
J Suchith                       4
RK Bhui                         4
VG Arora                        4
S Sreesanth                     4
RR Sarwan                       4
Sunny Singh                     4
Harmeet Singh                   4
Anirudh Singh                   4
NS Naik                         4
Yudhvir Singh                   4
AP Majumdar                     4
DJ Harris                       4
PHKD Mendis                     4
AC Voges                        4
M Klinger                       4
LA Carseldine                   4
S Aravind                       4
TS Mills                        4
Anureet Singh                   4
K Kartikeya                     4
D Pretorius                     4
Imran Tahir                     4
AS Roy                          4
NK Patel                        4
R Sai Kishore                   4
KA Jamieson                     4
JR Philippe                     4
Joginder Sharma                 4
CV Varun                        4
Kartik Tyagi                    4
PVD Chameera                    4
AF Milne                        4
S Kaul                          4
J Yadav                         4
KL Nagarkoti                    4
Navdeep Saini                   4
NT Ellis                        4
Shoaib Malik                    4
Yashpal Singh                   4
Mujeeb Ur Rahman                3
Akash Deep                      3
M Prasidh Krishna               3
RR Powar                        3
M Markande                      3
A Kumble                        3
R Bishnoi                       3
I Udana                         3
CK Kapugedera                   3
Avesh Khan                      3
DJ Thornely                     3
S Chanderpaul                   3
TL Seifert                      3
Umar Gul                        3
J Arunkumar                     3
PN Mankad                       3
Kumar Kushagra                  3
Saurav Chauhan                  3
T Taibu                         3
SA Abbott                       3
S Narwal                        3
NJ Maddinson                    3
HR Shokeen                      3
B Indrajith                     3
Suryansh Shedge                 3
GB Hogg                         3
Urvil Patel                     3
T Kohler-Cadmore                3
SW Tait                         3
YV Dhull                        3
D Ferreira                      3
RJ Peterson                     3
T Kohli                         3
BMAJ Mendis                     3
BR Dunk                         3
Mohsin Khan                     3
KW Richardson                   3
LH Ferguson                     3
KC Cariappa                     3
MN van Wyk                      3
KS Sharma                       3
Yash Dayal                      3
M Theekshana                    3
Sohail Tanvir                   3
OF Smith                        3
Simarjeet Singh                 3
JA Richardson                   3
AC Thomas                       2
T Henderson                     2
A Flintoff                      2
AN Ghosh                        2
ER Dwivedi                      2
F Behardien                     2
Pankaj Singh                    2
BAW Mendis                      2
DJ Willey                       2
Umran Malik                     2
VH Zol                          2
S Sriram                        2
SB Wagh                         2
Parvez Rasool                   2
TD Paine                        2
AU Rashid                       2
MA Khote                        2
Iqbal Abdulla                   2
JM Kemp                         2
PV Tambe                        2
T Thushara                      2
J Theron                        2
AB Barath                       2
C Bosch                         2
R Minz                          2
J Syed Mohammad                 2
P Awana                         2
B Laughlin                      2
DS Lehmann                      2
AP Dole                         2
CK Langeveldt                   2
MG Bracewell                    2
Vijaykumar Vyshak               2
SB Joshi                        2
JG Bethell                      2
MDKJ Perera                     2
A Mukund                        2
JJ van der Wath                 2
IS Sodhi                        2
Shoaib Ahmed                    2
Mustafizur Rahman               2
AA Chavan                       2
FA Allen                        2
D Salunkhe                      2
VRV Singh                       2
Ankit Soni                      2
MA Wood                         2
HE van der Dussen               2
DR Shorey                       2
GC Viljoen                      2
LPC Silva                       2
TU Deshpande                    2
RA Bawa                         2
T Banton                        2
AT Carey                        2
Mohammad Asif                   2
Virat Singh                     2
AA Kulkarni                     2
VY Mahesh                       2
DT Patil                        2
Sanvir Singh                    2
Sumit Kumar                     2
DG Nalkande                     2
MD Shanaka                      2
A Kamboj                        2
MS Bhandage                     1
Vivrant Sharma                  1
Arshad Khan (2)                 1
KA Maharaj                      1
Tanush Kotian                   1
BR Sharath                      1
MP Breetzke                     1
Sediqullah Atal                 1
M Tiwari                        1
MJ Owen                         1
JL Denly                        1
M Ntini                         1
GD McGrath                      1
JPR Scantlebury-Searles         1
Younis Khan                     1
SS Cottrell                     1
JL Pattinson                    1
D Kalyankrishna                 1
DNT Zoysa                       1
TM Srivastava                   1
GHS Garton                      1
B Sumanth                       1
SD Lad                          1
S Lamichhane                    1
P Ray Barman                    1
BB Sran                         1
A Nel                           1
VS Yeligati                     1
H Das                           1
Shoaib Akhtar                   1
DE Bollinger                    1
BA Bhatt                        1
Y Gnaneswara Rao                1
ND Doshi                        1
P Chopra                        1
Basil Thampi                    1
LE Plunkett                     1
A Choudhary                     1
DJ Malan                        1

In [ ]:
train_df.iloc[:,20:].head()

,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

In [ ]:
train_df['fielders'].isnull().sum()

np.int64(268192)

we are not going to fill the missing value with some other values as the filling value with result a broken web page so we are creating a new dataframe so that is clean and good  and we can check the best caches or golden hand .

In [ ]:
train_df.iloc[:,21:].head()

,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
0,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
1,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
2,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
3,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0
4,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0

In [ ]:
# Only fill NaN if it's NOT a dismissal that requires a fielder
# This preserves the integrity of your 'Caught' and 'Run Out' stats
# train_df['fielders'] = train_df['fielders'].fillna('Not Applicable')

In [ ]:
train_df['runs_target'].nunique()

175

we are going to drop the runs_target as we have alrady created a target_score column and chased score column so we dont need this column any more we can find the min and max target score from there and min and max chased score too

In [ ]:
train_df['target_score'].min()

np.int64(57)

In [ ]:
train_df[train_df['target_score']==57].head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
57068,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.1,nv ojha,1,1,1,ac thomas,1,0,1,1,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,1,1,0,NaN,1,1,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57069,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.2,da warner,2,0,1,ac thomas,1,1,1,0,False,legbyes,nv ojha,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,2,0,NaN,0,1,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57070,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.3,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,3,0,NaN,1,2,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57071,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.4,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,4,0,NaN,1,3,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57072,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.5,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,5,0,NaN,1,4,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0

In [ ]:
train_df.iloc[:,22:].sample(5)

,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
184501,NaN,NaN,NaN,NaN,NaN,NaN,False,R Ashwin,Delhi Capitals,46 runs,Rajasthan Royals,field,Sharjah Cricket Stadium,Unknown,9,10,2020,2020/21,male,club,NaN,NaN,NaN,6,20,23,Unknown,Unknown,43,27,2,RR Pant,17,14,0,"('RR Pant', 'SS Iyer')",NaN,False,185,138.0
239704,NaN,NaN,NaN,NaN,NaN,NaN,False,PN Mankad,Lucknow Super Giants,7 wickets,Sunrisers Hyderabad,bat,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,13,5,2023,2023,male,club,NaN,NaN,NaN,6,20,58,Unknown,Unknown,4,3,0,NaN,4,3,0,"('Abhishek Sharma', 'Anmolpreet Singh')",NaN,False,183,185.0
136387,NaN,NaN,NaN,NaN,NaN,NaN,False,BCJ Cutting,Sunrisers Hyderabad,8 runs,Sunrisers Hyderabad,bat,M Chinnaswamy Stadium,Bangalore,29,5,2016,2016,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,61,38,0,NaN,32,15,0,"('DA Warner', 'S Dhawan')",NaN,False,209,200.0
63854,V Sehwag,NaN,NaN,NaN,NaN,NaN,False,KP Pietersen,Delhi Daredevils,5 wickets,Deccan Chargers,bat,Feroz Shah Kotla,Delhi,19,4,2012,2012,male,club,NaN,NaN,NaN,6,20,23,Unknown,Unknown,113,82,4,NaN,4,5,1,"('DT Christian', 'JP Duminy')",B Chipli,True,158,162.0
65704,NaN,190.0,NaN,NaN,NaN,NaN,False,AB de Villiers,Royal Challengers Bangalore,46 runs,Rajasthan Royals,field,Sawai Mansingh Stadium,Jaipur,23,4,2012,2012,male,club,NaN,NaN,NaN,6,20,30,Unknown,Unknown,99,86,4,NaN,8,5,0,"('BJ Hodge', 'STR Binny')",NaN,False,190,143.0

In [ ]:
train_df['review_batter'].unique()

array([nan, 'E Lewis', 'MS Dhoni', 'SS Iyer', 'AB de Villiers', 'N Rana',
       'RK Singh', 'RA Tripathi', 'S Dhawan', 'KD Karthik', 'PJ Sangwan',
       'WP Saha', 'KS Williamson', 'AJ Finch', 'MP Stoinis', 'AR Patel',
       'Q de Kock', 'SA Yadav', 'KH Pandya', 'JJ Roy', 'RV Uthappa',
       'Shivam Mavi', 'DJ Hooda', 'SW Billings', 'V Shankar', 'HH Pandya',
       'KL Rahul', 'AM Rahane', 'RR Pant', 'AT Rayudu', 'BA Stokes',
       'G Gambhir', 'YK Pathan', 'MJ McClenaghan', 'AJ Tye', 'SR Watson',
       'M Vohra', 'RG Sharma', 'GJ Maxwell', 'DJM Short', 'CA Lynn',
       'JC Buttler', 'Sandeep Sharma', 'AD Nath', 'Ishan Kishan',
       'Kuldeep Yadav', 'CH Gayle', 'SN Khan', 'V Kohli', 'SV Samson',
       'H Klaasen', 'SP Goswami', 'R Ashwin', 'F du Plessis', 'SK Raina',
       'Navdeep Saini', 'PA Patel', 'DA Warner', 'JM Bairstow',
       'BCJ Cutting', 'SPD Smith', 'DA Miller', 'JJ Bumrah', 'NS Naik',
       'UT Yadav', 'SM Curran', 'CA Ingram', 'R Tewatia', 'CH Morris',
       'Mohammed Siraj', 'AD Russell', 'KM Jadhav', 'K Gowtham',
       'KMA Paul', 'MM Ali', 'LS Livingstone', 'P Simran Singh',
       'MJ Guptill', 'Gurkeerat Singh', 'C Munro', 'A Mishra', 'PP Shaw',
       'SE Rutherford', 'SS Tiwary', 'MK Pandey', 'KA Pollard', 'S Gopal',
       'N Pooran', 'RA Jadeja', 'SO Hetmyer', 'Mujeeb Ur Rahman',
       'R Parag', 'EJG Morgan', 'JC Archer', 'PJ Cummins', 'LH Ferguson',
       'RD Gaikwad', 'JO Holder', 'DT Christian', 'Rashid Khan', 'S Dube',
       'Lalit Yadav', 'D Padikkal', 'HV Patel', 'YS Chahal',
       'Abhishek Sharma', 'KA Jamieson', 'YBK Jaiswal', 'DJ Malan',
       'MA Agarwal', 'Shubman Gill', 'VR Iyer', 'SP Narine',
       'M Shahrukh Khan', 'Abdul Samad', 'Anuj Rawat', 'Shahbaz Ahmed',
       'A Badoni', 'D Pretorius', 'Harpreet Brar', 'TH David', 'MS Wade',
       'SN Thakur', 'R Powell', 'CJ Jordan', 'RD Chahar',
       'B Sai Sudharsan', 'PVD Chameera', 'JM Sharma', 'KR Sen',
       'DR Sams', 'PWH de Silva', 'SS Prabhudessai', 'Shashank Singh',
       'AS Roy', 'Umran Malik', 'Avesh Khan', 'MR Marsh',
       'Simarjeet Singh', 'HR Shokeen', 'DP Conway', 'Tilak Varma',
       'RM Patidar', 'RR Rossouw', 'N Wadhera', 'Rahmanullah Gurbaz',
       'KV Sharma', 'Anmolpreet Singh', 'Washington Sundar', 'R Shepherd',
       'PBB Rajapaksa', 'HC Brook', 'MK Lomror', 'YV Dhull',
       'Atharva Taide', 'D Wiese', 'N Jagadeesan', 'Aman Hakim Khan',
       'Dhruv Jurel', 'KR Mayers', 'AK Markram', 'PD Salt', 'JE Root',
       'C Sakariya', 'RK Bhui', 'Naman Dhir', 'Sumit Kumar', 'T Stubbs',
       'R Ravindra', 'Ashutosh Sharma', 'Harpreet Singh', 'R Sai Kishore',
       'B Kumar', 'WG Jacks', 'Rasikh Salam', 'AA Kulkarni', 'TM Head',
       'DJ Mitchell', 'Ravi Bishnoi', 'D Ferreira', 'Abishek Porel',
       'Arshad Khan', 'TA Boult', 'JD Unadkat', 'MJ Santner', 'MM Sharma',
       'Nithish Kumar Reddy', 'M Theekshana', 'Suryansh Shedge',
       'Arshdeep Singh', 'Aniket Verma', 'RD Rickelton', 'SB Dubey',
       'KK Nair', 'MS Bhandage', 'M Jansen', 'Priyansh Arya',
       'Prince Yadav', 'V Suryavanshi', 'Harshit Rana', 'KS Rathore',
       'JP Inglis', 'Musheer Khan'], dtype=object)

checking the number of times a player have asked for a review and is succes both into a new df

here we dont need to drop the duplicate rows as it is bawl to ball data so we dont have two time review in two balls

# batter_review_df

In [ ]:
batter_review_df = train_df.dropna(subset=['review_batter'])

In [ ]:
batter_review_df['review_batter'].value_counts()

review_batter
KD Karthik             22
RG Sharma              20
SA Yadav               18
N Rana                 18
JM Bairstow            14
JC Buttler             14
AM Rahane              13
WP Saha                13
RR Pant                13
RA Jadeja              13
KA Pollard             13
JM Sharma              12
R Tewatia              12
KL Rahul               11
SS Iyer                11
DA Warner              11
AR Patel               11
Q de Kock              11
SO Hetmyer             11
N Pooran               11
Shashank Singh         11
A Badoni               11
Tilak Varma            10
DA Miller              10
MS Dhoni               10
DJ Hooda               10
SV Samson               9
RA Tripathi             9
MP Stoinis              9
HH Pandya               9
P Simran Singh          9
D Padikkal              9
YBK Jaiswal             8
R Parag                 8
KH Pandya               8
GJ Maxwell              8
Shubman Gill            8
LS Livingstone          8
S Dhawan                8
Ishan Kishan            8
F du Plessis            8
V Kohli                 8
M Shahrukh Khan         7
B Sai Sudharsan         7
RV Uthappa              7
R Powell                7
WG Jacks                6
Rahmanullah Gurbaz      6
MK Lomror               6
KS Williamson           6
Abhishek Sharma         6
Anuj Rawat              6
MA Agarwal              6
TH David                6
Rashid Khan             6
PP Shaw                 6
S Dube                  6
Dhruv Jurel             6
AT Rayudu               6
CH Gayle                6
SM Curran               6
SK Raina                6
MR Marsh                5
VR Iyer                 5
Shahbaz Ahmed           5
RD Gaikwad              5
V Shankar               5
E Lewis                 5
DP Conway               5
AD Russell              4
Mohammed Siraj          4
Kuldeep Yadav           4
SW Billings             4
SPD Smith               4
AJ Finch                4
PJ Cummins              4
SN Thakur               4
SP Narine               4
MK Pandey               4
Abdul Samad             4
SN Khan                 4
UT Yadav                4
KM Jadhav               4
N Wadhera               3
MS Wade                 3
HV Patel                3
Ashutosh Sharma         3
HC Brook                3
SE Rutherford           3
DR Sams                 3
RR Rossouw              3
KK Nair                 3
JP Inglis               3
RM Patidar              3
RK Singh                3
AK Markram              3
T Stubbs                3
Naman Dhir              3
R Ashwin                3
H Klaasen               3
SR Watson               3
JJ Roy                  3
Shivam Mavi             2
YK Pathan               2
AB de Villiers          2
MM Ali                  2
Aniket Verma            2
DJ Mitchell             2
MJ Santner              2
JD Unadkat              2
D Ferreira              2
Abishek Porel           2
Harshit Rana            2
Nithish Kumar Reddy     2
Ravi Bishnoi            2
Anmolpreet Singh        2
R Shepherd              2
KV Sharma               2
B Kumar                 2
JE Root                 2
C Sakariya              2
RK Bhui                 2
JC Archer               2
CA Lynn                 2
NS Naik                 2
CA Ingram               2
SS Prabhudessai         2
Harpreet Brar           2
RD Chahar               2
D Pretorius             2
R Ravindra              2
JO Holder               2
EJG Morgan              2
AS Roy                  2
PJ Sangwan              1
M Vohra                 1
DJM Short               1
Sandeep Sharma          1
KMA Paul                1
K Gowtham               1
CH Morris               1
BCJ Cutting             1
JJ Bumrah               1
SP Goswami              1
PA Patel                1
Navdeep Saini           1
AD Nath                 1
MJ McClenaghan          1
G Gambhir               1
BA Stokes               1
AJ Tye                  1
Avesh Khan              1
Umran Malik             1
PWH de Silva            1
Gurkeerat Singh         1
MJ Guptill              1
A Mishra                1
C Munro                 1
PVD Chameera            1
CJ Jordan               1
KR Sen                  1
DJ Malan                1
Mujeeb Ur Rahman        1
S Gopal                 1
SS Tiwary               1
LH Ferguson             1
DT Christian            1
Lalit Yadav             1
YS Chahal               1
KA Jamieson             1
Simarjeet Singh         1
Sumit Kumar             1
KR Mayers               1
D Wiese                 1
Harpreet Singh          1
N Jagadeesan            1
PD Salt                 1
Atharva Taide           1
PBB Rajapaksa           1
Washington Sundar       1
YV Dhull                1
HR Shokeen              1
Aman Hakim Khan         1
TM Head                 1
R Sai Kishore           1
Rasikh Salam            1
MM Sharma               1
TA Boult                1
Arshad Khan             1
AA Kulkarni             1
Arshdeep Singh          1
RD Rickelton            1
Suryansh Shedge         1
M Theekshana            1
MS Bhandage             1
SB Dubey                1
M Jansen                1
Priyansh Arya           1
V Suryavanshi           1
Prince Yadav            1
KS Rathore              1
Musheer Khan            1
Name: count, dtype: int64

In [ ]:
batter_review_df=batter_review_df[batter_review_df['review_batter'].isin(batter_review_df['review_batter']\
    .value_counts()[batter_review_df['review_batter'].value_counts() >= 3].index)]

In [ ]:
batter_review_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
150472,1136561,2018-04-07,1,Mumbai Indians,Chennai Super Kings,2,2.1,e lewis,2,0,1,dl chahar,1,0,0,0,False,no_extra_runs,rg sharma,1,lbw,E Lewis,NaN,NaN,E Lewis,Mumbai Indians,struck down,CB Gaffaney,True,DJ Bravo,Chennai Super Kings,1 wickets,Chennai Super Kings,field,Wankhede Stadium,Mumbai,7,4,2018,2018,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,7,13,1,NaN,0,2,1,"('E Lewis', 'RG Sharma')",Ishan Kishan,True,166,169.0
150633,1136561,2018-04-07,2,Chennai Super Kings,Mumbai Indians,8,8.3,ms dhoni,5,0,1,m markande,1,0,0,0,False,no_extra_runs,km jadhav,4,lbw,MS Dhoni,NaN,166.0,MS Dhoni,Mumbai Indians,upheld,CB Gaffaney,False,DJ Bravo,Chennai Super Kings,1 wickets,Chennai Super Kings,field,Wankhede Stadium,Mumbai,7,4,2018,2018,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,51,51,4,NaN,5,5,1,"('KM Jadhav', 'MS Dhoni')",RA Jadeja,True,166,169.0
150735,1136562,2018-04-08,1,Delhi Daredevils,Kings XI Punjab,4,4.6,ss iyer,3,0,0,mujeeb ur rahman,0,1,1,1,False,wides,g gambhir,2,not out,not out,NaN,NaN,SS Iyer,Kings XI Punjab,struck down,RJ Tucker,True,KL Rahul,Kings XI Punjab,6 wickets,Kings XI Punjab,field,Punjab Cricket Association IS Bindra Stadium,Chandigarh,8,4,2018,2018,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,39,29,1,NaN,4,6,0,"('G Gambhir', 'SS Iyer')",NaN,False,167,167.0
151157,1136563,2018-04-08,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,14.3,n rana,4,0,1,washington sundar,1,0,0,0,False,no_extra_runs,kd karthik,5,lbw,N Rana,NaN,177.0,N Rana,Kolkata Knight Riders,struck down,C Shamshuddin,True,SP Narine,Kolkata Knight Riders,4 wickets,Kolkata Knight Riders,field,Eden Gardens,Kolkata,8,4,2018,2018,male,club,NaN,NaN,NaN,6,20,3,Unknown,Unknown,138,87,4,NaN,34,25,1,"('KD Karthik', 'N Rana')",RK Singh,True,177,177.0
151165,1136563,2018-04-08,2,Kolkata Knight Riders,Royal Challengers Bangalore,15,15.4,rk singh,6,0,1,cr woakes,1,0,0,0,False,no_extra_runs,kd karthik,5,caught,RK Singh,Q de Kock,177.0,RK Singh,Royal Challengers Bangalore,upheld,A Deshmukh,False,SP Narine,Kolkata Knight Riders,4 wickets,Kolkata Knight Riders,field,Eden Gardens,Kolkata,8,4,2018,2018,male,club,NaN,NaN,NaN,6,20,3,Unknown,Unknown,146,94,5,NaN,6,6,1,"('KD Karthik', 'RK Singh')",AD Russell,True,177,177.0

In [ ]:
batter_review_df['review_decision'].value_counts()

review_decision
struck down    502
upheld         238
Name: count, dtype: int64

In [ ]:
mapping_dict = {'struck down':'right_dec',
                "upheld":'wrong_dec'}
batter_review_df['review_decision'] = batter_review_df['review_decision'].map(mapping_dict)

In [ ]:
train_df.sample(4)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
251564,1426270,2024-04-17,2,Delhi Capitals,Gujarat Titans,3,3.6,abishek porel,3,4,1,sh johnson,1,0,4,4,False,no_extra_runs,sd hope,4,not out,not out,NaN,90.0,NaN,NaN,NaN,NaN,False,RR Pant,Delhi Capitals,6 wickets,Delhi Capitals,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,17,4,2024,2024,male,club,NaN,NaN,NaN,6,20,32,Unknown,Unknown,42,24,2,NaN,9,5,0,"('Abishek Porel', 'SD Hope')",NaN,False,90,92.0
181444,1216547,2020-09-28,2,Mumbai Indians,Royal Challengers Bangalore,7,7.4,ishan kishan,4,1,1,a zampa,1,0,1,1,False,no_extra_runs,hh pandya,5,not out,not out,NaN,202.0,NaN,NaN,NaN,NaN,False,AB de Villiers,Unknown,NaN,Mumbai Indians,field,Dubai International Cricket Stadium,Unknown,28,9,2020,2020/21,male,club,Royal Challengers Bangalore,tie,NaN,6,20,10,Unknown,Unknown,45,46,3,NaN,19,18,0,"('HH Pandya', 'Ishan Kishan')",NaN,False,202,201.0
50655,501237,2011-05-02,1,Mumbai Indians,Kings XI Punjab,4,4.2,sr tendulkar,2,1,1,bipul sharma,1,0,1,1,False,no_extra_runs,at rayudu,3,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,KA Pollard,Mumbai Indians,23 runs,Kings XI Punjab,field,Wankhede Stadium,Mumbai,2,5,2011,2011,male,club,NaN,NaN,NaN,6,20,40,Unknown,Unknown,20,26,1,NaN,6,10,0,"('AT Rayudu', 'SR Tendulkar')",NaN,False,160,136.0
90267,598055,2013-05-11,2,Mumbai Indians,Pune Warriors,10,10.5,rg sharma,4,1,1,parvez rasool,1,0,1,1,False,no_extra_runs,at rayudu,5,not out,not out,NaN,113.0,NaN,NaN,NaN,NaN,False,MG Johnson,Mumbai Indians,5 wickets,Pune Warriors,bat,Subrata Roy Sahara Stadium,Pune,11,5,2013,2013,male,club,NaN,NaN,NaN,6,20,58,Unknown,Unknown,55,65,3,NaN,16,19,0,"('AT Rayudu', 'RG Sharma')",NaN,False,113,116.0

In [ ]:
train_df[train_df['result_type']=='no result'].head(10)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
57068,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.1,nv ojha,1,1,1,ac thomas,1,0,1,1,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,1,1,0,NaN,1,1,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57069,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.2,da warner,2,0,1,ac thomas,1,1,1,0,False,legbyes,nv ojha,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,2,0,NaN,0,1,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57070,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.3,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,3,0,NaN,1,2,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57071,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.4,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,4,0,NaN,1,3,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57072,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.5,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,5,0,NaN,1,4,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57073,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,0.6,nv ojha,1,0,1,ac thomas,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,2,6,0,NaN,1,5,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57074,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,1,1.1,da warner,2,0,1,jp faulkner,1,1,1,0,False,legbyes,nv ojha,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,3,7,0,NaN,0,2,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57075,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,1,1.2,nv ojha,1,0,1,jp faulkner,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,3,8,0,NaN,1,6,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57076,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,1,1.3,nv ojha,1,0,1,jp faulkner,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,3,9,0,NaN,1,7,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0
57077,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,1,1.4,nv ojha,1,0,1,jp faulkner,1,0,0,0,False,no_extra_runs,da warner,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Unknown,Unknown,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,21,5,2011,2011,male,club,NaN,no result,NaN,6,20,68,Unknown,Unknown,3,10,0,NaN,1,8,0,"('DA Warner', 'NV Ojha')",NaN,False,57,0.0

In [ ]:
cancel_matches_due_to_rain=train_df[train_df['result_type']=='no result']['match_id'].unique()

In [ ]:
train_df['result_type'].value_counts()

result_type
tie          3896
no result     806
Name: count, dtype: int64

# 




































































































































































































































































































































































































core_card

creating sorecard to checek the lowest loweser and highest score in the match

In [ ]:
real_score_card=train_df[train_df['result_type']!='no result']

In [ ]:
real_score_card.sample(4)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
75930,548380,2012-05-25,1,Chennai Super Kings,Delhi Daredevils,5,5.4,m vijay,1,0,1,vr aaron,1,0,0,0,False,no_extra_runs,mek hussey,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,M Vijay,Chennai Super Kings,86 runs,Delhi Daredevils,field,"MA Chidambaram Stadium, Chepauk",Chennai,25,5,2012,2012,male,club,NaN,NaN,NaN,6,20,Unknown,Qualifier 2,Unknown,44,34,0,NaN,30,17,0,"('M Vijay', 'MEK Hussey')",NaN,False,223,136.0
224408,1304114,2022-05-20,2,Rajasthan Royals,Chennai Super Kings,3,3.3,ybk jaiswal,1,1,1,simarjeet singh,1,0,1,1,False,no_extra_runs,sv samson,3,not out,not out,NaN,151.0,NaN,NaN,NaN,NaN,False,R Ashwin,Rajasthan Royals,5 wickets,Chennai Super Kings,bat,"Brabourne Stadium, Mumbai",Mumbai,20,5,2022,2022,male,club,NaN,NaN,NaN,6,20,68,Unknown,Unknown,32,21,1,NaN,22,12,0,"('SV Samson', 'YBK Jaiswal')",NaN,False,151,151.0
267093,1473463,2025-04-12,2,Lucknow Super Giants,Gujarat Titans,11,11.6,a badoni,4,0,1,m prasidh krishna,1,0,0,0,False,no_extra_runs,n pooran,3,not out,not out,NaN,181.0,NaN,NaN,NaN,NaN,False,AK Markram,Lucknow Super Giants,6 wickets,Lucknow Super Giants,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,12,4,2025,2025,male,club,NaN,NaN,NaN,6,20,26,Unknown,Unknown,125,72,2,NaN,1,3,0,"('A Badoni', 'N Pooran')",NaN,False,181,186.0
81525,598018,2013-04-17,1,Sunrisers Hyderabad,Pune Warriors,10,10.5,a mishra,8,4,1,mr marsh,1,0,4,4,False,no_extra_runs,bb samantray,5,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,A Mishra,Sunrisers Hyderabad,11 runs,Pune Warriors,field,Maharashtra Cricket Association Stadium,Pune,17,4,2013,2013,male,club,NaN,NaN,NaN,6,20,22,Unknown,Unknown,48,65,6,A Mishra,4,1,0,"('A Mishra', 'BB Samantray')",NaN,False,120,108.0

In [ ]:
real_score_card['chased_score'].min()

np.float64(44.0)

In [ ]:
train_df[train_df['chased_score']==44].head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
101974,733993,2014-05-10,1,Delhi Daredevils,Sunrisers Hyderabad,0,0.1,q de kock,1,0,1,dw steyn,1,0,0,0,False,no_extra_runs,kp pietersen,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,DW Steyn,Sunrisers Hyderabad,8 wickets,Sunrisers Hyderabad,field,Feroz Shah Kotla,Delhi,10,5,2014,2014,male,club,NaN,NaN,D/L,6,20,32,Unknown,Unknown,0,1,0,NaN,0,1,0,"('KP Pietersen', 'Q de Kock')",NaN,False,144,44.0
101975,733993,2014-05-10,1,Delhi Daredevils,Sunrisers Hyderabad,0,0.2,q de kock,1,2,1,dw steyn,1,0,2,2,False,no_extra_runs,kp pietersen,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,DW Steyn,Sunrisers Hyderabad,8 wickets,Sunrisers Hyderabad,field,Feroz Shah Kotla,Delhi,10,5,2014,2014,male,club,NaN,NaN,D/L,6,20,32,Unknown,Unknown,2,2,0,NaN,2,2,0,"('KP Pietersen', 'Q de Kock')",NaN,False,144,44.0
101976,733993,2014-05-10,1,Delhi Daredevils,Sunrisers Hyderabad,0,0.3,q de kock,1,1,1,dw steyn,1,0,1,1,False,no_extra_runs,kp pietersen,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,DW Steyn,Sunrisers Hyderabad,8 wickets,Sunrisers Hyderabad,field,Feroz Shah Kotla,Delhi,10,5,2014,2014,male,club,NaN,NaN,D/L,6,20,32,Unknown,Unknown,3,3,0,NaN,3,3,0,"('KP Pietersen', 'Q de Kock')",NaN,False,144,44.0
101977,733993,2014-05-10,1,Delhi Daredevils,Sunrisers Hyderabad,0,0.4,kp pietersen,2,0,1,dw steyn,1,0,0,0,False,no_extra_runs,q de kock,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,DW Steyn,Sunrisers Hyderabad,8 wickets,Sunrisers Hyderabad,field,Feroz Shah Kotla,Delhi,10,5,2014,2014,male,club,NaN,NaN,D/L,6,20,32,Unknown,Unknown,3,4,0,NaN,0,1,0,"('KP Pietersen', 'Q de Kock')",NaN,False,144,44.0
101978,733993,2014-05-10,1,Delhi Daredevils,Sunrisers Hyderabad,0,0.5,kp pietersen,2,1,1,dw steyn,1,0,1,1,False,no_extra_runs,q de kock,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,DW Steyn,Sunrisers Hyderabad,8 wickets,Sunrisers Hyderabad,field,Feroz Shah Kotla,Delhi,10,5,2014,2014,male,club,NaN,NaN,D/L,6,20,32,Unknown,Unknown,4,5,0,NaN,1,2,0,"('KP Pietersen', 'Q de Kock')",NaN,False,144,44.0

In [ ]:
train_df['method'].value_counts()

method
D/L    3890
Name: count, dtype: int64

In [ ]:
train_df['method'].unique()

array([nan, 'D/L'], dtype=object)

In [ ]:
dl_method_matches=train_df[train_df['method']=='D/L	']['match_id'].unique()

so werre the dl formula is been used that is not usefull in the chased score and other o we are going to drop these column from score_card

In [ ]:
real_score_card=real_score_card[real_score_card['method']!= 'D/L']

In [ ]:
real_score_card.sample()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
87836,598044,2013-05-04,2,Sunrisers Hyderabad,Delhi Daredevils,1,1.2,s dhawan,2,4,1,ut yadav,1,0,4,4,False,no_extra_runs,pa patel,1,not out,not out,NaN,81.0,NaN,NaN,NaN,NaN,False,DJG Sammy,Sunrisers Hyderabad,6 wickets,Delhi Daredevils,bat,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,4,5,2013,2013,male,club,NaN,NaN,NaN,6,20,48,Unknown,Unknown,12,8,0,NaN,11,6,0,"('PA Patel', 'S Dhawan')",NaN,False,81,81.0

mnbmnb

In [ ]:
real_score_card['chased_score'].min()

np.float64(49.0)

In [ ]:
train_df.shape

(278205, 62)

In [ ]:
train_df.sample(4)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score
138241,1082597,2017-04-09,2,Mumbai Indians,Kolkata Knight Riders,14,14.2,ka pollard,6,4,1,cr woakes,1,0,4,4,False,no_extra_runs,n rana,3,not out,not out,NaN,179.0,NaN,NaN,NaN,NaN,False,N Rana,Mumbai Indians,4 wickets,Mumbai Indians,field,Wankhede Stadium,Mumbai,9,4,2017,2017,male,club,NaN,NaN,NaN,6,20,7,Unknown,Unknown,113,86,4,NaN,14,11,0,"('KA Pollard', 'N Rana')",NaN,False,179,180.0
141058,1082609,2017-04-17,2,Kings XI Punjab,Sunrisers Hyderabad,3,3.5,m vohra,2,1,1,s kaul,1,0,1,1,False,no_extra_runs,ejg morgan,4,not out,not out,NaN,160.0,NaN,NaN,NaN,NaN,False,B Kumar,Sunrisers Hyderabad,5 runs,Kings XI Punjab,field,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,17,4,2017,2017,male,club,NaN,NaN,NaN,6,20,19,Unknown,Unknown,21,23,2,NaN,8,7,0,"('EJG Morgan', 'M Vohra')",NaN,False,160,154.0
85234,598033,2013-04-27,2,Royal Challengers Bangalore,Mumbai Indians,12,12.6,ss tiwary,5,1,1,harbhajan singh,1,0,1,1,False,no_extra_runs,j syed mohammad,7,not out,not out,NaN,195.0,NaN,NaN,NaN,NaN,False,DR Smith,Mumbai Indians,58 runs,Mumbai Indians,bat,Wankhede Stadium,Mumbai,27,4,2013,2013,male,club,NaN,NaN,NaN,6,20,37,Unknown,Unknown,81,78,5,NaN,19,17,0,"('J Syed Mohammad', 'SS Tiwary')",NaN,False,195,136.0
142539,1082615,2017-04-22,2,Rising Pune Supergiant,Sunrisers Hyderabad,8,8.6,ra tripathi,2,4,1,rashid khan,1,0,4,4,False,no_extra_runs,spd smith,3,not out,not out,NaN,177.0,NaN,NaN,NaN,NaN,False,MS Dhoni,Rising Pune Supergiant,6 wickets,Rising Pune Supergiant,field,Maharashtra Cricket Association Stadium,Pune,22,4,2017,2017,male,club,NaN,NaN,NaN,6,20,24,Unknown,Unknown,68,54,1,NaN,54,33,0,"('RA Tripathi', 'SPD Smith')",NaN,False,177,179.0

In [ ]:
train_df['tie_match'] = np.where((train_df['win_outcome'].isna()),1, 0)
train_df['match_won_by']=np.where(train_df['match_won_by']=='Unknown',train_df['superover_winner'],train_df['match_won_by'])

In [ ]:
train_df['win_outcome'].value_counts()

win_outcome
6 wickets     30082
7 wickets     28540
5 wickets     24481
8 wickets     19424
4 wickets     15059
9 wickets     10979
3 wickets      7888
10 runs        4296
14 runs        4249
12 runs        3960
4 runs         3929
1 runs         3732
18 runs        3712
7 runs         3703
20 runs        3500
13 runs        3468
10 wickets     3418
15 runs        3225
2 runs         3220
23 runs        3216
6 runs         3113
37 runs        2991
5 runs         2948
9 runs         2750
2 wickets      2725
24 runs        2575
27 runs        2477
11 runs        2426
25 runs        2252
17 runs        2239
19 runs        2167
34 runs        2135
16 runs        2123
22 runs        2096
3 runs         1927
8 runs         1763
21 runs        1738
31 runs        1736
38 runs        1723
45 runs        1510
35 runs        1497
33 runs        1494
44 runs        1251
32 runs        1241
39 runs        1240
54 runs        1240
28 runs        1238
1 wickets      1236
29 runs        1235
46 runs        1232
48 runs        1227
41 runs        1222
55 runs        1215
36 runs        1011
50 runs         996
26 runs         989
57 runs         984
59 runs         975
82 runs         856
58 runs         751
42 runs         745
63 runs         737
30 runs         731
40 runs         730
67 runs         724
78 runs         709
97 runs         707
62 runs         705
60 runs         697
80 runs         688
86 runs         687
77 runs         508
56 runs         507
49 runs         506
43 runs         502
61 runs         500
47 runs         494
72 runs         493
65 runs         488
69 runs         478
85 runs         472
81 runs         464
98 runs         462
71 runs         455
92 runs         439
75 runs         432
130 runs        251
66 runs         250
51 runs         248
110 runs        247
64 runs         245
106 runs        244
118 runs        244
88 runs         243
83 runs         242
144 runs        242
87 runs         241
53 runs         241
91 runs         239
102 runs        234
74 runs         233
52 runs         233
111 runs        232
100 runs        226
140 runs        225
105 runs        223
93 runs         219
138 runs        212
146 runs        211
76 runs         204
112 runs        189
Name: count, dtype: int64

In [ ]:
#train_df.drop(columns=['method','result_type', 'runs_target'],inplace=True)

In [ ]:
train_df.sample(5
                )

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
149768,1082647,2017-05-16,2,Mumbai Indians,Rising Pune Supergiant,7,7.4,pa patel,2,1,1,washington sundar,1,0,1,1,False,no_extra_runs,ka pollard,5,not out,not out,NaN,163.0,NaN,NaN,NaN,NaN,False,Washington Sundar,Rising Pune Supergiant,20 runs,Mumbai Indians,field,Wankhede Stadium,Mumbai,16,5,2017,2017,male,club,NaN,NaN,NaN,6,20,Unknown,Qualifier 1,Unknown,51,46,3,NaN,36,20,0,"('KA Pollard', 'PA Patel')",NaN,False,163,142.0,0
99597,733973,2014-05-03,1,Kings XI Punjab,Mumbai Indians,12,12.2,gj bailey,5,1,1,cj anderson,1,0,1,1,False,no_extra_runs,wp saha,3,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,CJ Anderson,Mumbai Indians,5 wickets,Kings XI Punjab,bat,Wankhede Stadium,Mumbai,3,5,2014,2014,male,club,NaN,NaN,NaN,6,20,22,Unknown,Unknown,98,74,3,NaN,5,2,0,"('GJ Bailey', 'WP Saha')",NaN,False,169,170.0,0
196891,1254071,2021-04-21,1,Punjab Kings,Sunrisers Hyderabad,14,14.6,fa allen,8,1,1,s kaul,1,0,1,1,False,no_extra_runs,m shahrukh khan,7,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,JM Bairstow,Sunrisers Hyderabad,9 wickets,Punjab Kings,bat,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,21,4,2021,2021,male,club,NaN,NaN,NaN,6,20,14,Unknown,Unknown,94,90,6,NaN,3,6,0,"('FA Allen', 'M Shahrukh Khan')",NaN,False,121,121.0,0
63364,548327,2012-04-17,1,Pune Warriors,Royal Challengers Bangalore,10,10.2,rv uthappa,1,2,1,dl vettori,1,0,2,2,False,no_extra_runs,sc ganguly,3,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,CH Gayle,Royal Challengers Bangalore,6 wickets,Pune Warriors,bat,M Chinnaswamy Stadium,Bangalore,17,4,2012,2012,male,club,NaN,NaN,NaN,6,20,21,Unknown,Unknown,98,62,1,NaN,55,36,0,"('RV Uthappa', 'SC Ganguly')",NaN,False,183,186.0,0
200022,1254084,2021-05-01,1,Chennai Super Kings,Mumbai Indians,16,16.2,at rayudu,5,1,1,jj bumrah,1,0,1,1,False,no_extra_runs,ra jadeja,6,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,KA Pollard,Mumbai Indians,4 wickets,Mumbai Indians,field,"Arun Jaitley Stadium, Delhi",Delhi,1,5,2021,2021,male,club,NaN,NaN,NaN,6,20,27,Unknown,Unknown,155,98,4,NaN,30,14,0,"('AT Rayudu', 'RA Jadeja')",NaN,False,219,219.0,0

In [ ]:
train_df.groupby('batter')['runs_batter'].sum().sort_values(ascending=False).head(10)

batter
v kohli           8671
rg sharma         7048
s dhawan          6769
da warner         6567
sk raina          5536
ms dhoni          5439
kl rahul          5235
ab de villiers    5181
am rahane         5032
ch gayle          4997
Name: runs_batter, dtype: int64

In [ ]:
train_df.head(10)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
5,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.5,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
6,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.6,bb mccullum,2,0,1,p kumar,1,1,1,0,False,legbyes,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,6,0,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
7,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.1,bb mccullum,2,0,1,z khan,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,7,0,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
8,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.2,bb mccullum,2,4,1,z khan,1,0,4,4,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,7,8,0,NaN,4,7,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
9,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.3,bb mccullum,2,4,1,z khan,1,0,4,4,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,11,9,0,NaN,8,8,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0

batter_runs decide the run a perticular batsmen have made in a single match

In [ ]:
score_card=train_df.groupby(['match_id','batter'])['batter_runs'].max().sort_values(ascending=False).reset_index()

In [ ]:
score_card.head()

   match_id           batter  batter_runs
0    598027         ch gayle          175
1    335982      bb mccullum          158
2   1473464  abhishek sharma          141
3   1304112        q de kock          140
4    829795   ab de villiers          133

In [ ]:
score_card=score_card.sort_values(by='match_id',ascending=False)

In [ ]:
score_card.head()

       match_id          batter  batter_runs
7850    1485779       n wadhera           16
9750    1485779  shashank singh           11
1648    1485779         ss iyer           53
11650   1485779   priyansh arya            6
2382    1485779      mp stoinis           44

In [ ]:
balls_faced=train_df.groupby(['match_id','batter'])['balls_faced'].sum().reset_index().sort_values(by='match_id', ascending=False)

In [ ]:
score_card.merge(balls_faced,on=['match_id','batter']).sort_values(by='match_id', ascending=False).head()

    match_id           batter  batter_runs  balls_faced
1    1485779   shashank singh           11           10
10   1485779  sediqullah atal           22           16
6    1485779    harpreet brar            7            2
9    1485779     f du plessis           23           15
8    1485779         t stubbs           18           14

In [ ]:
train_df['tie_match'].value_counts()

tie_match
0    273503
1      4702
Name: count, dtype: int64

In [ ]:
train_df.sample(5)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
146279,1082632,2017-05-04,2,Delhi Daredevils,Gujarat Lions,13,13.2,sv samson,1,0,1,ra jadeja,1,0,0,0,False,no_extra_runs,rr pant,3,caught,SV Samson,JP Faulkner,209.0,NaN,NaN,NaN,NaN,False,RR Pant,Delhi Daredevils,7 wickets,Delhi Daredevils,field,Feroz Shah Kotla,Delhi,4,5,2017,2017,male,club,NaN,NaN,NaN,6,20,42,Unknown,Unknown,167,80,2,NaN,61,31,1,"('RR Pant', 'SV Samson')",SS Iyer,True,209,214.0,0
252129,1426273,2024-04-20,1,Sunrisers Hyderabad,Delhi Capitals,6,6.1,abhishek sharma,2,6,1,kuldeep yadav,1,0,6,6,False,no_extra_runs,tm head,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,TM Head,Sunrisers Hyderabad,67 runs,Delhi Capitals,field,"Arun Jaitley Stadium, Delhi",Delhi,20,4,2024,2024,male,club,NaN,NaN,NaN,6,20,35,Unknown,Unknown,131,37,0,NaN,46,11,0,"('Abhishek Sharma', 'TM Head')",NaN,False,267,199.0,0
37298,419147,2010-04-10,2,Deccan Chargers,Chennai Super Kings,16,16.2,a symonds,5,1,1,sb jakati,1,0,1,1,False,no_extra_runs,dr smith,6,not out,not out,NaN,139.0,NaN,NaN,NaN,NaN,False,RJ Harris,Deccan Chargers,6 wickets,Chennai Super Kings,bat,"Vidarbha Cricket Association Stadium, Jamtha",Nagpur,10,4,2010,2009/10,male,club,NaN,NaN,NaN,6,20,42,Unknown,Unknown,108,98,4,DR Smith,11,13,0,"('A Symonds', 'DR Smith')",NaN,False,139,139.0,0
189498,1216498,2020-10-24,2,Sunrisers Hyderabad,Kings XI Punjab,7,7.1,mk pandey,3,1,1,m ashwin,1,0,1,1,False,no_extra_runs,jm bairstow,2,not out,not out,NaN,127.0,NaN,NaN,NaN,NaN,False,CJ Jordan,Kings XI Punjab,12 runs,Sunrisers Hyderabad,field,Dubai International Cricket Stadium,Unknown,24,10,2020,2020/21,male,club,NaN,NaN,NaN,6,20,43,Unknown,Unknown,58,43,1,NaN,2,4,0,"('JM Bairstow', 'MK Pandey')",NaN,False,127,114.0,0
27451,419107,2010-03-13,1,Mumbai Indians,Rajasthan Royals,15,15.6,ss tiwary,4,1,1,yk pathan,1,0,1,1,False,no_extra_runs,at rayudu,5,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,YK Pathan,Mumbai Indians,4 runs,Mumbai Indians,bat,Brabourne Stadium,Mumbai,13,3,2010,2009/10,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,170,96,3,NaN,44,27,0,"('AT Rayudu', 'SS Tiwary')",NaN,False,213,208.0,0

# cleaning the train_df

In [ ]:
train_df.sample(4)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
111490,829727,2015-04-16,2,Rajasthan Royals,Sunrisers Hyderabad,9,9.1,sv samson,2,1,1,kv sharma,1,0,1,1,False,no_extra_runs,am rahane,1,not out,not out,NaN,128.0,NaN,NaN,NaN,NaN,False,AM Rahane,Rajasthan Royals,6 wickets,Rajasthan Royals,field,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Visakhapatnam,16,4,2015,2015,male,club,NaN,NaN,NaN,6,20,11,Unknown,Unknown,58,55,0,NaN,26,29,0,"('AM Rahane', 'SV Samson')",NaN,False,128,131.0,0
191024,1216536,2020-10-29,2,Chennai Super Kings,Kolkata Knight Riders,19,19.2,sm curran,5,2,1,kl nagarkoti,1,0,2,2,False,no_extra_runs,ra jadeja,6,not out,not out,NaN,173.0,NaN,NaN,NaN,NaN,False,RD Gaikwad,Chennai Super Kings,6 wickets,Chennai Super Kings,field,Dubai International Cricket Stadium,Unknown,29,10,2020,2020/21,male,club,NaN,NaN,NaN,6,20,49,Unknown,Unknown,165,116,4,NaN,12,13,0,"('RA Jadeja', 'SM Curran')",NaN,False,173,178.0,0
33307,419131,2010-03-29,2,Kolkata Knight Riders,Delhi Daredevils,2,2.2,sc ganguly,2,0,1,dp nannes,1,0,0,0,False,no_extra_runs,ch gayle,1,not out,not out,NaN,178.0,NaN,NaN,NaN,NaN,False,DA Warner,Delhi Daredevils,40 runs,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,29,3,2010,2009/10,male,club,NaN,NaN,NaN,6,20,26,Unknown,Unknown,15,14,0,NaN,1,7,0,"('CH Gayle', 'SC Ganguly')",NaN,False,178,137.0,0
144338,1082624,2017-04-29,2,Royal Challengers Bangalore,Rising Pune Supergiant,3,3.3,ab de villiers,3,1,1,jd unadkat,1,0,1,1,False,no_extra_runs,v kohli,2,not out,not out,NaN,158.0,NaN,NaN,NaN,NaN,False,LH Ferguson,Rising Pune Supergiant,61 runs,Royal Challengers Bangalore,field,Maharashtra Cricket Association Stadium,Pune,29,4,2017,2017,male,club,NaN,NaN,NaN,6,20,34,Unknown,Unknown,26,21,1,NaN,2,4,0,"('AB de Villiers', 'V Kohli')",NaN,False,158,96.0,0

# most runs in ipl season

In [ ]:
train_df.groupby(['season','batter'])['runs_batter'].sum().reset_index().sort_values(by='runs_batter',ascending=False).head()

     season           batter  runs_batter
1016   2016          v kohli          973
1876   2023     shubman gill          890
1604   2022       jc buttler          863
911    2016        da warner          848
2100   2025  b sai sudharsan          759

In [ ]:
train_df['season'].value_counts()

season
2013       18177
2022       17912
2023       17863
2012       17767
2025       17285
2024       17103
2020/21    14559
2009/10    14498
2014       14300
2018       14286
2016       14096
2017       13862
2015       13652
2007/08    13489
2021       11434
2011        9454
2009        8192
2011        7559
2019        7286
2019        7026
2009        5414
2021        2991
Name: count, dtype: int64

In [ ]:
train_df['season']=train_df['year']

# most witckets by bowler

In [ ]:
train_df['wicket_kind'].value_counts()

wicket_kind
not out                  264382
caught                     8665
bowled                     2345
run out                    1153
lbw                         853
caught and bowled           388
stumped                     376
hit wicket                   18
retired hurt                 17
retired out                   5
obstructing the field         3
Name: count, dtype: int64

In [ ]:
no_credits=['not out','run out','retired hurt','retired out','obstructing the field']
wickets_df=train_df[~train_df['wicket_kind'].isin(no_credits)]

In [ ]:
wickets_df.sample(5)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
252230,1426273,2024-04-20,2,Delhi Capitals,Sunrisers Hyderabad,1,1.6,da warner,2,0,1,b kumar,1,0,0,0,False,no_extra_runs,j fraser-mcgurk,3,caught,DA Warner,PJ Cummins,267.0,NaN,NaN,NaN,NaN,False,TM Head,Sunrisers Hyderabad,67 runs,Delhi Capitals,field,"Arun Jaitley Stadium, Delhi",Delhi,20,4,2024,2024,male,club,NaN,NaN,NaN,6,20,35,Unknown,Unknown,25,12,2,NaN,1,3,1,"('DA Warner', 'J Fraser-McGurk')",Abishek Porel,True,267,199.0,0
209145,1304051,2022-03-29,1,Rajasthan Royals,Sunrisers Hyderabad,19,19.6,r parag,6,0,1,t natarajan,1,0,0,0,False,no_extra_runs,nm coulter-nile,7,caught,R Parag,N Pooran,NaN,NaN,NaN,NaN,NaN,False,SV Samson,Rajasthan Royals,61 runs,Sunrisers Hyderabad,field,"Maharashtra Cricket Association Stadium, Pune",Pune,29,3,2022,2022,male,club,NaN,NaN,NaN,6,20,5,Unknown,Unknown,210,120,6,NaN,12,9,1,"('NM Coulter-Nile', 'R Parag')",NaN,True,211,149.0,0
222972,1304108,2022-05-15,2,Gujarat Titans,Chennai Super Kings,11,11.2,ms wade,3,0,1,mm ali,1,0,0,0,False,no_extra_runs,wp saha,1,caught,MS Wade,S Dube,134.0,NaN,NaN,NaN,NaN,False,WP Saha,Gujarat Titans,7 wickets,Chennai Super Kings,bat,"Wankhede Stadium, Mumbai",Mumbai,15,5,2022,2022,male,club,NaN,NaN,NaN,6,20,62,Unknown,Unknown,90,68,2,NaN,20,15,1,"('MS Wade', 'WP Saha')",HH Pandya,True,134,137.0,0
46644,501220,2011-04-21,1,Kings XI Punjab,Rajasthan Royals,19,19.6,pp chawla,8,0,1,sw tait,1,0,0,0,False,no_extra_runs,sunny singh,7,bowled,PP Chawla,NaN,NaN,NaN,NaN,NaN,NaN,False,SE Marsh,Kings XI Punjab,48 runs,Rajasthan Royals,field,"Punjab Cricket Association Stadium, Mohali",Chandigarh,21,4,2011,2011,male,club,NaN,NaN,NaN,6,20,23,Unknown,Unknown,195,120,7,NaN,4,3,1,"('PP Chawla', 'Sunny Singh')",NaN,True,196,147.0,0
263192,1473447,2025-03-30,1,Sunrisers Hyderabad,Delhi Capitals,10,10.5,h klaasen,6,0,1,mm sharma,1,0,0,0,False,no_extra_runs,aniket verma,5,caught,H Klaasen,V Nigam,NaN,NaN,NaN,NaN,NaN,False,MA Starc,Delhi Capitals,7 wickets,Sunrisers Hyderabad,bat,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Visakhapatnam,30,3,2025,2025,male,club,NaN,NaN,NaN,6,20,10,Unknown,Unknown,114,65,5,NaN,32,19,1,"('Aniket Verma', 'H Klaasen')",A Manohar,True,164,166.0,0

In [ ]:
wickets_df.shape

(12645, 63)

In [ ]:
wickets_df['wicket_kind'].value_counts()

wicket_kind
caught               8665
bowled               2345
lbw                   853
caught and bowled     388
stumped               376
hit wicket             18
Name: count, dtype: int64

In [ ]:
wickets_df.groupby('bowler')['bowler_wicket'].sum().reset_index().sort_values(by='bowler_wicket',ascending=False).head(1)

        bowler  bowler_wicket
461  ys chahal            221

In [ ]:
bowler_runs=train_df.groupby(['date','bowler'])['runs_bowler'].sum().reset_index()

In [ ]:
bowler_runs.sort_values(by='runs_bowler', ascending=False).head()

             date          bowler  runs_bowler
12994  2025-03-23       jc archer           76
13286  2025-04-12  mohammed shami           75
13797  2025-05-27      w o'rourke           74
12594  2024-04-24       mm sharma           73
8169   2018-05-17    basil thampi           70

In [ ]:
bowler_ball=train_df.groupby(['date','bowler'])['valid_ball'].sum().reset_index()

In [ ]:
wickets_df=wickets_df.groupby(['date','bowler'])['bowler_wicket'].sum().reset_index().merge(bowler_runs,\
    on=['date','bowler'],how='left').merge(bowler_ball,\
    on=['date','bowler'],how='left')

In [ ]:
wickets_df=wickets_df.sort_values(by=['bowler_wicket', 'runs_bowler'], ascending=[False,True])

In [ ]:
wickets_df.groupby('bowler')['bowler_wicket'].sum().reset_index().sort_values(by='bowler_wicket',ascending=False).head(1)

        bowler  bowler_wicket
461  ys chahal            221

In [ ]:
wickets_df.head()

            date         bowler  bowler_wicket  runs_bowler  valid_ball
4781  2019-04-06      as joseph              6           12          22
164   2008-05-04  sohail tanvir              6           14          24
3697  2016-05-10        a zampa              6           19          24
375   2009-04-18       a kumble              5            5          19
6881  2023-05-24  akash madhwal              5            5          21

adding the columns wicket kind also to the same wickets df

savingthe wickets_df intothe  file|

In [ ]:
wickets_df.to_csv("bowler_wicket_runs.csv", index=False)

#  most catches

In [ ]:
train_df.tail()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
278200,1473511,2025-06-03,2,Punjab Kings,Royal Challengers Bengaluru,19,19.2,shashank singh,6,0,1,jr hazlewood,1,0,0,0,False,no_extra_runs,ka jamieson,9,not out,not out,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False,191,184.0,0
278201,1473511,2025-06-03,2,Punjab Kings,Royal Challengers Bengaluru,19,19.3,shashank singh,6,6,1,jr hazlewood,1,0,6,6,False,no_extra_runs,ka jamieson,9,not out,not out,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False,191,184.0,0
278202,1473511,2025-06-03,2,Punjab Kings,Royal Challengers Bengaluru,19,19.4,shashank singh,6,4,1,jr hazlewood,1,0,4,4,False,no_extra_runs,ka jamieson,9,not out,not out,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False,191,184.0,0
278203,1473511,2025-06-03,2,Punjab Kings,Royal Challengers Bengaluru,19,19.5,shashank singh,6,6,1,jr hazlewood,1,0,6,6,False,no_extra_runs,ka jamieson,9,not out,not out,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False,191,184.0,0
278204,1473511,2025-06-03,2,Punjab Kings,Royal Challengers Bengaluru,19,19.6,shashank singh,6,6,1,jr hazlewood,1,0,6,6,False,no_extra_runs,ka jamieson,9,not out,not out,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False,191,184.0,0

In [ ]:
train_df[train_df['wicket_kind']=='caught'].groupby('fielders')['wicket_kind'].value_counts().reset_index().sort_values(by='count',ascending=False).head(10)

           fielders wicket_kind  count
347        MS Dhoni      caught    158
258      KD Karthik      caught    145
23   AB de Villiers      caught    120
594         V Kohli      caught    117
513        SK Raina      caught    106
444       RA Jadeja      caught    103
452       RG Sharma      caught    101
483        S Dhawan      caught    100
253      KA Pollard      caught     97
615         WP Saha      caught     93

we nedd tofilter out the keeoer by first findinfthe uniquw values of stumed then we need to not include person with stumedin fielder

In [ ]:
wickets_keepers=train_df[train_df['wicket_kind']=='stumped']['fielders'].unique()

In [ ]:
wickets_keepers

array(['MV Boucher', 'Kamran Akmal', 'WP Saha', 'YV Takawale',
       'AC Gilchrist', 'KD Karthik', 'SP Goswami', 'RV Uthappa',
       'MS Dhoni', 'PR Shah', 'M Rawat', 'NV Ojha', 'KC Sangakkara',
       'AP Tare', 'PA Patel', 'AT Rayudu', 'AB de Villiers', 'DJ Jacobs',
       'MS Bisla', 'DH Yagnik', 'KH Devdhar', 'N Saini', 'BB McCullum',
       'KB Arun Karthik', 'KM Jadhav', 'Q de Kock', 'Gurkeerat Singh',
       'CM Gautam', 'SV Samson', 'KL Rahul', 'RR Pant', 'Vishnu Vinod',
       'Ishan Kishan', 'JC Buttler', 'H Klaasen', 'JM Bairstow',
       'KS Bharat', 'SP Jackson', 'SW Billings', 'N Pooran', 'JM Sharma',
       'MS Wade', 'P Simran Singh', 'RD Rickelton', 'JP Inglis',
       'T Stubbs'], dtype=object)

In [ ]:
bowl_df = train_df[train_df['bowler'] =='v kohli']

In [ ]:
bowl_df[bowl_df['valid_ball']==1].shape

(251, 63)

In [ ]:
@st.cache_data
def wicket_keeper(df):
    return df.loc[df['wicket_kind'] == 'stumped', 'fielders'].dropna()

wickets_keeper1 = wicket_keeper(train_df).unique()

2026-05-05 20:24:38.559 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [ ]:
wickets_keeper1

array(['MV Boucher', 'Kamran Akmal', 'WP Saha', 'YV Takawale',
       'AC Gilchrist', 'KD Karthik', 'SP Goswami', 'RV Uthappa',
       'MS Dhoni', 'PR Shah', 'M Rawat', 'NV Ojha', 'KC Sangakkara',
       'AP Tare', 'PA Patel', 'AT Rayudu', 'AB de Villiers', 'DJ Jacobs',
       'MS Bisla', 'DH Yagnik', 'KH Devdhar', 'N Saini', 'BB McCullum',
       'KB Arun Karthik', 'KM Jadhav', 'Q de Kock', 'Gurkeerat Singh',
       'CM Gautam', 'SV Samson', 'KL Rahul', 'RR Pant', 'Vishnu Vinod',
       'Ishan Kishan', 'JC Buttler', 'H Klaasen', 'JM Bairstow',
       'KS Bharat', 'SP Jackson', 'SW Billings', 'N Pooran', 'JM Sharma',
       'MS Wade', 'P Simran Singh', 'RD Rickelton', 'JP Inglis',
       'T Stubbs'], dtype=object)

In [ ]:
train_df[
    (train_df['wicket_kind'] == 'caught') &
    (~train_df['fielders'].isin(wickets_keepers))
].groupby('fielders')['wicket_kind'].value_counts().reset_index().sort_values(by='count',ascending=False).head(1)

    fielders wicket_kind  count
552  V Kohli      caught    117

we need to create function in order to get the required df so we dint load to muchof the df and notto much of therequired columns so we are 
going to use the def function the app.py to get the required data

In [ ]:
@st.cache_data
def get_top_catches(df,wkt):
    return (
        df[
            (df['wicket_kind'] == 'caught') &
            (~df['fielders'].isin(wkt))
        ]
        .groupby('fielders')
        .size()
        .reset_index(name='count')
        .sort_values(by='count', ascending=False)
    )

top_catches_df = get_top_catches(train_df,wickets_keeper1)
# st.dataframe(top_catches_df.head(10))

2026-05-05 20:24:38.746 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-05 20:24:38.811 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
top_catches_df.head()

      fielders  count
552    V Kohli    117
476   SK Raina    106
410  RA Jadeja    103
417  RG Sharma    101
446   S Dhawan    100

droping the columns which is not neeed

In [ ]:
train_df.columns

Index(['match_id', 'date', 'innings', 'batting_team', 'bowling_team', 'over',
       'ball_no', 'batter', 'bat_pos', 'runs_batter', 'balls_faced', 'bowler',
       'valid_ball', 'runs_extras', 'runs_total', 'runs_bowler',
       'runs_not_boundary', 'extra_type', 'non_striker', 'non_striker_pos',
       'wicket_kind', 'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out', 'target_score', 'chased_score', 'tie_match'],
      dtype='object')

# most match played by

In [ ]:
batter_df=train_df.drop_duplicates(subset=['date','batter'])
batter_df=batter_df[['match_id','batter']].rename(columns={'batter':'player'})

In [ ]:
bowler_df=train_df.drop_duplicates(subset=['date','bowler'])
bowler_df=bowler_df[['match_id','bowler']].rename(columns={'bowler':'player'})

In [ ]:
fieder_df=train_df.dropna(subset=['fielders'])
fieder_df=fieder_df[['match_id','fielders']].rename(columns={'fielders':'player'})

In [ ]:
playersinmatch=pd.concat([bowler_df,batter_df,fieder_df])

In [ ]:
playersinmatch=playersinmatch.drop_duplicates()

In [ ]:
playersinmatch.head()

    match_id     player
0     335982    p kumar
7     335982     z khan
19    335982  aa noffke
50    335982  jh kallis
56    335982   sb joshi

In [ ]:
playersinmatch=playersinmatch.groupby('player')['match_id'].nunique().reset_index(name='matches').sort_values(by='matches', ascending=False).head(1)

In [ ]:
playersinmatch['player'].iloc[0]

'rg sharma'

In [ ]:
playersinmatch['matches'].iloc[0]

np.int64(266)

# most succesfull team

In [ ]:
train_df.sample(5)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
258364,1426299,2024-05-12,1,Rajasthan Royals,Chennai Super Kings,9,9.6,r parag,4,1,1,ra jadeja,1,0,1,1,False,no_extra_runs,sv samson,3,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Simarjeet Singh,Chennai Super Kings,5 wickets,Rajasthan Royals,bat,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,12,5,2024,2024,male,club,NaN,NaN,NaN,6,20,61,Unknown,Unknown,61,60,2,NaN,10,8,0,"('R Parag', 'SV Samson')",NaN,False,142,145.0,0
99051,729315,2014-04-29,3,Kolkata Knight Riders,Rajasthan Royals,0,0.2,mk pandey,3,1,1,jp faulkner,1,0,1,1,False,no_extra_runs,shakib al hasan,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,JP Faulkner,Rajasthan Royals,NaN,Rajasthan Royals,bat,Sheikh Zayed Stadium,Abu Dhabi,29,4,2014,2014,male,club,Rajasthan Royals,tie,NaN,6,20,19,Unknown,Unknown,2,2,1,MK Pandey,1,1,0,"('MK Pandey', 'Shakib Al Hasan')",NaN,False,153,152.0,1
36502,419144,2010-04-07,2,Delhi Daredevils,Kolkata Knight Riders,7,7.1,g gambhir,3,1,1,baw mendis,1,0,1,1,False,no_extra_runs,v sehwag,2,not out,not out,NaN,182.0,NaN,NaN,NaN,NaN,False,SC Ganguly,Kolkata Knight Riders,14 runs,Kolkata Knight Riders,bat,Eden Gardens,Kolkata,7,4,2010,2010,male,club,NaN,NaN,NaN,6,20,39,Unknown,Unknown,59,43,1,NaN,23,17,0,"('G Gambhir', 'V Sehwag')",NaN,False,182,167.0,0
48172,501226,2011-04-25,2,Pune Warriors,Chennai Super Kings,13,13.2,nl mccullum,7,3,1,sb jakati,1,0,3,3,False,no_extra_runs,yuvraj singh,5,not out,not out,NaN,143.0,NaN,NaN,NaN,NaN,False,MEK Hussey,Chennai Super Kings,25 runs,Pune Warriors,field,"MA Chidambaram Stadium, Chepauk",Chennai,25,4,2011,2011,male,club,NaN,NaN,NaN,6,20,29,Unknown,Unknown,82,80,5,NaN,3,2,0,"('NL McCullum', 'Yuvraj Singh')",NaN,False,143,117.0,0
275872,1473503,2025-05-23,1,Sunrisers Hyderabad,Royal Challengers Bengaluru,5,5.2,ishan kishan,3,2,1,l ngidi,1,0,2,2,False,no_extra_runs,h klaasen,4,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Ishan Kishan,Sunrisers Hyderabad,42 runs,Royal Challengers Bengaluru,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,23,5,2025,2025,male,club,NaN,NaN,NaN,6,20,65,Unknown,Unknown,60,32,2,NaN,4,2,0,"('H Klaasen', 'Ishan Kishan')",NaN,False,232,189.0,0

In [ ]:
train_df[train_df['stage']=='Final'].shape

(4338, 63)

In [ ]:
mst=train_df[train_df['stage']=='Final'].drop_duplicates(subset=['match_id','date'])

In [ ]:
mst['match_won_by'].value_counts().reset_index().sort_values(by='count', ascending=False)

                  match_won_by  count
0          Chennai Super Kings      5
1               Mumbai Indians      5
2        Kolkata Knight Riders      3
3              Deccan Chargers      1
4             Rajasthan Royals      1
5          Sunrisers Hyderabad      1
6               Gujarat Titans      1
7  Royal Challengers Bengaluru      1

In [ ]:
train_df['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Brabourne Stadium, Mumbai',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Arun Jaitley Stadium', 'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai', 'Narendra Modi Stadium, Ahmedabad',
       'Arun Jaitley Stadium, Delhi', 'Zayed Cricket Stadium, Abu Dhabi',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Eden Gardens, Kolkata',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'M Chinnaswamy Stadium, Bengaluru',
       'Barsapara Cricket Stadium, Guwahati',
       'Sawai Mansingh Stadium, Jaipur',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'],
      dtype=object)

In [ ]:
venu_place=train_df[train_df['venue']=='Wankhede Stadium']

In [ ]:
train_df['bowling_team'].unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Kings XI Punjab', 'Chennai Super Kings', 'Delhi Daredevils',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
venu_place['bowling_team'].unique()

array(['Royal Challengers Bangalore', 'Mumbai Indians',
       'Chennai Super Kings', 'Kolkata Knight Riders', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rajasthan Royals', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Deccan Chargers', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [ ]:
train_df[train_df['venue']=='Wankhede Stadium'].groupby('match_won_by')['match_won_by'].count().reset_index(name='count').sort_values(by='count', ascending=False)

                   match_won_by  count
8                Mumbai Indians  10132
0           Chennai Super Kings   1679
5               Kings XI Punjab   1255
10             Rajasthan Royals    907
13  Royal Challengers Bangalore    727
11       Rising Pune Supergiant    497
3              Delhi Daredevils    461
4                 Gujarat Lions    251
1               Deccan Chargers    249
9                 Pune Warriors    247
6          Kochi Tuskers Kerala    247
2                Delhi Capitals    246
7         Kolkata Knight Riders    245
14          Sunrisers Hyderabad    230
12      Rising Pune Supergiants    218

# top run score

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0

In [ ]:
train_df.groupby('batter')['runs_batter'].sum().sort_values(ascending=False).head(7)

batter
v kohli      8671
rg sharma    7048
s dhawan     6769
da warner    6567
sk raina     5536
ms dhoni     5439
kl rahul     5235
Name: runs_batter, dtype: int64

# highest team total

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0

In [ ]:
train_df['innings'].value_counts()

innings
1    144131
2    133903
3        83
4        76
5         8
6         4
Name: count, dtype: int64

the ining of 3 ,4,5 are represented as the tie match btweenplayers of we are going to replace 3 -=3,4=4,5=3,6=4 so we can see what arethe matches and over played ini tie match

In [ ]:
ining_corect={
    1:1,
    2:2,
    3:3,
    4:4,
    5:3,
    6:4
}
train_df['innings']=train_df['innings'].map(ining_corect)

In [ ]:
train_df['innings'].value_counts()

innings
1    144131
2    133903
3        91
4        80
Name: count, dtype: int64

In [ ]:
higest_team_total=train_df.groupby(["date","batting_team"])['bowler_wicket'].sum().reset_index()

In [ ]:
higest_team_total.head()

         date                 batting_team  bowler_wicket
0  2008-04-18        Kolkata Knight Riders              3
1  2008-04-18  Royal Challengers Bangalore              9
2  2008-04-19          Chennai Super Kings              5
3  2008-04-19             Delhi Daredevils              1
4  2008-04-19              Kings XI Punjab              4

In [ ]:
higest_team_total.merge(train_df[['date','innings','batting_team','target_score']],\
    on=['date','batting_team'],how='left').sort_values(by=['innings','target_score'],ascending=[True,False]).drop_duplicates(subset=['date','batting_team']).head()

,date,batting_team,bowler_wicket,innings,target_score
251036,2024-04-15,Sunrisers Hyderabad,3,1,288
261515,2025-03-23,Sunrisers Hyderabad,6,1,287
276694,2025-05-25,Sunrisers Hyderabad,3,1,279
245687,2024-03-27,Sunrisers Hyderabad,3,1,278
247619,2024-04-03,Kolkata Knight Riders,7,1,273

# most 6s and 4rs

In [ ]:
train_df['runs_not_boundary'].value_counts()

runs_not_boundary
False    278177
True         28
Name: count, dtype: int64

In [ ]:
train_df.sample(4)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match
117387,829781,2015-05-04,1,Kolkata Knight Riders,Sunrisers Hyderabad,12,12.5,mk pandey,3,1,1,kv sharma,1,0,1,1,False,no_extra_runs,rn ten doeschate,5,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,UT Yadav,Kolkata Knight Riders,35 runs,Sunrisers Hyderabad,field,Eden Gardens,Kolkata,4,5,2015,2015,male,club,NaN,NaN,NaN,6,20,38,Unknown,Unknown,99,77,3,NaN,31,23,0,"('MK Pandey', 'RN ten Doeschate')",NaN,False,168,132.0,0
102360,733995,2014-05-10,2,Chennai Super Kings,Mumbai Indians,17,17.6,ra jadeja,6,0,1,jj bumrah,1,0,0,0,False,no_extra_runs,ms dhoni,5,not out,not out,NaN,158.0,NaN,NaN,NaN,NaN,False,DR Smith,Chennai Super Kings,4 wickets,Chennai Super Kings,field,Wankhede Stadium,Mumbai,10,5,2014,2014,male,club,NaN,NaN,NaN,6,20,33,Unknown,Unknown,141,108,4,NaN,5,5,0,"('MS Dhoni', 'RA Jadeja')",NaN,False,158,160.0,0
111071,829725,2015-04-15,1,Kings XI Punjab,Delhi Daredevils,2,2.4,v sehwag,2,0,1,nm coulter-nile,1,0,0,0,False,no_extra_runs,m vijay,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,MA Agarwal,Delhi Daredevils,5 wickets,Kings XI Punjab,bat,Maharashtra Cricket Association Stadium,Pune,15,4,2015,2015,male,club,NaN,NaN,NaN,6,20,10,Unknown,Unknown,12,16,0,NaN,0,5,0,"('M Vijay', 'V Sehwag')",NaN,False,166,169.0,0
211960,1304063,2022-04-09,1,Chennai Super Kings,Sunrisers Hyderabad,6,6.3,at rayudu,4,4,1,umran malik,1,0,4,4,False,no_extra_runs,mm ali,3,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,Abhishek Sharma,Sunrisers Hyderabad,8 wickets,Sunrisers Hyderabad,field,"Dr DY Patil Sports Academy, Mumbai",Mumbai,9,4,2022,2022,male,club,NaN,NaN,NaN,6,20,17,Unknown,Unknown,45,39,2,NaN,5,5,0,"('AT Rayudu', 'MM Ali')",NaN,False,155,155.0,0

In [ ]:
train_df['6s']=np.where((train_df['runs_batter']==6)&(train_df['runs_not_boundary']==False),1,0)
train_df['4s']=np.where((train_df['runs_batter']==4)&(train_df['runs_not_boundary']==False),1,0)

In [ ]:
train_df[train_df['4s']==1].head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match,6s,4s
8,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.2,bb mccullum,2,4,1,z khan,1,0,4,4,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,7,8,0,NaN,4,7,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,1
9,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.3,bb mccullum,2,4,1,z khan,1,0,4,4,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,11,9,0,NaN,8,8,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,1
11,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1.5,bb mccullum,2,4,1,z khan,1,0,4,4,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,21,11,0,NaN,18,10,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,1
16,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2.4,bb mccullum,2,4,1,p kumar,1,0,4,4,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,26,16,0,NaN,22,12,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,1
22,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,3.3,sc ganguly,1,4,1,aa noffke,1,0,4,4,False,no_extra_runs,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,43,21,0,NaN,4,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,1

we aregoing to drop the rows were the ining isgreater than 2 as theseare thematches in tie match score scored in these over are not credit to the batsman or bowler

In [ ]:
notiesmatch_df=train_df[train_df['innings']<=2]

In [ ]:
notiesmatch_df[(notiesmatch_df['season']==2013)&(notiesmatch_df['batter']=='ch gayle')&(notiesmatch_df['6s']==1)].shape

(51, 65)

In [ ]:
notiesmatch_df.groupby(['season','batter'])['4s'].sum().reset_index().sort_values(by='4s',ascending=False).head(10)

      season           batter  4s
1278    2016        da warner  88
2640    2025  b sai sudharsan  88
446     2010     sr tendulkar  86
2416    2023     shubman gill  85
2144    2022       jc buttler  83
1383    2016          v kohli  83
2443    2023      ybk jaiswal  82
911     2013       mek hussey  81
2312    2023        dp conway  77
1088    2014       rv uthappa  74

In [ ]:
notiesmatch_df.groupby(['season','batter'])['6s'].sum().reset_index().sort_values(by='6s',ascending=False).head(10)

      season           batter  6s
684     2012         ch gayle  59
1673    2019       ad russell  52
852     2013         ch gayle  51
2144    2022       jc buttler  45
502     2011         ch gayle  44
2453    2024  abhishek sharma  42
2707    2025         n pooran  40
2762    2025          ss iyer  39
2606    2024          v kohli  38
2489    2024        h klaasen  38

# match summary

In [ ]:
train_df.head(
    
)

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0

In [ ]:
id=335982
summary=train_df[train_df['match_id']==id]

In [ ]:
batting_df=summary[summary['innings']==1]  # it contain both data battting and ininf

In [ ]:
batting_df.shape

(124, 65)

In [ ]:
batting_df=batting_df.groupby(['batter','bat_pos'])[['runs_batter','balls_faced','4s','6s']].sum().reset_index().head()

In [ ]:
batting_df['SR']=round((batting_df['runs_batter']/batting_df['balls_faced'])*100,2)

In [ ]:
batting_df.head()

            batter  bat_pos  runs_batter  balls_faced  4s  6s      SR
0      bb mccullum        2          158           73  10  13  216.44
1        dj hussey        4           12           12   1   0  100.00
2  mohammad hafeez        5            5            3   1   0  166.67
3       rt ponting        3           20           20   1   1  100.00
4       sc ganguly        1           10           12   2   0   83.33

In [ ]:
# extracting the data were the only batting is involved

In [ ]:
train_df['venue'].unique(
    
)

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Brabourne Stadium, Mumbai',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Arun Jaitley Stadium', 'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai', 'Narendra Modi Stadium, Ahmedabad',
       'Arun Jaitley Stadium, Delhi', 'Zayed Cricket Stadium, Abu Dhabi',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Eden Gardens, Kolkata',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'M Chinnaswamy Stadium, Bengaluru',
       'Barsapara Cricket Stadium, Guwahati',
       'Sawai Mansingh Stadium, Jaipur',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'],
      dtype=object)

In [ ]:
wkstd=train_df[train_df['venue']=='Wankhede Stadium, Mumbai']

In [ ]:
wkstd['bowling_team'].unique()

array(['Delhi Capitals', 'Chennai Super Kings', 'Rajasthan Royals',
       'Punjab Kings', 'Kolkata Knight Riders',
       'Royal Challengers Bangalore', 'Gujarat Titans',
       'Lucknow Super Giants', 'Mumbai Indians', 'Sunrisers Hyderabad',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
wkstd.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match,6s,4s
193867,1254059,2021-04-10,1,Chennai Super Kings,Delhi Capitals,0,0.1,rd gaikwad,1,0,1,cr woakes,1,0,0,0,False,no_extra_runs,f du plessis,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,S Dhawan,Delhi Capitals,7 wickets,Delhi Capitals,field,"Wankhede Stadium, Mumbai",Mumbai,10,4,2021,2021,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,0,1,0,NaN,0,1,0,"('F du Plessis', 'RD Gaikwad')",NaN,False,189,190.0,0,0,0
193868,1254059,2021-04-10,1,Chennai Super Kings,Delhi Capitals,0,0.2,rd gaikwad,1,0,1,cr woakes,1,0,0,0,False,no_extra_runs,f du plessis,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,S Dhawan,Delhi Capitals,7 wickets,Delhi Capitals,field,"Wankhede Stadium, Mumbai",Mumbai,10,4,2021,2021,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,0,2,0,NaN,0,2,0,"('F du Plessis', 'RD Gaikwad')",NaN,False,189,190.0,0,0,0
193869,1254059,2021-04-10,1,Chennai Super Kings,Delhi Capitals,0,0.3,rd gaikwad,1,4,1,cr woakes,1,0,4,4,False,no_extra_runs,f du plessis,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,S Dhawan,Delhi Capitals,7 wickets,Delhi Capitals,field,"Wankhede Stadium, Mumbai",Mumbai,10,4,2021,2021,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,4,3,0,NaN,4,3,0,"('F du Plessis', 'RD Gaikwad')",NaN,False,189,190.0,0,0,1
193870,1254059,2021-04-10,1,Chennai Super Kings,Delhi Capitals,0,0.4,rd gaikwad,1,0,1,cr woakes,1,1,1,0,False,legbyes,f du plessis,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,S Dhawan,Delhi Capitals,7 wickets,Delhi Capitals,field,"Wankhede Stadium, Mumbai",Mumbai,10,4,2021,2021,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,5,4,0,NaN,4,4,0,"('F du Plessis', 'RD Gaikwad')",NaN,False,189,190.0,0,0,0
193871,1254059,2021-04-10,1,Chennai Super Kings,Delhi Capitals,0,0.5,f du plessis,2,0,1,cr woakes,1,0,0,0,False,no_extra_runs,rd gaikwad,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,S Dhawan,Delhi Capitals,7 wickets,Delhi Capitals,field,"Wankhede Stadium, Mumbai",Mumbai,10,4,2021,2021,male,club,NaN,NaN,NaN,6,20,2,Unknown,Unknown,5,5,0,NaN,0,1,0,"('F du Plessis', 'RD Gaikwad')",NaN,False,189,190.0,0,0,0

In [ ]:
review=wkstd[(wkstd['bowling_team']=='Mumbai Indians') &(wkstd['batting_team']=='Lucknow Super Giants')]

In [ ]:
review.groupby('batter')['runs_batter'].sum().reset_index().sort_values(by='runs_batter',ascending=False).head(10)

          batter  runs_batter
11      kl rahul          158
15      n pooran          102
0       a badoni           71
14      mr marsh           34
13    mp stoinis           28
6      da miller           24
12     mk pandey           22
7       dj hooda           21
18  ravi bishnoi           13
10     kh pandya           13

In [ ]:
review.groupby('bowler')['bowler_wicket'].sum().reset_index().sort_values(by='bowler_wicket', ascending=False)

             bowler  bowler_wicket
8         jj bumrah              5
17         ta boult              3
14        pp chawla              3
11       n thushara              3
16      rp meredith              2
18         wg jacks              2
9        ka pollard              2
2           c bosch              1
4           dr sams              1
1   arjun tendulkar              0
0          a kamboj              0
10        kv sharma              0
7        jd unadkat              0
5         hh pandya              0
6        hr shokeen              0
3         dl chahar              0
12        n wadhera              0
13       naman dhir              0
15       r shepherd              0

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,bb mccullum,2,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,sc ganguly,1,not out,not out,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2008,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,223,82.0,0,0,0

In [ ]:
drop_col=['striker_out','next_batter','new_batter','team_wicket','team_balls','team_runs','match_number','overs','balls_per_over','team_type',\
    'gender','year','month','day','non_striker_pos','ball_no','non_striker','runs_target','event_match_no','batter_runs','batter_balls','player_out']
train_df.drop(columns=drop_col,inplace=True)

In [ ]:
train_df.to_csv("data\cleaned_ipl_data.csv", index=False)

In [ ]:
train_df.shape

(278205, 43)

In [ ]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,bb mccullum,2,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0

In [ ]:
train_df['runs_batter'].sum()

np.int64(355373)

# clean_df

In [ ]:
clean_df = train_df.drop_duplicates(subset=['match_id'], keep='first')
clean_df.shape

(1169, 43)

In [ ]:
clean_df.head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
225,335983,2008-04-19,1,Chennai Super Kings,Kings XI Punjab,0,pa patel,1,0,1,b lee,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,"Punjab Cricket Association Stadium, Mohali",Chandigarh,2008,NaN,NaN,NaN,Unknown,0,"('ML Hayden', 'PA Patel')",241,207.0,0,0,0
473,335984,2008-04-19,1,Rajasthan Royals,Delhi Daredevils,0,t kohli,1,0,1,gd mcgrath,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,Feroz Shah Kotla,Delhi,2008,NaN,NaN,NaN,Unknown,0,"('T Kohli', 'YK Pathan')",130,132.0,0,0,0
692,335985,2008-04-20,1,Mumbai Indians,Royal Challengers Bangalore,0,l ronchi,1,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,Wankhede Stadium,Mumbai,2008,NaN,NaN,NaN,Unknown,0,"('L Ronchi', 'ST Jayasuriya')",166,166.0,0,0,0
938,335986,2008-04-20,1,Deccan Chargers,Kolkata Knight Riders,0,ac gilchrist,1,1,1,ab dinda,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,Eden Gardens,Kolkata,2008,NaN,NaN,NaN,Unknown,0,"('AC Gilchrist', 'Y Venugopal Rao')",111,112.0,0,0,0

# team withmost win a season

In [ ]:
clean_df.groupby('season')['match_won_by'].value_counts().reset_index().sort_values(by='count',ascending=False).head()

    season           match_won_by  count
0     2008       Rajasthan Royals     13
43    2013         Mumbai Indians     13
34    2012  Kolkata Knight Riders     12
52    2014        Kings XI Punjab     12
44    2013    Chennai Super Kings     12

In [ ]:
clean_df['batting_team'].value_counts().head()

batting_team
Mumbai Indians                 143
Chennai Super Kings            136
Kolkata Knight Riders          126
Royal Challengers Bangalore    121
Rajasthan Royals               107
Name: count, dtype: int64

In [ ]:
clean_df['batter'].value_counts()

batter
da warner             59
v kohli               43
am rahane             40
kl rahul              38
rg sharma             37
q de kock             36
pp shaw               34
pa patel              33
dr smith              32
ch gayle              31
ac gilchrist          30
rd gaikwad            28
m vijay               28
rv uthappa            27
wp saha               24
s dhawan              23
ybk jaiswal           21
ma agarwal            21
g gambhir             20
sr watson             19
mek hussey            18
pd salt               17
bb mccullum           17
lmp simmons           16
st jayasuriya         14
jh kallis             14
jc buttler            14
aj finch              13
jd ryder              12
r dravid              12
abhishek sharma       12
f du plessis          12
shubman gill          11
priyansh arya         11
jj roy                10
ishan kishan          10
ca lynn               10
p simran singh         9
dpmd jayawardene       9
tm head                8
rs bopara              8
sc ganguly             8
mandeep singh          8
v sehwag               8
b sai sudharsan        7
ca pujara              7
sa yadav               7
gc smith               7
ms bisla               6
ak markram             6
se marsh               6
mj lumb                6
s sohal                6
salman butt            5
j fraser-mcgurk        5
sp narine              5
hm amla                5
mj guptill             5
rd rickelton           5
rahmanullah gurbaz     5
sv samson              5
d padikkal             5
ra tripathi            5
nv ojha                4
dj jacobs              4
mk pandey              4
mr marsh               4
vr iyer                4
e lewis                4
sm curran              4
jm bairstow            3
l ronchi               3
hh gibbs               3
sk rasheed             3
ms wade                3
m vohra                3
n rana                 3
kc sangakkara          3
pc valthaty            3
rt ponting             3
pa reddy               3
jr philippe            3
jec franklin           3
s vidyut               2
k goel                 2
abishek porel          2
a mhatre               2
anmolpreet singh       2
hc brook               2
ac blizzard            2
dj harris              2
mdkj perera            2
n saini                2
ap tare                2
ss tiwary              2
tl suman               2
s anirudha             2
mp stoinis             2
ad hales               2
atharva taide          2
r ravindra             2
re levi                2
b chipli               1
t kohli                1
s chanderpaul          1
j arunkumar            1
mv boucher             1
a chopra               1
w jaffer               1
yv takawale            1
s badrinath            1
mk tiwary              1
mn van wyk             1
sa asnodkar            1
rj quiney              1
gj bailey              1
md mishra              1
ejg morgan             1
r sathish              1
m klinger              1
fy fazal               1
rr rossouw             1
ankit sharma           1
am nayar               1
br dunk                1
a mukund               1
yk pathan              1
gj maxwell             1
ubt chand              1
ab mcdonald            1
ag paunikar            1
c madan                1
r mclaren              1
er dwivedi             1
rr pant                1
kp pietersen           1
c munro                1
ns naik                1
sp goswami             1
at rayudu              1
jl denly               1
spd smith              1
anuj rawat             1
pk garg                1
dp conway              1
dj hooda               1
c green                1
n jagadeesan           1
mw short               1
vivrant sharma         1
ks sharma              1
jg bethell             1
kk nair                1
Name: count, dtype: int64

In [ ]:
clean_df.head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
225,335983,2008-04-19,1,Chennai Super Kings,Kings XI Punjab,0,pa patel,1,0,1,b lee,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,"Punjab Cricket Association Stadium, Mohali",Chandigarh,2008,NaN,NaN,NaN,Unknown,0,"('ML Hayden', 'PA Patel')",241,207.0,0,0,0
473,335984,2008-04-19,1,Rajasthan Royals,Delhi Daredevils,0,t kohli,1,0,1,gd mcgrath,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,Feroz Shah Kotla,Delhi,2008,NaN,NaN,NaN,Unknown,0,"('T Kohli', 'YK Pathan')",130,132.0,0,0,0
692,335985,2008-04-20,1,Mumbai Indians,Royal Challengers Bangalore,0,l ronchi,1,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,Wankhede Stadium,Mumbai,2008,NaN,NaN,NaN,Unknown,0,"('L Ronchi', 'ST Jayasuriya')",166,166.0,0,0,0
938,335986,2008-04-20,1,Deccan Chargers,Kolkata Knight Riders,0,ac gilchrist,1,1,1,ab dinda,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,Eden Gardens,Kolkata,2008,NaN,NaN,NaN,Unknown,0,"('AC Gilchrist', 'Y Venugopal Rao')",111,112.0,0,0,0

In [ ]:
clean_df['player_of_match'].value_counts().head(10)

player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         21
V Kohli           19
DA Warner         18
MS Dhoni          18
SP Narine         17
AD Russell        16
SR Watson         16
YK Pathan         16
Name: count, dtype: int64

most matches won till the season

In [ ]:
clean_df['match_won_by'].value_counts().head(10)

match_won_by
Mumbai Indians                 153
Chennai Super Kings            142
Kolkata Knight Riders          136
Rajasthan Royals               116
Royal Challengers Bangalore    116
Sunrisers Hyderabad             94
Kings XI Punjab                 88
Delhi Daredevils                67
Delhi Capitals                  55
Gujarat Titans                  37
Name: count, dtype: int64

In [ ]:
clean_df[clean_df['win_outcome'].isnull()]

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s
15161,392190,2009-04-23,1,Rajasthan Royals,Kolkata Knight Riders,0,gc smith,1,0,1,i sharma,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,YK Pathan,Rajasthan Royals,NaN,Kolkata Knight Riders,field,Newlands,Cape Town,2009,Rajasthan Royals,tie,NaN,Unknown,0,"('GC Smith', 'PC Valthaty')",151,150.0,1,0,0
30707,419121,2010-03-21,1,Kings XI Punjab,Chennai Super Kings,0,rs bopara,1,1,1,ja morkel,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,J Theron,Kings XI Punjab,NaN,Chennai Super Kings,field,"MA Chidambaram Stadium, Chepauk",Chennai,2010,Kings XI Punjab,tie,NaN,Unknown,0,"('IK Pathan', 'RS Bopara')",137,136.0,1,0,0
57068,501265,2011-05-21,1,Delhi Daredevils,Pune Warriors,0,nv ojha,1,1,1,ac thomas,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Delhi Daredevils,bat,Feroz Shah Kotla,Delhi,2011,NaN,no result,NaN,Unknown,0,"('DA Warner', 'NV Ojha')",57,0.0,1,0,0
77794,598004,2013-04-07,1,Royal Challengers Bangalore,Sunrisers Hyderabad,0,ch gayle,1,1,1,dw steyn,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,GH Vihari,Sunrisers Hyderabad,NaN,Royal Challengers Bangalore,bat,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,2013,Sunrisers Hyderabad,tie,NaN,Unknown,0,"('CH Gayle', 'TM Dilshan')",131,130.0,1,0,0
81200,598017,2013-04-16,1,Delhi Daredevils,Royal Challengers Bangalore,0,da warner,1,0,1,r rampaul,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,V Kohli,Royal Challengers Bangalore,NaN,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2013,Royal Challengers Bangalore,tie,NaN,Unknown,0,"('DA Warner', 'V Sehwag')",153,152.0,1,0,0
98800,729315,2014-04-29,1,Rajasthan Royals,Kolkata Knight Riders,0,am rahane,1,2,1,r vinay kumar,1,0,2,2,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,JP Faulkner,Rajasthan Royals,NaN,Rajasthan Royals,bat,Sheikh Zayed Stadium,Abu Dhabi,2014,Rajasthan Royals,tie,NaN,Unknown,0,"('AM Rahane', 'KK Nair')",153,152.0,1,0,0
113004,829741,2015-04-21,1,Rajasthan Royals,Kings XI Punjab,0,am rahane,1,1,1,sandeep sharma,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,SE Marsh,Kings XI Punjab,NaN,Kings XI Punjab,field,"Sardar Patel Stadium, Motera",Ahmedabad,2015,Kings XI Punjab,tie,NaN,Unknown,0,"('AM Rahane', 'SR Watson')",192,191.0,1,0,0
115353,829763,2015-04-29,1,Royal Challengers Bangalore,Rajasthan Royals,0,ch gayle,1,0,1,tg southee,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Rajasthan Royals,field,M Chinnaswamy Stadium,Bangalore,2015,NaN,no result,NaN,Unknown,0,"('CH Gayle', 'V Kohli')",201,0.0,1,0,0
121177,829813,2015-05-17,1,Delhi Daredevils,Royal Challengers Bangalore,0,q de kock,1,1,1,ma starc,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2015,NaN,no result,NaN,Unknown,0,"('Q de Kock', 'SS Iyer')",188,2.0,1,0,0
144440,1082625,2017-04-29,1,Gujarat Lions,Mumbai Indians,0,ishan kishan,1,0,0,mj mcclenaghan,0,1,1,1,False,wides,not out,NaN,NaN,NaN,NaN,NaN,False,KH Pandya,Mumbai Indians,NaN,Gujarat Lions,bat,Saurashtra Cricket Association Stadium,Rajkot,2017,Mumbai Indians,tie,NaN,Unknown,0,"('BB McCullum', 'Ishan Kishan')",154,153.0,1,0,0
166931,1175365,2019-03-30,1,Kolkata Knight Riders,Delhi Capitals,0,ns naik,1,4,1,k rabada,1,0,4,4,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,PP Shaw,Delhi Capitals,NaN,Delhi Capitals,field,Arun Jaitley Stadium,Delhi,2019,Delhi Capitals,tie,NaN,Unknown,0,"('CA Lynn', 'NS Naik')",186,185.0,1,0,1
176392,1178424,2019-04-30,1,Royal Challengers Bangalore,Rajasthan Royals,0,v kohli,1,6,1,vr aaron,1,0,6,6,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Rajasthan Royals,field,M.Chinnaswamy Stadium,Bengaluru,2019,NaN,no result,NaN,Unknown,0,"('AB de Villiers', 'V Kohli')",63,41.0,1,1,0
176666,1178426,2019-05-02,1,Mumbai Indians,Sunrisers Hyderabad,0,rg sharma,1,0,1,b kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,JJ Bumrah,Mumbai Indians,NaN,Mumbai Indians,bat,Wankhede Stadium,Mumbai,2019,Mumbai Indians,tie,NaN,Unknown,0,"('Q de Kock', 'RG Sharma')",163,162.0,1,0,0
179302,1216493,2020-09-20,1,Delhi Capitals,Kings XI Punjab,0,pp shaw,1,0,1,ss cottrell,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MP Stoinis,Delhi Capitals,NaN,Kings XI Punjab,field,Dubai International Cricket Stadium,Unknown,2020,Delhi Capitals,tie,NaN,Unknown,0,"('PP Shaw', 'S Dhawan')",158,157.0,1,0,0
181275,1216547,2020-09-28,1,Royal Challengers Bangalore,Mumbai Indians,0,d padikkal,1,2,1,ta boult,1,0,2,2,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,AB de Villiers,Royal Challengers Bangalore,NaN,Mumbai Indians,field,Dubai International Cricket Stadium,Unknown,2020,Royal Challengers Bangalore,tie,NaN,Unknown,0,"('AJ Finch', 'D Padikkal')",202,201.0,1,0,0
187447,1216512,2020-10-18,1,Kolkata Knight Riders,Sunrisers Hyderabad,0,shubman gill,1,0,1,sandeep sharma,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,LH Ferguson,Kolkata Knight Riders,NaN,Sunrisers Hyderabad,field,Sheikh Zayed Stadium,Abu Dhabi,2020,Kolkata Knight Riders,tie,NaN,Unknown,0,"('RA Tripathi', 'Shubman Gill')",164,163.0,1,0,0
187698,1216517,2020-10-18,1,Mumbai Indians,Kings XI Punjab,0,rg sharma,1,1,1,gj maxwell,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,KL Rahul,Kings XI Punjab,NaN,Mumbai Indians,bat,Dubai International Cricket Stadium,Unknown,2020,Kings XI Punjab,tie,NaN,Unknown,0,"('Q de Kock', 'RG Sharma')",177,176.0,1,0,0
198245,1254077,2021-04-25,1,Delhi Capitals,Sunrisers Hyderabad,0,pp shaw,1,4,1,kk ahmed,1,0,4,4,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,PP Shaw,Delhi Capitals,NaN,Delhi Capitals,bat,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2021,Delhi Capitals,tie,NaN,Unknown,0,"('PP Shaw', 'S Dhawan')",160,159.0,1,0,1
236750,1359519,2023-05-03,1,Lucknow Super Giants,Chennai Super Kings,0,m vohra,1,1,1,dl chahar,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Chennai Super Kings,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,2023,NaN,no result,NaN,Unknown,0,"('KR Mayers', 'M Vohra')",126,0.0,1,0,0
268306,1473469,2025-04-16,1,Delhi Capitals,Rajasthan Royals,0,j fraser-mcgurk,1,0,1,jc archer,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MA Starc,Delhi Capitals,NaN,Rajasthan Royals,field,"Arun Jaitley Stadium, Delhi",Delhi,2025,Delhi Capitals,tie,NaN,Unknown,0,"('Abishek Porel', 'J Fraser-McGurk')",189,188.0,1,0,0
271126,1473481,2025-04-26,1,Punjab Kings,Kolkata Knight Riders,0,priyansh arya,1,4,1,vg arora,1,0,4,4,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Punjab Kings,bat,"Eden Gardens, Kolkata",Kolkata,2025,NaN,no result,NaN,Unknown,0,"('P Simran Singh', 'Priyansh Arya')",202,7.0,1,0,1
273705,1473492,2025-05-05,1,Delhi Capitals,Sunrisers Hyderabad,0,kk nair,1,0,1,pj cummins,1,0,0,0,False,no_extra_runs,caught,Ishan Kishan,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Sunrisers Hyderabad,field,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Hyderabad,2025,NaN,no result,NaN,Unknown,1,"('F du Plessis', 'KK Nair')",134,0.0,1,0,0
274316,1473495,2025-05-08,1,Punjab Kings,Delhi Capitals,0,priyansh arya,1,4,1,ma starc,1,0,4,4,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Unknown,NaN,NaN,Punjab Kings,bat,"Himachal Pradesh Cricket Association Stadium, ...",Dharamsala,2025,NaN,no result,NaN,Unknown,0,"('P Simran Singh', 'Priyansh Arya')",123,0.0,1,0,1

In [ ]:
clean_df['win_outcome'].fillna('tie',inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\1022529938.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_df['win_outcome'].fillna('tie',inplace=True)
C:\Users\karan\AppData\Local\Temp\ipykernel_2340\1022529938.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['win_outcome'].fillna('tie',inplace=True)

In [ ]:
clean_df['win_outcome'].value_counts()

win_outcome
6 wickets     127
7 wickets     122
5 wickets     102
8 wickets      87
4 wickets      62
9 wickets      50
3 wickets      32
tie            23
10 runs        18
10 wickets     17
14 runs        17
4 runs         16
12 runs        16
1 runs         15
18 runs        15
7 runs         15
20 runs        14
13 runs        14
23 runs        13
6 runs         13
2 runs         13
15 runs        13
37 runs        12
5 runs         12
9 runs         11
24 runs        11
2 wickets      11
27 runs        10
11 runs        10
34 runs         9
19 runs         9
25 runs         9
16 runs         9
22 runs         9
17 runs         9
3 runs          8
8 runs          7
21 runs         7
31 runs         7
38 runs         7
35 runs         6
33 runs         6
45 runs         6
41 runs         5
29 runs         5
55 runs         5
28 runs         5
32 runs         5
44 runs         5
39 runs         5
48 runs         5
46 runs         5
54 runs         5
1 wickets       5
59 runs         4
82 runs         4
50 runs         4
36 runs         4
57 runs         4
26 runs         4
78 runs         3
40 runs         3
86 runs         3
63 runs         3
60 runs         3
80 runs         3
97 runs         3
62 runs         3
30 runs         3
42 runs         3
67 runs         3
58 runs         3
61 runs         2
72 runs         2
71 runs         2
56 runs         2
65 runs         2
75 runs         2
92 runs         2
98 runs         2
49 runs         2
69 runs         2
77 runs         2
43 runs         2
81 runs         2
47 runs         2
85 runs         2
140 runs        1
53 runs         1
105 runs        1
66 runs         1
130 runs        1
76 runs         1
87 runs         1
111 runs        1
74 runs         1
146 runs        1
51 runs         1
138 runs        1
144 runs        1
93 runs         1
102 runs        1
118 runs        1
64 runs         1
91 runs         1
88 runs         1
52 runs         1
112 runs        1
106 runs        1
100 runs        1
83 runs         1
110 runs        1
Name: count, dtype: int64

In [ ]:
# 1. Extract the numeric values first as strings
# 2. Fill NaN with '0' so we can convert to int
# 3. Use np.where to assign them to the right columns

# Extract digits from 'win_outcome' (e.g., "8 wickets" -> "8")
extracted_nums = clean_df['win_outcome'].str.extract('(\d+)').fillna(0).astype(int)

# Apply the logic: only assign to 'wickets' column if 'wickets' is in the text
clean_df['won_by_wickets'] = np.where(clean_df['win_outcome'].str.contains('wickets', na=False), extracted_nums[0], 0)

# Only assign to 'runs' column if 'runs' is in the text
clean_df['won_by_runs'] = np.where(clean_df['win_outcome'].str.contains('runs', na=False), extracted_nums[0], 0)

# Handle Tie Matches
clean_df['tie_match'] = np.where(clean_df['win_outcome'].str.contains('tie|super over', case=False, na=False), 1, 0)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\848397612.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['won_by_wickets'] = np.where(clean_df['win_outcome'].str.contains('wickets', na=False), extracted_nums[0], 0)
C:\Users\karan\AppData\Local\Temp\ipykernel_2340\848397612.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['won_by_runs'] = np.where(clean_df['win_outcome'].str.contains('runs', na=False), extracted_nums[0], 0)
C:\Users\karan\AppData\Local\Temp\ipykernel_2340\848397612.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['tie_match'] = np.where(clean_df['win_outcome'].str.contains('tie|super over', case=False, na=False), 1, 0)

In [ ]:
clean_df.sample(3)

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs
153276,1136573,2018-04-16,1,Kolkata Knight Riders,Delhi Daredevils,0,ca lynn,1,0,1,ta boult,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,N Rana,Kolkata Knight Riders,71 runs,Delhi Daredevils,field,Eden Gardens,Kolkata,2018,NaN,NaN,NaN,Unknown,0,"('CA Lynn', 'SP Narine')",201,129.0,0,0,0,0,71
194106,1254060,2021-04-11,1,Kolkata Knight Riders,Sunrisers Hyderabad,0,n rana,1,4,1,b kumar,1,0,4,4,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,N Rana,Kolkata Knight Riders,10 runs,Sunrisers Hyderabad,field,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2021,NaN,NaN,NaN,Unknown,0,"('N Rana', 'Shubman Gill')",188,177.0,0,0,1,0,10
263771,1473450,2025-04-01,1,Lucknow Super Giants,Punjab Kings,0,ak markram,1,0,1,arshdeep singh,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,P Simran Singh,Punjab Kings,8 wickets,Punjab Kings,field,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,2025,NaN,NaN,NaN,Unknown,0,"('AK Markram', 'MR Marsh')",172,177.0,0,0,0,8,0

In [ ]:
clean_df['tie_match'].value_counts()

tie_match
0    1146
1      23
Name: count, dtype: int64

In [ ]:
train_df.iloc[:,23:].head()

,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s
0,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
1,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
2,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
3,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0
4,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0

TOSS WON BY :

In [ ]:
clean_df['toss_winner'].value_counts()

toss_winner
Mumbai Indians                 151
Kolkata Knight Riders          128
Chennai Super Kings            128
Rajasthan Royals               127
Royal Challengers Bangalore    113
Sunrisers Hyderabad             95
Kings XI Punjab                 85
Delhi Daredevils                80
Delhi Capitals                  58
Deccan Chargers                 43
Punjab Kings                    37
Gujarat Titans                  29
Lucknow Super Giants            24
Pune Warriors                   20
Gujarat Lions                   15
Royal Challengers Bengaluru     15
Kochi Tuskers Kerala             8
Rising Pune Supergiants          7
Rising Pune Supergiant           6
Name: count, dtype: int64

In [ ]:
clean_df['toss_decision'].value_counts()

toss_decision
field    764
bat      405
Name: count, dtype: int64

In [ ]:
clean_df.groupby('toss_winner')['toss_decision'].value_counts()

toss_winner                  toss_decision
Chennai Super Kings          field            68
                             bat              60
Deccan Chargers              bat              24
                             field            19
Delhi Capitals               field            45
                             bat              13
Delhi Daredevils             field            51
                             bat              29
Gujarat Lions                field            14
                             bat               1
Gujarat Titans               field            23
                             bat               6
Kings XI Punjab              field            58
                             bat              27
Kochi Tuskers Kerala         field             5
                             bat               3
Kolkata Knight Riders        field            88
                             bat              40
Lucknow Super Giants         field            17
                             bat               7
Mumbai Indians               field            97
                             bat              54
Pune Warriors                bat              11
                             field             9
Punjab Kings                 field            26
                             bat              11
Rajasthan Royals             field            83
                             bat              44
Rising Pune Supergiant       field             6
Rising Pune Supergiants      field             4
                             bat               3
Royal Challengers Bangalore  field            80
                             bat              33
Royal Challengers Bengaluru  field            13
                             bat               2
Sunrisers Hyderabad          field            58
                             bat              37
Name: count, dtype: int64

most of the toss won by the clubs have more chances of deciding to field than to bawl

In [ ]:
clean_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 153
Chennai Super Kings            142
Kolkata Knight Riders          136
Rajasthan Royals               116
Royal Challengers Bangalore    116
Sunrisers Hyderabad             94
Kings XI Punjab                 88
Delhi Daredevils                67
Delhi Capitals                  55
Gujarat Titans                  37
Punjab Kings                    34
Lucknow Super Giants            30
Deccan Chargers                 29
Royal Challengers Bengaluru     18
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [ ]:
clean_df[clean_df['match_won_by']=='Unknown'].head()

Empty DataFrame
Columns: [match_id, date, innings, batting_team, bowling_team, over, batter, bat_pos, runs_batter, balls_faced, bowler, valid_ball, runs_extras, runs_total, runs_bowler, runs_not_boundary, extra_type, wicket_kind, fielders, review_batter, team_reviewed, review_decision, umpire, umpires_call, player_of_match, match_won_by, win_outcome, toss_winner, toss_decision, venue, city, season, superover_winner, result_type, method, stage, bowler_wicket, batting_partners, target_score, chased_score, tie_match, 6s, 4s, won_by_wickets, won_by_runs]
Index: []

In [ ]:
clean_df['match_won_by']=np.where(clean_df['match_won_by']=='Unknown',clean_df['superover_winner'],clean_df['match_won_by'])

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\1770324491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['match_won_by']=np.where(clean_df['match_won_by']=='Unknown',clean_df['superover_winner'],clean_df['match_won_by'])

In [ ]:
clean_df['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 153
Chennai Super Kings            142
Kolkata Knight Riders          136
Rajasthan Royals               116
Royal Challengers Bangalore    116
Sunrisers Hyderabad             94
Kings XI Punjab                 88
Delhi Daredevils                67
Delhi Capitals                  55
Gujarat Titans                  37
Punjab Kings                    34
Lucknow Super Giants            30
Deccan Chargers                 29
Royal Challengers Bengaluru     18
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [ ]:
clean_df.groupby('toss_decision')['match_won_by'].value_counts()

toss_decision  match_won_by
bat            Chennai Super Kings            65
               Mumbai Indians                 55
               Kolkata Knight Riders          51
               Rajasthan Royals               43
               Royal Challengers Bangalore    37
               Sunrisers Hyderabad            32
               Delhi Daredevils               29
               Kings XI Punjab                24
               Delhi Capitals                 15
               Deccan Chargers                14
               Gujarat Titans                  9
               Pune Warriors                   9
               Lucknow Super Giants            7
               Punjab Kings                    7
               Gujarat Lions                   2
               Rising Pune Supergiants         2
               Royal Challengers Bengaluru     1
field          Mumbai Indians                 98
               Kolkata Knight Riders          85
               Royal Challengers Bangalore    79
               Chennai Super Kings            77
               Rajasthan Royals               73
               Kings XI Punjab                64
               Sunrisers Hyderabad            62
               Delhi Capitals                 40
               Delhi Daredevils               38
               Gujarat Titans                 28
               Punjab Kings                   27
               Lucknow Super Giants           23
               Royal Challengers Bengaluru    17
               Deccan Chargers                15
               Gujarat Lions                  11
               Rising Pune Supergiant         10
               Kochi Tuskers Kerala            6
               Pune Warriors                   3
               Rising Pune Supergiants         3
Name: count, dtype: int64

In [ ]:
clean_df.groupby('toss_winner')['match_won_by'].value_counts()

toss_winner                  match_won_by
Chennai Super Kings          Chennai Super Kings            78
                             Rajasthan Royals                8
                             Mumbai Indians                  7
                             Royal Challengers Bangalore     6
                             Kings XI Punjab                 5
                             Kolkata Knight Riders           5
                             Delhi Daredevils                4
                             Punjab Kings                    3
                             Royal Challengers Bengaluru     3
                             Delhi Capitals                  2
                             Gujarat Titans                  2
                             Sunrisers Hyderabad             2
                             Deccan Chargers                 1
                             Pune Warriors                   1
Deccan Chargers              Deccan Chargers                19
                             Delhi Daredevils                5
                             Mumbai Indians                  4
                             Kings XI Punjab                 3
                             Kolkata Knight Riders           3
                             Rajasthan Royals                3
                             Royal Challengers Bangalore     3
                             Chennai Super Kings             2
                             Pune Warriors                   1
Delhi Capitals               Delhi Capitals                 31
                             Mumbai Indians                  6
                             Chennai Super Kings             3
                             Kolkata Knight Riders           3
                             Rajasthan Royals                3
                             Royal Challengers Bangalore     3
                             Sunrisers Hyderabad             3
                             Kings XI Punjab                 2
                             Gujarat Titans                  1
                             Lucknow Super Giants            1
                             Punjab Kings                    1
                             Royal Challengers Bengaluru     1
Delhi Daredevils             Delhi Daredevils               35
                             Mumbai Indians                  9
                             Kings XI Punjab                 7
                             Rajasthan Royals                7
                             Chennai Super Kings             5
                             Kolkata Knight Riders           5
                             Royal Challengers Bangalore     5
                             Sunrisers Hyderabad             4
                             Gujarat Lions                   1
                             Pune Warriors                   1
Gujarat Lions                Gujarat Lions                  10
                             Kings XI Punjab                 2
                             Royal Challengers Bangalore     2
                             Mumbai Indians                  1
Gujarat Titans               Gujarat Titans                 19
                             Chennai Super Kings             2
                             Mumbai Indians                  2
                             Punjab Kings                    2
                             Delhi Capitals                  1
                             Kolkata Knight Riders           1
                             Lucknow Super Giants            1
                             Royal Challengers Bangalore     1
Kings XI Punjab              Kings XI Punjab                36
                             Kolkata Knight Riders           8
                             Sunrisers Hyderabad             8
                             Mumbai Indians                  7
                             Royal Challengers Bangalore     7
                             Rajasthan Royals                6
                             Chennai Super Kings             4
                             Delhi Daredevils                3
                             Deccan Chargers                 2
                             Pune Warriors                   2
                             Delhi Capitals                  1
                             Rising Pune Supergiants         1
Kochi Tuskers Kerala         Kochi Tuskers Kerala            4
                             Royal Challengers Bangalore     2
                             Deccan Chargers                 1
                             Pune Warriors                   1
Kolkata Knight Riders        Kolkata Knight Riders          71
                             Chennai Super Kings            11
                             Mumbai Indians                 10
                             Kings XI Punjab                 6
                             Sunrisers Hyderabad             6
                             Delhi Daredevils                5
                             Rajasthan Royals                5
                             Lucknow Super Giants            3
                             Royal Challengers Bangalore     3
                             Delhi Capitals                  2
                             Kochi Tuskers Kerala            2
                             Deccan Chargers                 1
                             Gujarat Titans                  1
                             Pune Warriors                   1
                             Punjab Kings                    1
Lucknow Super Giants         Lucknow Super Giants           13
                             Delhi Capitals                  2
                             Royal Challengers Bangalore     2
                             Chennai Super Kings             1
                             Gujarat Titans                  1
                             Kolkata Knight Riders           1
                             Mumbai Indians                  1
                             Punjab Kings                    1
                             Rajasthan Royals                1
                             Sunrisers Hyderabad             1
Mumbai Indians               Mumbai Indians                 83
                             Kings XI Punjab                10
                             Royal Challengers Bangalore     8
                             Sunrisers Hyderabad             7
                             Chennai Super Kings             6
                             Delhi Daredevils                6
                             Kolkata Knight Riders           6
                             Rajasthan Royals                6
                             Lucknow Super Giants            5
                             Gujarat Titans                  4
                             Delhi Capitals                  3
                             Punjab Kings                    2
                             Rising Pune Supergiant          2
                             Pune Warriors                   1
                             Rising Pune Supergiants         1
                             Royal Challengers Bengaluru     1
Pune Warriors                Royal Challengers Bangalore     4
                             Chennai Super Kings             3
                             Mumbai Indians                  3
                             Pune Warriors                   3
                             Delhi Daredevils                2
                             Rajasthan Royals                2
                             Sunrisers Hyderabad             2
                             Kings XI Punjab                 1
Punjab Kings                 Punjab Kings                   17
                             Sunrisers Hyderabad             4
                             Rajasthan Royals                3
                             Delhi Capitals                  2
                             Lucknow Super Giants            2
                             Royal Challengers Bengaluru     2
                             Chennai Super Kings             1
                             Gujarat Titans                  1
                             Kolkata Knight Riders           1
                             Mumbai Indians                  1
                             Royal Challengers Bangalore     1
Rajasthan Royals             Rajasthan Royals               62
                             Chennai Super Kings            12
                             Mumbai Indians                  8
                             Kolkata Knight Riders           7
                             Sunrisers Hyderabad             7
                             Delhi Capitals                  5
                             Kings XI Punjab                 5
                             Royal Challengers Bangalore     5
                             Gujarat Titans                  4
                             Delhi Daredevils                3
                             Punjab Kings                    3
                             Deccan Chargers                 1
                             Lucknow Super Giants            1
                             Pune Warriors                   1
                             Royal Challengers Bengaluru     1
Rising Pune Supergiant       Rising Pune Supergiant          5
                             Delhi Daredevils                1
Rising Pune Supergiants      Rising Pune Supergiants         3
                             Gujarat Lions                   1
                             Kings XI Punjab                 1
                             Kolkata Knight Riders           1
                             Royal Challengers Bangalore     1
Royal Challengers Bangalore  Royal Challengers Bangalore    57
                             Kolkata Knight Riders           9
                             Kings XI Punjab                 8
                             Sunrisers Hyderabad             7
                             Chennai Super Kings             6
                             Mumbai Indians                  6
                             Deccan Chargers                 4
                             Rajasthan Royals                4
                             Delhi Daredevils                3
                             Delhi Capitals                  2
                             Punjab Kings                    2
                             Rising Pune Supergiant          2
                             Gujarat Lions                   1
                             Gujarat Titans                  1
Royal Challengers Bengaluru  Royal Challengers Bengaluru    10
                             Sunrisers Hyderabad             2
                             Chennai Super Kings             1
                             Kolkata Knight Riders           1
                             Lucknow Super Giants            1
Sunrisers Hyderabad          Sunrisers Hyderabad            41
                             Kolkata Knight Riders          14
                             Chennai Super Kings             7
                             Rajasthan Royals                6
                             Royal Challengers Bangalore     6
                             Mumbai Indians                  5
                             Delhi Capitals                  4
                             Gujarat Titans                  3
                             Lucknow Super Giants            3
                             Kings XI Punjab                 2
                             Punjab Kings                    2
                             Rising Pune Supergiant          1
Name: count, dtype: int64

there is a huge diffrence relation in between the toss winner and the match winner .in very data the club who won the toss have much higher change to win the match

have removed the unknow values from the match won

In [ ]:
clean_df.head(4)

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0,0,140
225,335983,2008-04-19,1,Chennai Super Kings,Kings XI Punjab,0,pa patel,1,0,1,b lee,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,"Punjab Cricket Association Stadium, Mohali",Chandigarh,2008,NaN,NaN,NaN,Unknown,0,"('ML Hayden', 'PA Patel')",241,207.0,0,0,0,0,33
473,335984,2008-04-19,1,Rajasthan Royals,Delhi Daredevils,0,t kohli,1,0,1,gd mcgrath,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,Feroz Shah Kotla,Delhi,2008,NaN,NaN,NaN,Unknown,0,"('T Kohli', 'YK Pathan')",130,132.0,0,0,0,9,0
692,335985,2008-04-20,1,Mumbai Indians,Royal Challengers Bangalore,0,l ronchi,1,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,Wankhede Stadium,Mumbai,2008,NaN,NaN,NaN,Unknown,0,"('L Ronchi', 'ST Jayasuriya')",166,166.0,0,0,0,5,0

In [ ]:
clean_df['venue'].value_counts()

venue
Eden Gardens                                                               77
Wankhede Stadium                                                           73
M Chinnaswamy Stadium                                                      65
Feroz Shah Kotla                                                           60
Wankhede Stadium, Mumbai                                                   52
Rajiv Gandhi International Stadium, Uppal                                  49
MA Chidambaram Stadium, Chepauk                                            48
Sawai Mansingh Stadium                                                     47
Dubai International Cricket Stadium                                        46
Punjab Cricket Association Stadium, Mohali                                 35
MA Chidambaram Stadium, Chepauk, Chennai                                   34
Narendra Modi Stadium, Ahmedabad                                           33
Sheikh Zayed Stadium                                                       29
Sharjah Cricket Stadium                                                    28
Arun Jaitley Stadium, Delhi                                                23
Eden Gardens, Kolkata                                                      23
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow      22
Maharashtra Cricket Association Stadium                                    22
Dr DY Patil Sports Academy, Mumbai                                         20
Rajiv Gandhi International Stadium, Uppal, Hyderabad                       19
M Chinnaswamy Stadium, Bengaluru                                           19
Sawai Mansingh Stadium, Jaipur                                             17
Dr DY Patil Sports Academy                                                 17
Brabourne Stadium, Mumbai                                                  17
Subrata Roy Sahara Stadium                                                 16
Kingsmead                                                                  15
Rajiv Gandhi International Stadium                                         15
M.Chinnaswamy Stadium                                                      15
Arun Jaitley Stadium                                                       14
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                        13
Maharashtra Cricket Association Stadium, Pune                              13
SuperSport Park                                                            12
Sardar Patel Stadium, Motera                                               12
Punjab Cricket Association IS Bindra Stadium, Mohali                       11
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur         10
Punjab Cricket Association IS Bindra Stadium                               10
Saurashtra Cricket Association Stadium                                     10
Brabourne Stadium                                                          10
Himachal Pradesh Cricket Association Stadium                                9
MA Chidambaram Stadium                                                      9
Holkar Cricket Stadium                                                      9
New Wanderers Stadium                                                       8
Zayed Cricket Stadium, Abu Dhabi                                            8
JSCA International Stadium Complex                                          7
Barabati Stadium                                                            7
Newlands                                                                    7
St George's Park                                                            7
Himachal Pradesh Cricket Association Stadium, Dharamsala                    6
Shaheed Veer Narayan Singh International Stadium                            6
Nehru Stadium                                                               5
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh            5
Barsapara Cricket Stadium, Guwahati                                         5
Green Park                                                                  4
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam          4
Buffalo Park                                                                3
De Beers Diamond Oval                                                       3
Vidarbha Cricket Association Stadium, Jamtha                                3
OUTsurance Oval                                                             2
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh     1
Name: count, dtype: int64

there are some stadium name which have appered twice and thrice in the data witht the location of the stadium so in order to sort thode weneed to split the data on the basis of , and lower the value

In [ ]:
clean_df['venue'][225].split(',')[0]

'Punjab Cricket Association Stadium'

In [ ]:
# Use [0] to access the first element of the list after splitting
clean_df['venue'] = clean_df['venue'].apply(lambda x: x.split(',')[0].strip().lower()if pd.notnull(x) else x)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\4220076717.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['venue'] = clean_df['venue'].apply(lambda x: x.split(',')[0].strip().lower()if pd.notnull(x) else x)

In [ ]:
clean_df['venue'].value_counts()

venue
wankhede stadium                                                125
eden gardens                                                    100
ma chidambaram stadium                                           91
m chinnaswamy stadium                                            84
rajiv gandhi international stadium                               83
sawai mansingh stadium                                           64
feroz shah kotla                                                 60
dubai international cricket stadium                              46
arun jaitley stadium                                             37
dr dy patil sports academy                                       37
maharashtra cricket association stadium                          35
punjab cricket association stadium                               35
narendra modi stadium                                            33
sheikh zayed stadium                                             29
sharjah cricket stadium                                          28
brabourne stadium                                                27
punjab cricket association is bindra stadium                     26
bharat ratna shri atal bihari vajpayee ekana cricket stadium     22
dr. y.s. rajasekhara reddy aca-vdca cricket stadium              17
subrata roy sahara stadium                                       16
himachal pradesh cricket association stadium                     15
kingsmead                                                        15
m.chinnaswamy stadium                                            15
supersport park                                                  12
sardar patel stadium                                             12
maharaja yadavindra singh international cricket stadium          11
saurashtra cricket association stadium                           10
holkar cricket stadium                                            9
new wanderers stadium                                             8
zayed cricket stadium                                             8
newlands                                                          7
jsca international stadium complex                                7
barabati stadium                                                  7
st george's park                                                  7
shaheed veer narayan singh international stadium                  6
nehru stadium                                                     5
barsapara cricket stadium                                         5
green park                                                        4
de beers diamond oval                                             3
vidarbha cricket association stadium                              3
buffalo park                                                      3
outsurance oval                                                   2
Name: count, dtype: int64

In [ ]:
stadium_map = {
    'm.chinnaswamy stadium': 'm chinnaswamy stadium',
    'feroz shah kotla': 'arun jaitley stadium',
    'zayed cricket stadium': 'sheikh zayed stadium',
    'punjab cricket association is bindra stadium': 'punjab cricket association stadium',
    'sardar patel stadium': 'narendra modi stadium',
    'subrata roy sahara stadium': 'maharashtra cricket association stadium'
}

# Apply the mapping
clean_df['venue'] = clean_df['venue'].replace(stadium_map)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\2973552453.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['venue'] = clean_df['venue'].replace(stadium_map)

In [ ]:
clean_df['venue'].value_counts()

venue
wankhede stadium                                                125
eden gardens                                                    100
m chinnaswamy stadium                                            99
arun jaitley stadium                                             97
ma chidambaram stadium                                           91
rajiv gandhi international stadium                               83
sawai mansingh stadium                                           64
punjab cricket association stadium                               61
maharashtra cricket association stadium                          51
dubai international cricket stadium                              46
narendra modi stadium                                            45
dr dy patil sports academy                                       37
sheikh zayed stadium                                             37
sharjah cricket stadium                                          28
brabourne stadium                                                27
bharat ratna shri atal bihari vajpayee ekana cricket stadium     22
dr. y.s. rajasekhara reddy aca-vdca cricket stadium              17
himachal pradesh cricket association stadium                     15
kingsmead                                                        15
supersport park                                                  12
maharaja yadavindra singh international cricket stadium          11
saurashtra cricket association stadium                           10
holkar cricket stadium                                            9
new wanderers stadium                                             8
newlands                                                          7
st george's park                                                  7
jsca international stadium complex                                7
barabati stadium                                                  7
shaheed veer narayan singh international stadium                  6
barsapara cricket stadium                                         5
nehru stadium                                                     5
green park                                                        4
buffalo park                                                      3
de beers diamond oval                                             3
vidarbha cricket association stadium                              3
outsurance oval                                                   2
Name: count, dtype: int64

In [ ]:
clean_df.sample()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs
48712,501229,2011-04-27,1,Deccan Chargers,Kochi Tuskers Kerala,0,s sohal,1,1,1,rp singh,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,I Sharma,Deccan Chargers,55 runs,Kochi Tuskers Kerala,field,nehru stadium,Kochi,2011,NaN,NaN,NaN,Unknown,0,"('S Dhawan', 'S Sohal')",130,74.0,0,0,0,0,55

In [ ]:
clean_df['batting_team'].value_counts()

batting_team
Mumbai Indians                 143
Chennai Super Kings            136
Kolkata Knight Riders          126
Royal Challengers Bangalore    121
Rajasthan Royals               107
Sunrisers Hyderabad            102
Kings XI Punjab                 97
Delhi Daredevils                72
Delhi Capitals                  47
Deccan Chargers                 43
Punjab Kings                    42
Lucknow Super Giants            33
Gujarat Titans                  27
Pune Warriors                   20
Royal Challengers Bengaluru     17
Gujarat Lions                   14
Rising Pune Supergiant           8
Kochi Tuskers Kerala             7
Rising Pune Supergiants          7
Name: count, dtype: int64

In [ ]:
clean_df['venue'].unique()

array(['m chinnaswamy stadium', 'punjab cricket association stadium',
       'arun jaitley stadium', 'wankhede stadium', 'eden gardens',
       'sawai mansingh stadium', 'rajiv gandhi international stadium',
       'ma chidambaram stadium', 'dr dy patil sports academy', 'newlands',
       "st george's park", 'kingsmead', 'supersport park', 'buffalo park',
       'new wanderers stadium', 'de beers diamond oval',
       'outsurance oval', 'brabourne stadium', 'narendra modi stadium',
       'barabati stadium', 'vidarbha cricket association stadium',
       'himachal pradesh cricket association stadium', 'nehru stadium',
       'holkar cricket stadium',
       'dr. y.s. rajasekhara reddy aca-vdca cricket stadium',
       'maharashtra cricket association stadium',
       'shaheed veer narayan singh international stadium',
       'jsca international stadium complex', 'sheikh zayed stadium',
       'sharjah cricket stadium', 'dubai international cricket stadium',
       'saurashtra cricket association stadium', 'green park',
       'bharat ratna shri atal bihari vajpayee ekana cricket stadium',
       'barsapara cricket stadium',
       'maharaja yadavindra singh international cricket stadium'],
      dtype=object)

In [ ]:
#  home ground of the clubs
# Map the stadium names (cleaned) to the Team that calls it home
venue_to_team = {
    'wankhede stadium': 'Mumbai Indians',
    'eden gardens': 'Kolkata Knight Riders',
    'ma chidambaram stadium': 'Chennai Super Kings',
    'm chinnaswamy stadium': 'Royal Challengers Bangalore',
    'arun jaitley stadium': 'Delhi Capitals',
    'rajiv gandhi international stadium': 'Sunrisers Hyderabad',
    'sawai mansingh stadium': 'Rajasthan Royals',
    'narendra modi stadium': 'Gujarat Titans',
    'ekana cricket stadium': 'Lucknow Super Giants',
    'punjab cricket association stadium': 'Punjab Kings',
    'maharaja yadavindra singh international cricket stadium': 'Punjab Kings',
    'himachal pradesh cricket association stadium': 'Punjab Kings'
}

# Create the home_team column based on the venue
clean_df['venue_home_team'] = clean_df['venue'].map(venue_to_team)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\280842960.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['venue_home_team'] = clean_df['venue'].map(venue_to_team)

In [ ]:
clean_df['venue_home_team'].head()

0      Royal Challengers Bangalore
225                   Punjab Kings
473                 Delhi Capitals
692                 Mumbai Indians
938          Kolkata Knight Riders
Name: venue_home_team, dtype: object

In [ ]:
clean_df['venue'].isnull().sum()

np.int64(0)

In [ ]:
# A 'Home Win' occurs if the winner matches the venue's home team
clean_df['is_home_win'] = (clean_df['match_won_by'] == clean_df['venue_home_team']).astype(int)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\1349526132.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['is_home_win'] = (clean_df['match_won_by'] == clean_df['venue_home_team']).astype(int)

In [ ]:
clean_df['is_home_win'].value_counts()

is_home_win
0    862
1    307
Name: count, dtype: int64

In [ ]:
clean_df[clean_df['is_home_win']==1].head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs,venue_home_team,is_home_win
938,335986,2008-04-20,1,Deccan Chargers,Kolkata Knight Riders,0,ac gilchrist,1,1,1,ab dinda,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,eden gardens,Kolkata,2008,NaN,NaN,NaN,Unknown,0,"('AC Gilchrist', 'Y Venugopal Rao')",111,112.0,0,0,0,5,0,Kolkata Knight Riders,1
1178,335987,2008-04-21,1,Kings XI Punjab,Rajasthan Royals,0,k goel,1,0,1,mm patel,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,SR Watson,Rajasthan Royals,6 wickets,Kings XI Punjab,bat,sawai mansingh stadium,Jaipur,2008,NaN,NaN,NaN,Unknown,0,"('JR Hopes', 'K Goel')",167,168.0,0,0,0,6,0,Rajasthan Royals,1
1624,335989,2008-04-23,1,Chennai Super Kings,Mumbai Indians,0,pa patel,1,0,0,sm pollock,0,1,1,1,False,wides,not out,NaN,NaN,NaN,NaN,NaN,False,ML Hayden,Chennai Super Kings,6 runs,Mumbai Indians,field,ma chidambaram stadium,Chennai,2008,NaN,NaN,NaN,Unknown,0,"('ML Hayden', 'PA Patel')",209,202.0,0,0,0,0,6,Chennai Super Kings,1
2606,335993,2008-04-26,1,Kolkata Knight Riders,Chennai Super Kings,0,sc ganguly,1,2,1,jdp oram,1,0,2,2,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,JDP Oram,Chennai Super Kings,9 wickets,Kolkata Knight Riders,bat,ma chidambaram stadium,Chennai,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",148,152.0,0,0,0,9,0,Chennai Super Kings,1
4261,336000,2008-05-01,1,Rajasthan Royals,Kolkata Knight Riders,0,gc smith,1,0,1,ab dinda,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,SA Asnodkar,Rajasthan Royals,45 runs,Rajasthan Royals,bat,sawai mansingh stadium,Jaipur,2008,NaN,NaN,NaN,Unknown,0,"('GC Smith', 'SA Asnodkar')",197,151.0,0,0,0,0,45,Rajasthan Royals,1

# dominatin_df

In [ ]:
match_won_athome=clean_df[clean_df['is_home_win']==1]
dominated_athome=(clean_df[~(clean_df['is_home_win']==1)])

In [ ]:
match_won_athome.shape

(307, 47)

In [ ]:
match_won_athome['batting_team'].value_counts()

batting_team
Kolkata Knight Riders          46
Chennai Super Kings            46
Mumbai Indians                 41
Royal Challengers Bangalore    35
Sunrisers Hyderabad            32
Rajasthan Royals               30
Kings XI Punjab                15
Delhi Daredevils               12
Gujarat Titans                 10
Delhi Capitals                 10
Punjab Kings                    8
Deccan Chargers                 5
Gujarat Lions                   4
Pune Warriors                   4
Royal Challengers Bengaluru     3
Kochi Tuskers Kerala            2
Rising Pune Supergiants         2
Lucknow Super Giants            2
Name: count, dtype: int64

In [ ]:
dominated_athome['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 96
Chennai Super Kings            91
Kings XI Punjab                88
Kolkata Knight Riders          82
Rajasthan Royals               78
Royal Challengers Bangalore    76
Delhi Daredevils               67
Sunrisers Hyderabad            56
Delhi Capitals                 44
Lucknow Super Giants           30
Deccan Chargers                29
Punjab Kings                   29
Gujarat Titans                 24
Royal Challengers Bengaluru    18
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [ ]:
match_won_athome['match_won_by'].value_counts()

match_won_by
Mumbai Indians                 57
Kolkata Knight Riders          54
Chennai Super Kings            51
Royal Challengers Bangalore    40
Rajasthan Royals               38
Sunrisers Hyderabad            38
Gujarat Titans                 13
Delhi Capitals                 11
Punjab Kings                    5
Name: count, dtype: int64

In [ ]:
clean_df.sample(2)

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs,venue_home_team,is_home_win
6368,336009,2008-05-08,1,Delhi Daredevils,Chennai Super Kings,0,g gambhir,1,0,1,ms gony,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MS Dhoni,Chennai Super Kings,4 wickets,Chennai Super Kings,field,arun jaitley stadium,Delhi,2008,NaN,NaN,NaN,Unknown,0,"('G Gambhir', 'V Sehwag')",188,188.0,0,0,0,4,0,Delhi Capitals,0
692,335985,2008-04-20,1,Mumbai Indians,Royal Challengers Bangalore,0,l ronchi,1,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,wankhede stadium,Mumbai,2008,NaN,NaN,NaN,Unknown,0,"('L Ronchi', 'ST Jayasuriya')",166,166.0,0,0,0,5,0,Mumbai Indians,0

In [ ]:
clean_df['city'].isnull().sum()

np.int64(0)

In [ ]:
clean_df['city'].value_counts()

city
Mumbai            180
Kolkata           100
Delhi              97
Chennai            91
Hyderabad          83
Bangalore          65
Jaipur             64
Chandigarh         61
Unknown            51
Pune               51
Ahmedabad          45
Abu Dhabi          37
Bengaluru          34
Lucknow            22
Visakhapatnam      17
Durban             15
Dharamsala         15
Dubai              13
Centurion          12
Rajkot             10
Sharjah            10
Indore              9
Mohali              9
Navi Mumbai         9
Johannesburg        8
Ranchi              7
Port Elizabeth      7
Cuttack             7
Cape Town           7
Raipur              6
Kochi               5
Guwahati            5
Kanpur              4
East London         3
Kimberley           3
Nagpur              3
Bloemfontein        2
New Chandigarh      2
Name: count, dtype: int64

In [ ]:
clean_df[clean_df['city']=='Unknown'].head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs,venue_home_team,is_home_win
94795,729281,2014-04-17,1,Delhi Daredevils,Royal Challengers Bangalore,0,ma agarwal,1,0,1,ma starc,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,YS Chahal,Royal Challengers Bangalore,8 wickets,Royal Challengers Bangalore,field,sharjah cricket stadium,Unknown,2014,NaN,NaN,NaN,Unknown,0,"('M Vijay', 'MA Agarwal')",146,146.0,0,0,0,8,0,NaN,0
95515,729287,2014-04-19,1,Mumbai Indians,Royal Challengers Bangalore,0,mek hussey,1,1,1,ma starc,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,PA Patel,Royal Challengers Bangalore,7 wickets,Royal Challengers Bangalore,field,dubai international cricket stadium,Unknown,2014,NaN,NaN,NaN,Unknown,0,"('AP Tare', 'MEK Hussey')",116,116.0,0,0,0,7,0,NaN,0
95745,729289,2014-04-19,1,Kolkata Knight Riders,Delhi Daredevils,0,jh kallis,1,0,0,mohammed shami,0,1,1,1,False,wides,not out,NaN,NaN,NaN,NaN,NaN,False,JP Duminy,Delhi Daredevils,4 wickets,Kolkata Knight Riders,bat,dubai international cricket stadium,Unknown,2014,NaN,NaN,NaN,Unknown,0,"('G Gambhir', 'JH Kallis')",167,167.0,0,0,0,4,0,NaN,0
95994,729291,2014-04-20,1,Rajasthan Royals,Kings XI Punjab,0,am nayar,1,0,1,ar patel,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,GJ Maxwell,Kings XI Punjab,7 wickets,Kings XI Punjab,field,sharjah cricket stadium,Unknown,2014,NaN,NaN,NaN,Unknown,0,"('AM Nayar', 'AM Rahane')",192,193.0,0,0,0,7,0,NaN,0
96452,729295,2014-04-22,1,Kings XI Punjab,Sunrisers Hyderabad,0,ca pujara,1,1,1,dw steyn,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,GJ Maxwell,Kings XI Punjab,72 runs,Sunrisers Hyderabad,field,sharjah cricket stadium,Unknown,2014,NaN,NaN,NaN,Unknown,0,"('CA Pujara', 'V Sehwag')",194,121.0,0,0,0,0,72,NaN,0

In [ ]:
# Added the 'n' to 'Unknown' and handled potential case issues
clean_df['city'] = clean_df['city'].str.replace('Unknown', 'Uae', case=False).str.lower()

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\3113807568.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['city'] = clean_df['city'].str.replace('Unknown', 'Uae', case=False).str.lower()

In [ ]:
clean_df['city'].value_counts()

city
mumbai            180
kolkata           100
delhi              97
chennai            91
hyderabad          83
bangalore          65
jaipur             64
chandigarh         61
uae                51
pune               51
ahmedabad          45
abu dhabi          37
bengaluru          34
lucknow            22
visakhapatnam      17
durban             15
dharamsala         15
dubai              13
centurion          12
rajkot             10
sharjah            10
indore              9
mohali              9
navi mumbai         9
johannesburg        8
ranchi              7
port elizabeth      7
cuttack             7
cape town           7
raipur              6
kochi               5
guwahati            5
kanpur              4
east london         3
kimberley           3
nagpur              3
bloemfontein        2
new chandigarh      2
Name: count, dtype: int64

In [ ]:
clean_df.head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs,venue_home_team,is_home_win
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,m chinnaswamy stadium,bangalore,2008,NaN,NaN,NaN,Unknown,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0,0,140,Royal Challengers Bangalore,0
225,335983,2008-04-19,1,Chennai Super Kings,Kings XI Punjab,0,pa patel,1,0,1,b lee,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,punjab cricket association stadium,chandigarh,2008,NaN,NaN,NaN,Unknown,0,"('ML Hayden', 'PA Patel')",241,207.0,0,0,0,0,33,Punjab Kings,0
473,335984,2008-04-19,1,Rajasthan Royals,Delhi Daredevils,0,t kohli,1,0,1,gd mcgrath,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,arun jaitley stadium,delhi,2008,NaN,NaN,NaN,Unknown,0,"('T Kohli', 'YK Pathan')",130,132.0,0,0,0,9,0,Delhi Capitals,0
692,335985,2008-04-20,1,Mumbai Indians,Royal Challengers Bangalore,0,l ronchi,1,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,wankhede stadium,mumbai,2008,NaN,NaN,NaN,Unknown,0,"('L Ronchi', 'ST Jayasuriya')",166,166.0,0,0,0,5,0,Mumbai Indians,0
938,335986,2008-04-20,1,Deccan Chargers,Kolkata Knight Riders,0,ac gilchrist,1,1,1,ab dinda,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,eden gardens,kolkata,2008,NaN,NaN,NaN,Unknown,0,"('AC Gilchrist', 'Y Venugopal Rao')",111,112.0,0,0,0,5,0,Kolkata Knight Riders,1

day,month,year  gender team type

In [ ]:
clean_df['season'].value_counts()

season
2013    76
2012    74
2022    74
2023    74
2025    74
2011    73
2024    71
2020    60
2021    60
2010    60
2019    60
2018    60
2016    60
2014    60
2017    59
2015    59
2008    58
2009    57
Name: count, dtype: int64

replacing the season with the year columns as the season column contin some mising data errror

In [ ]:
clean_df['season'].value_counts().sort_index()

season
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
2018    60
2019    60
2020    60
2021    60
2022    74
2023    74
2024    71
2025    74
Name: count, dtype: int64

In [ ]:
clean_df.sample(5)

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs,venue_home_team,is_home_win
164260,1136619,2018-05-25,1,Sunrisers Hyderabad,Kolkata Knight Riders,0,wp saha,1,0,0,shivam mavi,0,1,1,1,False,wides,not out,NaN,NaN,NaN,NaN,NaN,False,Rashid Khan,Sunrisers Hyderabad,14 runs,Kolkata Knight Riders,field,eden gardens,kolkata,2018,NaN,NaN,NaN,Qualifier 2,0,"('S Dhawan', 'WP Saha')",175,160.0,0,0,0,0,14,Kolkata Knight Riders,0
56829,501264,2011-05-21,1,Deccan Chargers,Kings XI Punjab,0,s dhawan,1,1,1,p kumar,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,S Dhawan,Deccan Chargers,82 runs,Kings XI Punjab,field,himachal pradesh cricket association stadium,dharamsala,2011,NaN,NaN,NaN,Unknown,0,"('DB Ravi Teja', 'S Dhawan')",199,116.0,0,0,0,0,82,Punjab Kings,0
263996,1473451,2025-04-02,1,Royal Challengers Bengaluru,Gujarat Titans,0,pd salt,1,1,1,mohammed siraj,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,Mohammed Siraj,Gujarat Titans,8 wickets,Gujarat Titans,field,m chinnaswamy stadium,bengaluru,2025,NaN,NaN,NaN,Unknown,0,"('PD Salt', 'V Kohli')",170,170.0,0,0,0,8,0,Royal Challengers Bangalore,0
235746,1359515,2023-04-30,1,Chennai Super Kings,Punjab Kings,0,rd gaikwad,1,0,0,arshdeep singh,0,1,1,1,False,wides,not out,NaN,NaN,NaN,NaN,NaN,False,DP Conway,Punjab Kings,4 wickets,Chennai Super Kings,bat,ma chidambaram stadium,chennai,2023,NaN,NaN,NaN,Unknown,0,"('DP Conway', 'RD Gaikwad')",201,201.0,0,0,0,4,0,Chennai Super Kings,0
163519,1136616,2018-05-20,1,Kings XI Punjab,Chennai Super Kings,0,kl rahul,1,0,1,dl chahar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,L Ngidi,Chennai Super Kings,5 wickets,Chennai Super Kings,field,maharashtra cricket association stadium,pune,2018,NaN,NaN,NaN,Unknown,0,"('CH Gayle', 'KL Rahul')",154,159.0,0,0,0,5,0,NaN,0

In [ ]:
clean_df['stage'].replace('Unknown','simple matches',inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_2340\351399278.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_df['stage'].replace('Unknown','simple matches',inplace=True)
C:\Users\karan\AppData\Local\Temp\ipykernel_2340\351399278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['stage'].replace('Unknown','simple matches',inplace=True)

In [ ]:
clean_df.head()

,match_id,date,innings,batting_team,bowling_team,over,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,wicket_kind,fielders,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,bowler_wicket,batting_partners,target_score,chased_score,tie_match,6s,4s,won_by_wickets,won_by_runs,venue_home_team,is_home_win
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,not out,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,m chinnaswamy stadium,bangalore,2008,NaN,NaN,NaN,simple matches,0,"('BB McCullum', 'SC Ganguly')",223,82.0,0,0,0,0,140,Royal Challengers Bangalore,0
225,335983,2008-04-19,1,Chennai Super Kings,Kings XI Punjab,0,pa patel,1,0,1,b lee,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,punjab cricket association stadium,chandigarh,2008,NaN,NaN,NaN,simple matches,0,"('ML Hayden', 'PA Patel')",241,207.0,0,0,0,0,33,Punjab Kings,0
473,335984,2008-04-19,1,Rajasthan Royals,Delhi Daredevils,0,t kohli,1,0,1,gd mcgrath,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,arun jaitley stadium,delhi,2008,NaN,NaN,NaN,simple matches,0,"('T Kohli', 'YK Pathan')",130,132.0,0,0,0,9,0,Delhi Capitals,0
692,335985,2008-04-20,1,Mumbai Indians,Royal Challengers Bangalore,0,l ronchi,1,0,1,p kumar,1,0,0,0,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,wankhede stadium,mumbai,2008,NaN,NaN,NaN,simple matches,0,"('L Ronchi', 'ST Jayasuriya')",166,166.0,0,0,0,5,0,Mumbai Indians,0
938,335986,2008-04-20,1,Deccan Chargers,Kolkata Knight Riders,0,ac gilchrist,1,1,1,ab dinda,1,0,1,1,False,no_extra_runs,not out,NaN,NaN,NaN,NaN,NaN,False,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,eden gardens,kolkata,2008,NaN,NaN,NaN,simple matches,0,"('AC Gilchrist', 'Y Venugopal Rao')",111,112.0,0,0,0,5,0,Kolkata Knight Riders,1

In [ ]:
# droping the  team_runs as we will use tthe ball to ball data in this  same for team _balls ,witket,new batxh,bater runs,batter balls,nowller witcj
# batting partener, next batter, striker out .won by witker won by runs ti match ,

# clean_data

droping the columns which are not usefull fot the over all data  analysis such as tem runs and more we will us the ball to bal data for that purpose 
we are going to use the clean data for overall analyse of thedata

In [ ]:
clean_df.shape

(1169, 47)

In [ ]:
dropping_col = ['innings', 'over', 'ball_no', 'ball_no_in_over',
    'batter', 'bat_pos', 'runs_batter', 'balls_faced', 'non_striker', 'non_striker_pos',
    'bowler', 'valid_ball', 'runs_bowler', 'runs_extras', 'runs_total', 
    'runs_not_boundary', 'extra_type', 'wicket_kind', 'player_out', 'fielders',
    'runs_target', 'review_batter', 'team_reviewed', 'review_decision', 
    'umpire', 'umpires_call', 'balls_per_over', 'overs', 
    'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs', 
    'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter', 
    'striker_out', 'won_by_wickets', 'won_by_runs'
]

# Dropping and finalizing the team-focused view
team_analysis_df = clean_df.drop(columns=dropping_col, errors='ignore')

In [ ]:
# Keep only the first occurrence of each match to avoid duplicate records
team_analysis_df = team_analysis_df.drop_duplicates(subset=['season', 'date','batting_team', 'bowling_team'])

# Check the shape to see your total match count
print(f"Total Unique Matches: {team_analysis_df.shape[0]}")

Total Unique Matches: 1169

In [ ]:
team_analysis_df.head()

,match_id,date,batting_team,bowling_team,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,target_score,chased_score,tie_match,6s,4s,venue_home_team,is_home_win
0,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,m chinnaswamy stadium,bangalore,2008,NaN,NaN,NaN,simple matches,223,82.0,0,0,0,Royal Challengers Bangalore,0
225,335983,2008-04-19,Chennai Super Kings,Kings XI Punjab,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,punjab cricket association stadium,chandigarh,2008,NaN,NaN,NaN,simple matches,241,207.0,0,0,0,Punjab Kings,0
473,335984,2008-04-19,Rajasthan Royals,Delhi Daredevils,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,arun jaitley stadium,delhi,2008,NaN,NaN,NaN,simple matches,130,132.0,0,0,0,Delhi Capitals,0
692,335985,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,wankhede stadium,mumbai,2008,NaN,NaN,NaN,simple matches,166,166.0,0,0,0,Mumbai Indians,0
938,335986,2008-04-20,Deccan Chargers,Kolkata Knight Riders,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,eden gardens,kolkata,2008,NaN,NaN,NaN,simple matches,111,112.0,0,0,0,Kolkata Knight Riders,1

In [ ]:
team_analysis_df['superover_winner'].value_counts()

superover_winner
Delhi Capitals                 4
Kings XI Punjab                3
Rajasthan Royals               2
Mumbai Indians                 2
Royal Challengers Bangalore    2
Sunrisers Hyderabad            1
Kolkata Knight Riders          1
Name: count, dtype: int64

In [ ]:
team_analysis_df.fillna('no super over', inplace=True)

In [ ]:
team_analysis_df.head()

,match_id,date,batting_team,bowling_team,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,season,superover_winner,result_type,method,stage,target_score,chased_score,tie_match,6s,4s,venue_home_team,is_home_win
0,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,m chinnaswamy stadium,bangalore,2008,no super over,no super over,no super over,simple matches,223,82.0,0,0,0,Royal Challengers Bangalore,0
225,335983,2008-04-19,Chennai Super Kings,Kings XI Punjab,MEK Hussey,Chennai Super Kings,33 runs,Chennai Super Kings,bat,punjab cricket association stadium,chandigarh,2008,no super over,no super over,no super over,simple matches,241,207.0,0,0,0,Punjab Kings,0
473,335984,2008-04-19,Rajasthan Royals,Delhi Daredevils,MF Maharoof,Delhi Daredevils,9 wickets,Rajasthan Royals,bat,arun jaitley stadium,delhi,2008,no super over,no super over,no super over,simple matches,130,132.0,0,0,0,Delhi Capitals,0
692,335985,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,MV Boucher,Royal Challengers Bangalore,5 wickets,Mumbai Indians,bat,wankhede stadium,mumbai,2008,no super over,no super over,no super over,simple matches,166,166.0,0,0,0,Mumbai Indians,0
938,335986,2008-04-20,Deccan Chargers,Kolkata Knight Riders,DJ Hussey,Kolkata Knight Riders,5 wickets,Deccan Chargers,bat,eden gardens,kolkata,2008,no super over,no super over,no super over,simple matches,111,112.0,0,0,0,Kolkata Knight Riders,1

In [ ]:
team_analysis_df.shape

(1169, 23)

In [ ]:
team_analysis_df.to_csv('team_analysis_df.csv', index=False)