In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df=pd.read_csv("D:\ipl\IPL.csv")

C:\Users\karan\AppData\Local\Temp\ipykernel_20464\4278241017.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("D:\ipl\IPL.csv")

In [4]:
df.shape

(278205, 64)

In [5]:
df.tail(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,19.2,Shashank Singh,6,0,1,JR Hazlewood,1,0,0,0,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,19.3,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,19.4,Shashank Singh,6,4,1,JR Hazlewood,1,0,4,4,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,19.5,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,19.6,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

In [6]:
df['match_id'].nunique()

1169

1. the data is of 1169 ipl matches from 2008-2025
2. average matches per season is 69

In [7]:
df.isnull().sum()

Unnamed: 0                0
match_id                  0
date                      0
match_type                0
event_name                0
innings                   0
batting_team              0
bowling_team              0
over                      0
ball                      0
ball_no                   0
batter                    0
bat_pos                   0
runs_batter               0
balls_faced               0
bowler                    0
valid_ball                0
runs_extras               0
runs_total                0
runs_bowler               0
runs_not_boundary         0
extra_type           263072
non_striker               0
non_striker_pos           0
wicket_kind          264382
player_out           264382
fielders             268192
runs_target          144302
review_batter        277333
team_reviewed        277333
review_decision      277333
umpire               277333
umpires_call              0
player_of_match           0
match_won_by              0
win_outcome            4702
toss_winner               0
toss_decision             0
venue                     0
city                      0
day                       0
month                     0
year                      0
season                    0
gender                    0
team_type                 0
superover_winner     274309
result_type          273503
method               274315
balls_per_over            0
overs                     0
event_match_no            0
stage                     0
match_number              0
team_runs                 0
team_balls                0
team_wicket               0
new_batter           264884
batter_runs               0
batter_balls              0
bowler_wicket             0
batting_partners          0
next_batter          264884
striker_out               0
dtype: int64

there are plenty of missing value but most of them are maybe due to data error .we can resolve that using the map function

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  object
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), object(35)
memory usage: 130.3+ MB

In [9]:
df.duplicated().sum()

np.int64(0)

# data cleaning

In [10]:
train_df=df.copy()

In [11]:
train_df.tail()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,19.2,Shashank Singh,6,0,1,JR Hazlewood,1,0,0,0,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,19.3,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,19.4,Shashank Singh,6,4,1,JR Hazlewood,1,0,4,4,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,19.5,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,19.6,Shashank Singh,6,6,1,JR Hazlewood,1,0,6,6,False,NaN,KA Jamieson,9,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,False,KH Pandya,Royal Challengers Bengaluru,6 runs,Punjab Kings,field,"Narendra Modi Stadium, Ahmedabad",Ahmedabad,3,6,2025,2025,male,club,NaN,NaN,NaN,6,20,Unknown,Final,Unknown,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

droping the unnamed :0 ,match type, event name : as these are same for all the mathes.and  ipl are of 20 overs

In [12]:
train_df.drop(columns=['Unnamed: 0','match_type','event_name'],inplace=True)

In [13]:
train_df.head()

,match_id,date,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,2008-04-18,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

we are also deleting the date column as it is already extracted into day /month /year

In [14]:
train_df.drop('date',axis=1,inplace=True)

In [15]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

inning is defining the which club is playing first/bating  and which club is bowling

replacing the names of batting team into the sort form (example "Kolkata Knight Riders"-kkr) and so on

In [16]:
train_df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

some of the teams are have 2 value so we will convert these into lower case teams

In [17]:
train_df['batting_team'].nunique()

19

In [18]:
batting_dic={
            'Kolkata Knight Riders':'KKR',
            'Royal Challengers Bangalore':'RCB',
            'Chennai Super Kings':'CSK',
            'Kings XI Punjab':'KXP',
            'Rajasthan Royals':'RR',
            'Delhi Daredevils':'DC',
            'Mumbai Indians':'MI',
            'Deccan Chargers':'DEC',
            'Kochi Tuskers Kerala':'KTK',
            'Pune Warriors':"PW",
            'Sunrisers Hyderabad':'SRH',
            'Rising Pune Supergiants':'RPS',
            'Gujarat Lions':'GL',
            'Rising Pune Supergiant':'RPS',
            'Delhi Capitals':'DC',
            'Punjab Kings':'KXP',
            'Lucknow Super Giants':'LSG',
            'Gujarat Titans':'GT',
            'Royal Challengers Bengaluru':'RCB'}

In [19]:
# train_df.apply(lambda x : x .replace(batting_dic))
# this process can be slow so insted of using lamda we are going to use the replace function of pandas which is faster or the map function 
# Create a list of columns that contain team names
team_cols = ['batting_team', 'bowling_team'] 

# Option A: Using replace (Great for whole DataFrames or specific columns)
# Strip spaces and replace names for both columns efficiently
for col in team_cols:
    train_df[col] = train_df[col].str.strip().replace(batting_dic)# we added the strip fuction so that the there is no extrea space in
# the daataset which can cause problem in the future

In [20]:
train_df.head(8)

,match_id,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,1,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,2,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,3,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,3,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,4,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,335982,1,KKR,RCB,0,5,0.5,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
6,335982,1,KKR,RCB,0,6,0.6,BB McCullum,2,0,1,P Kumar,1,1,1,0,False,legbyes,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,6,0,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False
7,335982,1,KKR,RCB,1,1,1.1,BB McCullum,2,0,1,Z Khan,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,7,0,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [21]:
train_df[['match_id','ball','ball_no']].head(20)

    match_id  ball  ball_no
0     335982     1      0.1
1     335982     2      0.2
2     335982     3      0.3
3     335982     3      0.3
4     335982     4      0.4
5     335982     5      0.5
6     335982     6      0.6
7     335982     1      1.1
8     335982     2      1.2
9     335982     3      1.3
10    335982     4      1.4
11    335982     5      1.5
12    335982     6      1.6
13    335982     1      2.1
14    335982     2      2.2
15    335982     3      2.3
16    335982     4      2.4
17    335982     5      2.5
18    335982     6      2.6
19    335982     1      3.1

we dont need both ball and ball no so we are removingthe ball as the ball_no is same but better than ball

In [22]:
train_df.drop('ball',axis=1,inplace=True)

In [23]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,SC Ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,BB McCullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,BB McCullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

bat_pos define the order on which the batsman have enter the ground and contains 1-11 number a

In [24]:
train_df['bat_pos'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
# Group the data as you did
pos_stats = train_df.groupby(['batter', 'bat_pos'])['runs_batter'].sum().reset_index()

# Filter: Only show positions where the player has scored at least 30 runs
# This keeps your charts from looking cluttered with '1' or '0' run bars
pos_stats = pos_stats[pos_stats['runs_batter'] > 30]

In [26]:
pos_stats.head(10)

            batter  bat_pos  runs_batter
2   A Ashish Reddy        7          141
3   A Ashish Reddy        8           85
4   A Ashish Reddy        9           33
6         A Badoni        3           44
7         A Badoni        4           58
8         A Badoni        5          285
9         A Badoni        6          340
10        A Badoni        7          232
14        A Chopra        2           38
21      A Flintoff        5           38

In [27]:
train_df['batter']=train_df['batter'].apply(lambda x : x.lower())

runs_batter define the run made by the batsman in matches

In [28]:
train_df.groupby('batter')['runs_batter'].sum().sort_values(ascending=False).tail(500)

batter
y nagar                    285
gh vihari                  284
vvs laxman                 282
b chipli                   280
a ashish reddy             280
mj lumb                    278
jp inglis                  278
pbb rajapaksa              277
pk garg                    273
mj guptill                 271
hv patel                   270
r sathish                  270
jc archer                  262
atharva taide              260
m kaif                     259
jo holder                  259
v suryavanshi              252
k gowtham                  247
harpreet brar              244
sm katich                  241
a mhatre                   240
bcj cutting                238
md mishra                  237
aniket verma               236
mohammad nabi              221
k goel                     218
ramandeep singh            217
aa jhunjhunwala            217
k rabada                   215
r dhawan                   210
ut yadav                   208
ca ingram                  205
pd collingwood             203
kuldeep yadav              201
ks bharat                  199
sk warne                   198
jd unadkat                 197
sp fleming                 196
as raut                    194
bj rohrer                  193
salman butt                193
yv takawale                192
hc brook                   190
bipul sharma               187
r shepherd                 185
fy fazal                   183
sd hope                    183
ms wade                    183
sikandar raza              182
cr brathwaite              181
ac voges                   181
s gopal                    180
ab agarkar                 179
mf maharoof                177
c munro                    177
sameer rizvi               172
dh yagnik                  170
cm gautam                  169
dw steyn                   167
mn van wyk                 167
mg johnson                 167
pa reddy                   164
n jagadeesan               162
mn samuels                 161
re van der merwe           159
r mclaren                  159
ad hales                   148
d wiese                    148
sm pollock                 147
s vidyut                   145
sachin baby                144
v nigam                    142
m jansen                   141
n saini                    140
sb dubey                   139
anmolpreet singh           139
s anirudha                 136
sb styris                  131
w jaffer                   130
rd chahar                  129
kamran akmal               128
p dogra                    127
tk curran                  127
ut khawaja                 127
ss prabhudessai            126
m morkel                   126
bb samantray               125
mc juneja                  125
mm sharma                  125
b lee                      124
ab mcdonald                123
harpreet singh             123
dl vettori                 121
nk patel                   121
tg southee                 120
ac blizzard                120
arshad khan                119
rj harris                  117
mw short                   117
misbah-ul-haq              117
dl chahar                  117
z khan                     117
kk cooper                  116
aman hakim khan            115
djm short                  115
m kartik                   113
mohammed siraj             112
dj harris                  111
ma starc                   111
mj santner                 110
jdp oram                   106
lj wright                  106
ds kulkarni                104
rj quiney                  103
azmatullah omarzai          99
sd chitnis                  99
ms gony                     99
cj ferguson                 98
mj clarke                   98
pn mankad                   97
dj jacobs                   92
phkd mendis                 92
jds neesham                 92
pr shah                     92
rt ponting                  91
aj tye                      91
s rana                      91
ad nath                     90
iqbal abdulla               88
sl malinga                  88
ankit sharma                87
ap majumdar                 87
ta boult                    85
mj mcclenaghan              85
mohammed shami              84
re levi                     83
nm coulter-nile             82
pwh de silva                81
la carseldine               81
cj jordan                   81
shahid afridi               81
wpujc vaas                  81
rv patel                    80
ad mascarenhas              79
jr philippe                 78
cr woakes                   78
ir jaggi                    76
b akhil                     76
tr birt                     75
m klinger                   73
rr sarwan                   73
lh ferguson                 72
sk rasheed                  71
j suchith                   70
aa bilakhia                 69
vivrant sharma              69
urvil patel                 68
jj bumrah                   68
jg bethell                  67
rr powar                    67
r sharma                    66
hr shokeen                  66
wd parnell                  65
gd phillips                 65
ka jamieson                 65
mohammad hafeez             64
anirudh singh               63
a flintoff                  62
avesh khan                  62
sp jackson                  61
sandeep sharma              60
s aravind                   59
harshit rana                59
mg bracewell                58
i sharma                    57
wa mota                     56
vishnu vinod                56
m rawat                     55
a chopra                    53
dj willey                   53
pvd chameera                53
rp singh                    52
shoaib malik                52
r rampaul                   51
of smith                    51
swapnil singh               51
kb arun karthik             51
shivam mavi                 51
rv gomez                    50
vr aaron                    50
sb bangar                   49
a nortje                    49
ag paunikar                 49
as yadav                    49
m markande                  48
t kohler-cadmore            48
yashpal singh               47
c bosch                     47
ravi bishnoi                45
d pretorius                 44
dr sams                     44
sunny singh                 43
sk trivedi                  42
ab barath                   42
a nehra                     41
rasikh salam                40
lpc silva                   40
br dunk                     40
j yadav                     40
auk pathan                  39
s nadeem                    39
umar gul                    39
dj thornely                 39
mm patel                    39
ys chahal                   37
s narwal                    37
an ahmed                    36
sohail tanvir               36
kw richardson               36
l balaji                    36
anureet singh               36
joginder sharma             36
a kumble                    35
m ashwin                    35
b sumanth                   35
l ronchi                    34
ap dole                     34
a mithun                    34
s sreesanth                 34
d salunkhe                  33
imran tahir                 33
navdeep saini               33
at carey                    32
rj peterson                 32
basil thampi                32
arshdeep singh              31
t taibu                     31
g coetzee                   31
s sriram                    31
ns naik                     31
j syed mohammad             29
vh zol                      29
sb jakati                   28
tu deshpande                28
as joseph                   27
jm kemp                     26
as roy                      26
as rajpoot                  26
pj sangwan                  26
nl mccullum                 26
dj malan                    26
md shanaka                  26
tl seifert                  26
ab dinda                    26
cv varun                    26
sanvir singh                25
akash deep                  25
mohsin khan                 25
s chanderpaul               25
a choudhary                 25
er dwivedi                  24
aj turner                   24
tanush kotian               24
kc cariappa                 24
ma khote                    24
p dubey                     23
j arunkumar                 23
umran malik                 23
af milne                    23
bmaj mendis                 23
sw tait                     23
au rashid                   22
gb hogg                     22
sediqullah atal             22
sa abbott                   22
yudhvir singh               22
he van der dussen           22
kl nagarkoti                22
b indrajith                 21
de bollinger                21
s kaul                      20
ac thomas                   20
noor ahmad                  20
m muralitharan              20
bkg mendis                  20
c sakariya                  20
nj maddinson                20
rr raje                     20
p sahu                      19
p ray barman                19
y gnaneswara rao            19
r bishnoi                   19
nt ellis                    19
ra bawa                     19
dr martyn                   19
a mukund                    19
jr hazlewood                19
r shukla                    19
gulbadin naib               19
bj haddin                   18
naveen-ul-haq               18
t banton                    18
kma paul                    18
ds lehmann                  18
harmeet singh               18
sumit kumar                 18
saurav chauhan              18
r sai kishore               18
pv tambe                    18
jj van der wath             18
parvez rasool               17
m theekshana                17
ja richardson               17
aj hosein                   16
yv dhull                    16
a kamboj                    16
pp ojha                     16
ck kapugedera               16
ks sharma                   16
virat singh                 15
a zampa                     15
vy mahesh                   15
c madan                     15
i udana                     15
jl pattinson                15
gr napier                   15
sd lad                      15
j overton                   15
mdkj perera                 14
fa allen                    14
f behardien                 14
vijaykumar vyshak           14
mp breetzke                 14
arjun tendulkar             13
mustafizur rahman           13
dt patil                    13
dr shorey                   13
s badree                    13
kartik tyagi                13
kj abbott                   13
mujeeb ur rahman            12
t thushara                  12
daj bracewell               12
ma wood                     12
karanveer singh             12
dg nalkande                 12
ar bawne                    12
k kartikeya                 12
k upadhyay                  12
aa chavan                   12
xc bartlett                 11
t henderson                 11
m ntini                     11
t kohli                     11
dnt zoysa                   11
x thalaivan sargunam        10
td paine                    10
d du preez                  10
mukesh kumar                10
je root                     10
ag murtaza                  10
kaj roach                   10
smsm senanayake             10
simarjeet singh             10
j theron                    10
bb sran                     10
rk bhui                     10
m prasidh krishna            9
pwa mulder                   9
vg arora                     9
d ferreira                   9
aa kulkarni                  9
aa noffke                    9
sm harwood                   9
l wood                       9
akash madhwal                8
ts mills                     8
p chopra                     8
ck langeveldt                8
jpr scantlebury-searles      8
jaskaran singh               8
kt maphaka                   8
sh johnson                   8
tm srivastava                8
cj mckay                     8
oc mccoy                     8
suryansh shedge              7
ua birla                     7
vs malik                     7
i malhotra                   7
pankaj singh                 7
an ghosh                     7
ankit soni                   7
v viyaskanth                 7
is sodhi                     7
mukesh choudhary             6
ss shaikh                    6
sb joshi                     6
r minz                       6
dm bravo                     6
ba bhatt                     6
jp behrendorff               6
psp handscomb                6
sj srivastava                5
b stanlake                   5
b laughlin                   5
prince yadav                 5
p awana                      5
kmdn kulasekara              5
fazalhaq farooqi             5
shivam sharma                5
arshad khan (2)              5
vrv singh                    4
crd fernando                 4
gd mcgrath                   4
liton das                    4
rs sodhi                     4
fh edwards                   4
dp nannes                    4
a uniyal                     4
a tomar                      4
a dananjaya                  4
yash dayal                   4
a chandila                   4
younis khan                  3
baw mendis                   3
je taylor                    3
gc viljoen                   3
kumar kushagra               3
kamran khan                  3
mohammad asif                3
m tiwari                     3
rjw topley                   3
r ninan                      3
t natarajan                  3
s tyagi                      3
d kalyankrishna              3
kp appanna                   2
rs gavaskar                  2
kk ahmed                     2
vs yeligati                  2
br sharath                   2
s randiv                     2
sb wagh                      2
shivam singh                 2
shoaib akhtar                2
a singh                      2
t shamsi                     2
mohammad ashraful            2
mashrafe mortaza             2
rj gleeson                   2
rg more                      2
ghs garton                   2
h das                        2
abdul basith                 1
dj muthuswami                1
se bond                      1
shoaib ahmed                 1
dp vijaykumar                1
ds rathi                     1
m de lange                   1
mohit rathee                 1
mj suthar                    1
p parameswaran               1
sz mulani                    1
pvsn raju                    1
nj rimmington                1
ms bhandage                  1
hf gurney                    1
pm sarvesh kumar             1
le plunkett                  1
lb williams                  1
be hendricks                 1
ka maharaj                   1
y prithvi raj                0
ya abdulla                   0
sunny gupta                  0
ss cottrell                  0
rp meredith                  0
s lamichhane                 0
s kaushik                    0
rr bhatkal                   0
s ladda                      0
r sanjay yadav               0
u kaul                       0
mayank dagar                 0
mj owen                      0
musheer khan                 0
nd doshi                     0
l ngidi                      0
kr sen                       0
ks rathore                   0
v pratap singh               0
jl denly                     0
km asif                      0
k yadav                      0
l ablish                     0
ic pandey                    0
c nanda                      0
abdur razzak                 0
Name: runs_batter, dtype: int64

In [29]:
wide_balls=train_df[train_df['balls_faced']==0]

In [30]:
wide_balls['extra_type'].value_counts()

extra_type
wides             9079
penalty, wides       1
Name: count, dtype: int64

In [31]:
wide_balls[wide_balls['extra_type']!='wides'].head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
98231,729309,2,DC,MI,4,4.2,m vijay,2,0,0,SL Malinga,0,7,7,2,False,"penalty, wides",Q de Kock,1,NaN,NaN,NaN,126.0,NaN,NaN,NaN,NaN,False,M Vijay,Delhi Daredevils,6 wickets,Mumbai Indians,bat,Sharjah Cricket Stadium,Unknown,27,4,2014,2014,male,club,NaN,NaN,NaN,6,20,16,Unknown,Unknown,30,25,0,NaN,8,12,0,"('M Vijay', 'Q de Kock')",NaN,False

there is only 1 penalty ball so we can say the balled_faced into wide balls

In [32]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

ball faced

In [33]:
train_df['balls_faced'].nunique()

2

In [34]:
train_df.groupby('batter')['balls_faced'].sum().sort_values(ascending=False).head(10)

batter
v kohli       6523
rg sharma     5337
s dhawan      5326
da warner     4702
sk raina      4046
am rahane     4025
ms dhoni      3957
kl rahul      3848
rv uthappa    3801
kd karthik    3580
Name: balls_faced, dtype: int64

In [35]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,P Kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,P Kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,P Kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [36]:
train_df['bowler'].unique()

array(['P Kumar', 'Z Khan', 'AA Noffke', 'JH Kallis', 'SB Joshi',
       'CL White', 'AB Dinda', 'I Sharma', 'AB Agarkar', 'SC Ganguly',
       'LR Shukla', 'B Lee', 'S Sreesanth', 'JR Hopes', 'IK Pathan',
       'K Goel', 'PP Chawla', 'WA Mota', 'JDP Oram', 'MS Gony',
       'M Muralitharan', 'P Amarnath', 'Joginder Sharma', 'GD McGrath',
       'B Geeves', 'MF Maharoof', 'R Bhatia', 'DL Vettori', 'MM Patel',
       'SR Watson', 'SK Trivedi', 'SK Warne', 'YK Pathan', 'D Salunkhe',
       'R Vinay Kumar', 'B Akhil', 'A Nehra', 'SM Pollock', 'DS Kulkarni',
       'ST Jayasuriya', 'Harbhajan Singh', 'AM Nayar', 'M Kartik',
       'Mohammad Hafeez', 'DJ Hussey', 'WPUJC Vaas', 'RP Singh',
       'SB Styris', 'SB Bangar', 'A Symonds', 'PP Ojha', 'Pankaj Singh',
       'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi', 'DJ Bravo',
       'VS Yeligati', 'MA Khote', 'D Kalyankrishna', 'VRV Singh',
       'Sohail Tanvir', 'A Kumble', 'DNT Zoysa', 'SD Chitnis',
       'Yuvraj Singh', 'Shoaib Malik', 'DW Steyn', 'JA Morkel',
       'CRD Fernando', 'V Kohli', 'V Sehwag', 'Gagandeep Singh',
       'Y Venugopal Rao', 'Umar Gul', 'PJ Sangwan', 'M Ntini',
       'DP Vijaykumar', 'DJ Thornely', 'RR Raje', 'SK Raina', 'S Vidyut',
       'L Balaji', 'CK Kapugedera', 'AD Mascarenhas', 'A Mishra',
       'Shoaib Akhtar', 'Iqbal Abdulla', 'PM Sarvesh Kumar', 'RR Powar',
       'Abdur Razzak', 'RA Jadeja', 'TM Dilshan', 'DR Smith', 'RG Sharma',
       'A Nel', 'DB Ravi Teja', 'LPC Silva', 'BAW Mendis', 'T Thushara',
       'A Flintoff', 'SL Malinga', 'Kamran Khan', 'T Henderson',
       'JD Ryder', 'DP Nannes', 'AM Salvi', 'YA Abdulla', 'VS Malik',
       'FH Edwards', 'Harmeet Singh', 'CH Gayle', 'MC Henriques',
       'KP Pietersen', 'LRPL Taylor', 'RS Bopara', 'MK Tiwary',
       'Anureet Singh', 'RR Bose', 'KP Appanna', 'Shoaib Ahmed',
       'BJ Hodge', 'SR Tendulkar', 'RE van der Merwe', 'JP Duminy',
       'S Tyagi', 'GR Napier', 'SM Harwood', 'AS Raut', 'SB Jakati',
       'D du Preez', 'RJ Harris', 'TL Suman', 'A Singh', 'M Morkel',
       'LA Carseldine', 'A Mithun', 'C Nanda', 'SS Sarkar', 'AD Mathews',
       'AM Rahane', 'J Botha', 'Mashrafe Mortaza', 'AB McDonald',
       'Y Nagar', 'CK Langeveldt', 'R Ashwin', 'RA Shaikh',
       'Jaskaran Singh', 'SW Tait', 'A Uniyal', 'AA Jhunjhunwala',
       'R McLaren', 'AG Murtaza', 'R Sathish', 'RS Gavaskar', 'JM Kemp',
       'S Ladda', 'Bipul Sharma', 'SE Bond', 'KA Pollard', 'S Narwal',
       'UT Yadav', 'SJ Srivastava', 'AC Voges', 'R Sharma', 'J Theron',
       'NLTC Perera', 'KAJ Roach', 'PD Collingwood', 'C Ganapathy',
       'MB Parmar', 'SB Wagh', 'DE Bollinger', 'JD Unadkat', 'AP Dole',
       'AN Ahmed', 'FY Fazal', 'MR Marsh', 'L Ablish', 'S Sriram',
       'AJ Finch', 'STR Binny', 'ND Doshi', 'TG Southee', 'S Randiv',
       'AL Menaria', 'DT Christian', 'AUK Pathan', 'RV Gomez',
       'JEC Franklin', 'AC Thomas', 'WD Parnell', 'M Manhas',
       'NJ Rimmington', 'RN ten Doeschate', 'S Nadeem', 'BA Bhatt',
       'JJ van der Wath', 'S Aravind', 'R Ninan', 'Shakib Al Hasan',
       'PC Valthaty', 'S Dhawan', 'J Syed Mohammad', 'VR Aaron',
       'NL McCullum', 'JE Taylor', 'KMDN Kulasekara', 'P Parameswaran',
       'I Malhotra', 'B Chipli', 'B Kumar', 'AA Kazi', 'Anand Rajan',
       'P Prasanth', 'Y Gnaneswara Rao', 'AA Chavan', 'S Rana',
       'JP Faulkner', 'SS Mundhe', 'RW Price', 'GJ Maxwell', 'M de Lange',
       'MN Samuels', 'KK Cooper', 'DAJ Bracewell', 'HV Patel',
       'Ankit Sharma', 'DJ Harris', 'TP Sudhindra', 'F du Plessis',
       'SP Narine', 'GB Hogg', 'RR Bhatkal', 'P Awana', 'CJ McKay',
       'V Pratap Singh', 'Azhar Mahmood', 'A Chandila', 'P Negi',
       'LJ Wright', 'RJ Peterson', 'A Ashish Reddy', 'R Shukla',
       'MJ Clarke', 'BW Hilfenhaus', 'SPD Smith', 'AD Russell',
       'K Upadhyay', 'Sunny Gupta', 'MG Johnson', 'JJ Bumrah', 'S Badree',
       'AS Rajpoot', 'B Laughlin', 'GH Vihari', 'Mohammed Shami',
       'BMAJ Mendis', 'CH Morris', 'S Kaul', 'R Dhawan', 'MM Sharma',
       'R Rampaul', 'KV Sharma', 'SMSM Senanayake', 'JO Holder',
       'IC Pandey', 'YS Chahal', 'DJG Sammy', 'KW Richardson', 'P Suyal',
       'MG Neser', 'PV Tambe', 'BJ Rohrer', 'Parvez Rasool',
       'Sandeep Sharma', 'NM Coulter-Nile', 'AC Gilchrist', 'CJ Anderson',
       'MA Starc', 'JDS Neesham', 'AR Patel', 'M Vijay', 'R Tewatia',
       'SA Yadav', 'Shivam Sharma', 'Imran Tahir', 'V Shankar',
       'LMP Simmons', 'BCJ Cutting', 'K Santokie', 'S Gopal',
       'BE Hendricks', 'PJ Cummins', 'JW Hastings', 'Karanveer Singh',
       'DJ Muthuswami', 'TA Boult', 'SA Abbott', 'KC Cariappa',
       'DJ Hooda', 'J Suchith', 'D Wiese', 'MJ McClenaghan', 'HH Pandya',
       'RG More', 'SN Thakur', 'GS Sandhu', 'Gurkeerat Singh', 'J Yadav',
       'BB Sran', 'M Ashwin', 'C Munro', 'CR Brathwaite', 'MP Stoinis',
       'P Sahu', 'Mustafizur Rahman', 'AF Milne', 'Kuldeep Yadav',
       'KH Pandya', 'KJ Abbott', 'T Shamsi', 'S Kaushik', 'SM Boland',
       'Swapnil Singh', 'CJ Jordan', 'A Zampa', 'Sachin Baby', 'N Rana',
       'DL Chahar', 'KS Williamson', 'TS Mills', 'A Choudhary', 'TM Head',
       'Rashid Khan', 'BA Stokes', 'CR Woakes', 'T Natarajan',
       'RD Chahar', 'B Stanlake', 'Tejas Baroka', 'Basil Thampi',
       'C de Grandhomme', 'AJ Tye', 'LH Ferguson', 'Mohammad Nabi',
       'Mohammed Siraj', 'K Rabada', 'Washington Sundar', 'SS Agarwal',
       'NB Singh', 'RA Tripathi', 'Ankit Soni', 'MJ Henry', 'Avesh Khan',
       'MA Wood', 'M Markande', 'Mujeeb Ur Rahman', 'K Khejroliya',
       'K Gowtham', 'DJM Short', 'TK Curran', 'A Dananjaya',
       'Shivam Mavi', 'JC Archer', 'LE Plunkett', 'IS Sodhi', 'MK Lomror',
       'L Ngidi', 'KM Asif', 'DJ Willey', 'M Prasidh Krishna', 'MM Ali',
       'JPR Scantlebury-Searles', 'S Lamichhane', 'CJ Dala', 'KK Ahmed',
       'Navdeep Saini', 'S Dube', 'Rasikh Salam', 'KMA Paul', 'SM Curran',
       'CV Varun', 'GC Viljoen', 'Mandeep Singh', 'P Ray Barman',
       'MJ Santner', 'JP Behrendorff', 'SC Kuggeleijn', 'AS Joseph',
       'HF Gurney', 'S Midhun', 'R Parag', 'LS Livingstone', 'SN Khan',
       'Abhishek Sharma', 'Arshdeep Singh', 'SE Rutherford',
       'Harpreet Brar', 'Y Prithvi Raj', 'O Thomas', 'AS Roy',
       'S Sandeep Warrier', 'JL Pattinson', 'SS Cottrell', 'Ravi Bishnoi',
       'A Nortje', 'JR Hazlewood', 'KL Nagarkoti', 'I Udana',
       'Abdul Samad', 'Kartik Tyagi', 'TU Deshpande', 'CJ Green',
       'Shahbaz Ahmed', 'DR Sams', 'Monu Kumar', 'DA Warner', 'P Dubey',
       'KA Jamieson', 'M Jansen', 'C Sakariya', 'JA Richardson',
       'RP Meredith', 'LI Meriwala', 'Lalit Yadav', 'Jalaj S Saxena',
       'FA Allen', 'PWH de Silva', 'IC Porel', 'AU Rashid', 'NT Ellis',
       'VR Iyer', 'AK Markram', 'GHS Garton', 'Akash Singh',
       'GD Phillips', 'Umran Malik', 'K Yadav', 'RV Patel', 'OF Smith',
       'Akash Deep', 'PVD Chameera', 'Mohsin Khan', 'R Shepherd',
       'Mukesh Choudhary', 'D Pretorius', 'VG Arora', 'YBK Jaiswal',
       'Tilak Varma', 'DG Nalkande', 'M Theekshana', 'D Brevis',
       'R Powell', 'KR Sen', 'Yash Dayal', 'Shashank Singh',
       'Aman Hakim Khan', 'OC McCoy', 'HR Shokeen', 'A Badoni',
       'DJ Mitchell', 'Harshit Rana', 'SS Iyer', 'K Kartikeya',
       'Simarjeet Singh', 'Fazalhaq Farooqi', 'R Sai Kishore',
       'Ramandeep Singh', 'PH Solanki', 'M Pathirana', 'R Sanjay Yadav',
       'J Little', 'RS Hangargekar', 'Sikandar Raza', 'Mukesh Kumar',
       'KR Mayers', 'NA Saini', 'RJW Topley', 'MG Bracewell',
       'Arshad Khan', 'C Green', 'Yash Thakur', 'Suyash Sharma',
       'SSB Magala', 'Mohit Rathee', 'MW Short', 'Vijaykumar Vyshak',
       'Yudhvir Singh', 'Arjun Tendulkar', 'D Jansen', 'Noor Ahmad',
       'Naveen-ul-Haq', 'Mayank Dagar', 'Gurnoor Brar', 'AJ Hosein',
       'Akash Madhwal', 'R Goyal', 'T Stubbs', 'Vivrant Sharma',
       'JE Root', 'Nithish Kumar Reddy', 'H Sharma', 'Sumit Kumar',
       'N Burger', 'L Wood', 'SZ Mulani', 'Naman Dhir', 'G Coetzee',
       'Azmatullah Omarzai', 'SH Johnson', 'KT Maphaka', 'M Siddharth',
       'MP Yadav', 'R Ravindra', 'KA Maharaj', 'WG Jacks', 'S Joseph',
       'Arshad Khan (2)', 'M Shahrukh Khan', 'N Thushara', 'LB Williams',
       'RJ Gleeson', 'MJ Suthar', 'A Kamboj', 'V Viyaskanth',
       'V Kaverappa', 'Gulbadin Naib', 'N Wadhera', 'Atharva Taide',
       'PVSN Raju', 'V Puthur', 'V Nigam', 'DS Rathi', 'Prince Yadav',
       'Ishan Kishan', 'Zeeshan Ansari', 'PWA Mulder', 'J Overton',
       'Ashwani Kumar', 'PHKD Mendis', 'E Malinga', 'XC Bartlett',
       'C Bosch', 'Karim Janat', 'Suryansh Shedge', 'M Tiwari',
       'Harsh Dubey', "W O'Rourke", 'Musheer Khan'], dtype=object)

In [37]:
train_df['bowler']=train_df['bowler'].apply(lambda x:x.lower())

In [38]:
train_df.groupby('bowler')['valid_ball'].value_counts().reset_index().sort_values(by='count',ascending=False).head(10)

               bowler  valid_ball  count
679          r ashwin           1   4710
872         sp narine           1   4351
132           b kumar           1   4222
712         ra jadeja           1   4056
664         pp chawla           1   3850
1001        ys chahal           1   3791
296   harbhajan singh           1   3416
13           a mishra           1   3371
370         jj bumrah           1   3359
98           ar patel           1   3321

here the bowler defines the name of the bowler[50] total number of bowler and weather the balll is valid or not

In [39]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [40]:
train_df['runs_extras'].unique()

array([1, 0, 5, 4, 2, 3, 7])

DEFINES THE EXTRA RUNS A BOLLWER GETS

In [41]:
train_df.groupby('bowler')['runs_extras'].sum().sort_values(ascending=False).head(10)

bowler
b kumar           320
sl malinga        292
r ashwin          263
mohammed siraj    261
dj bravo          258
ut yadav          257
i sharma          247
hv patel          243
jj bumrah         238
p kumar           236
Name: runs_extras, dtype: int64

runs_extra defines the extra run which are faced by the bowler inclide[legby,wide,freehit....]

In [42]:
train_df.head(13
              )

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,335982,1,KKR,RCB,0,0.5,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
6,335982,1,KKR,RCB,0,0.6,bb mccullum,2,0,1,p kumar,1,1,1,0,False,legbyes,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,6,0,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False
7,335982,1,KKR,RCB,1,1.1,bb mccullum,2,0,1,z khan,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,3,7,0,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False
8,335982,1,KKR,RCB,1,1.2,bb mccullum,2,4,1,z khan,1,0,4,4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,7,8,0,NaN,4,7,0,"('BB McCullum', 'SC Ganguly')",NaN,False
9,335982,1,KKR,RCB,1,1.3,bb mccullum,2,4,1,z khan,1,0,4,4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,11,9,0,NaN,8,8,0,"('BB McCullum', 'SC Ganguly')",NaN,False
10,335982,1,KKR,RCB,1,1.4,bb mccullum,2,6,1,z khan,1,0,6,6,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,17,10,0,NaN,14,9,0,"('BB McCullum', 'SC Ganguly')",NaN,False
11,335982,1,KKR,RCB,1,1.5,bb mccullum,2,4,1,z khan,1,0,4,4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,21,11,0,NaN,18,10,0,"('BB McCullum', 'SC Ganguly')",NaN,False
12,335982,1,KKR,RCB,1,1.6,bb mccullum,2,0,1,z khan,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,21,12,0,NaN,18,11,0,"('BB McCullum', 'SC Ganguly')",NaN,False

the runs total is defines as the sumition of extra runs and runbatter

In [43]:
train_df['runs_total'].value_counts()

runs_total
1    115711
0     95778
4     32502
2     18349
6     14259
3       954
5       557
7        95
Name: count, dtype: int64

In [44]:
train_df[['runs_batter','runs_extras','runs_total']].tail(30)

        runs_batter  runs_extras  runs_total
278175            1            0           1
278176            6            0           6
278177            0            1           1
278178            0            1           1
278179            1            0           1
278180            6            0           6
278181            0            0           0
278182            0            0           0
278183            6            0           6
278184            0            0           0
278185            1            0           1
278186            1            0           1
278187            0            1           1
278188            0            0           0
278189            0            1           1
278190            2            0           2
278191            1            0           1
278192            0            0           0
278193            6            0           6
278194            0            0           0
278195            0            0           0
278196            4            0           4
278197            2            0           2
278198            1            0           1
278199            0            0           0
278200            0            0           0
278201            6            0           6
278202            4            0           4
278203            6            0           6
278204            6            0           6

In [45]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

the runs_total will help us decid the overall runs of that match

In [46]:
train_df.groupby(['match_id', 'batting_team'])['runs_total'].sum()

match_id  batting_team
335982    KKR             222
          RCB              82
335983    CSK             240
          KXP             207
335984    DC              132
          RR              129
335985    MI              165
          RCB             166
335986    DEC             110
          KKR             112
335987    KXP             166
          RR              168
335988    DC              143
          DEC             142
335989    CSK             208
          MI              202
335990    DEC             214
          RR              217
335991    KXP             182
          MI              116
335992    RCB             135
          RR              138
335993    CSK             152
          KKR             147
335994    DEC             155
          MI              154
335995    DC              158
          KXP             162
335996    CSK             178
          RCB             165
335997    KKR             137
          MI              138
335998    DC              191
          RCB             181
335999    DEC             164
          KXP             167
336000    KKR             151
          RR              196
336001    CSK             169
          DC              172
336002    DEC             165
          RCB             171
336003    KKR             169
          KXP             178
336004    DC              133
          MI              162
336005    CSK             109
          RR              110
336006    KXP             127
          RCB             126
336007    CSK             144
          DEC             148
336008    MI              104
          RR              103
336009    CSK             188
          DC              187
336010    KKR             129
          RCB             124
336011    DEC             140
          RR              141
336012    MI              126
          RCB             122
336013    CSK             181
          KXP             163
336014    DEC             181
          KKR             204
336015    DC              156
          RR              159
336016    KXP             144
          RCB             143
336017    DC              110
          KKR             133
336018    CSK             156
          MI              158
336019    KXP             221
          RR              180
336020    DC              194
          DEC             182
336021    KKR              67
          MI               68
336022    DC              118
          KXP              94
336023    RCB             132
          RR              197
336024    DEC             153
          MI              178
336025    CSK              55
          KKR             149
336026    DC              158
          RCB             154
336027    KKR             147
          RR              150
336028    KXP             189
          MI              188
336029    CSK             112
          RCB             126
336031    DEC             175
          KXP             178
336032    DC              179
          MI              176
336033    CSK             201
          RR              211
336034    DEC             153
          RCB             156
336035    KKR             175
          KXP             174
336036    MI              145
          RR              146
336037    CSK             148
          DEC             147
336038    DC               87
          RR              192
336039    CSK             116
          KXP             112
336040    CSK             163
          RR              164
392181    CSK             146
          MI              165
392182    RCB             133
          RR               58
392183    DC               58
          KXP             104
392184    DEC             104
          KKR             101
392185    CSK             179
          RCB              87
392186    KKR              79
          KXP             158
392188    DEC             184
          RCB             160
392189    CSK             180
          DC              189
392190    KKR             165
          RR              168
392191    KXP             173
          RCB             168
392192    DEC             168
          MI              156
392194    DC              150
          RCB             149
392195    KXP             139
          RR              112
392196    CSK             165
          DEC             169
392197    KKR              95
          MI              187
392198    DC              143
          RR              147
392199    KKR             139
          RCB             143
392200    KXP             119
          MI              116
392201    DC              150
          DEC             148
392202    CSK             164
          RR              126
392203    KKR             139
          MI              148
392204    KXP             137
          RCB             145
392205    DEC             141
          RR              142
392206    CSK             163
          DC              145
392207    KKR             153
          KXP             154
392208    MI              149
          RCB             150
392209    CSK             178
          DEC             100
392210    KXP             133
          RR              211
392211    DC              157
          KKR             154
392212    DEC             145
          MI              126
392213    RCB             105
          RR              107
392214    CSK             185
          KXP             174
392215    DC              118
          MI              116
392216    DEC             168
          KXP             169
392217    CSK             141
          RR              140
392218    MI              157
          RCB             141
392219    DC              125
          KKR             123
392220    DEC             166
          RR              113
392221    KKR             173
          RCB             176
392222    KXP             119
          MI              122
392223    DC              173
          DEC             161
392224    CSK             129
          RCB             132
392225    MI              143
          RR              145
392226    DC              120
          KXP             123
392227    CSK             151
          MI              147
392228    DEC             166
          KKR             160
392229    DEC             133
          KXP             134
392230    DC              150
          RR              136
392231    CSK             188
          KKR             189
392232    DC              134
          RCB             135
392233    KKR             102
          RR              101
392234    CSK             116
          KXP              92
392235    DC              166
          MI              165
392236    DEC             158
          RCB             170
392237    DC              153
          DEC             154
392238    CSK             146
          RCB             149
392239    DEC             143
          RCB             137
419106    DEC             150
          KKR             161
419107    MI              212
          RR              208
419108    DC              146
          KXP             142
419109    KKR             136
          RCB             135
419110    CSK             159
          DEC             190
419111    DC              142
          RR              141
419112    KXP             203
          RCB             204
419113    CSK             164
          KKR             109
419114    DC              120
          MI              218
419115    RCB              93
          RR               92
419116    CSK             190
          DC              185
419117    DEC             170
          KXP             164
419118    KKR             134
          RR              168
419119    MI              151
          RCB             155
419120    DC              161
          DEC             171
419121    CSK             145
          KXP             146
419122    KKR             155
          MI              156
419123    CSK             135
          RCB             171
419124    KXP             152
          RR              183
419125    CSK             180
          MI              181
419126    DEC             148
          RR              151
419127    KKR             183
          KXP             144
419128    DC              183
          RCB             166
419129    CSK             160
          RR              177
419130    DEC             131
          MI              172
419131    DC              177
          KKR             137
419132    KXP             163
          MI              164
419133    CSK             162
          RCB             161
419134    DC              188
          RR              121
419135    DEC             157
          KKR             181
419136    KXP             181
          RCB             184
419137    CSK             246
          RR              223
419138    DEC             115
          MI              178
419139    KKR             200
          KXP             204
419140    DC              184
          RCB             147
419141    DEC             157
          RR              159
419142    CSK             165
          MI              141
419143    KXP             153
          RR              157
419144    DC              167
          KKR             181
419145    DEC             186
          RCB             184
419146    KXP             158
          MI              154
419147    CSK             138
          DEC             139
419148    KKR             160
          RCB             162
419149    DC              111
          KXP             112
419150    MI              174
          RR              137
419151    DEC             151
          RCB             138
419152    DC              144
          MI              183
419153    CSK             143
          KKR             139
419154    RCB             132
          RR              130
419155    CSK             112
          DC              113
419156    DEC             178
          KXP             174
419157    MI              191
          RCB             134
419158    KKR             133
          RR              132
419159    CSK             195
          KXP             192
419160    DC              134
          DEC             145
419161    KKR             135
          MI              133
419162    MI              184
          RCB             149
419163    CSK             142
          DEC             104
419164    DEC              82
          RCB              86
419165    CSK             168
          MI              146
501198    CSK             153
          KKR             151
501199    DEC             137
          RR              141
501200    KTK             161
          RCB             162
501201    DC               95
          MI               99
501202    KXP             112
          PW              113
501203    DEC             154
          KKR             163
501204    DC              151
          RR              152
501205    MI              143
          RCB             140
501206    CSK             188
          KXP             193
501207    KTK             148
          PW              151
501208    DEC             175
          RCB             142
501209    KKR             160
          RR              159
501210    KTK             184
          MI              182
501211    CSK             183
          RCB             162
501212    DEC             165
          KXP             166
501213    DC              190
          PW              187
501214    KKR              85
          RR               81
501215    CSK             131
          KTK             135
501216    DC              152
          DEC             168
501218    MI              124
          PW              118
501219    KKR             126
          KTK             132
501220    KXP             195
          RR              147
501221    CSK             156
          MI              164
501222    KKR             171
          RCB             175
501223    DC              231
          KXP             202
501224    DEC             135
          MI              172
501225    KTK             109
          RR              111
501226    CSK             142
          PW              117
501227    DC              160
          RCB             161
501228    CSK             145
          PW              141
501229    DEC             129
          KTK              74
501230    DC              131
          KKR             148
501231    MI               94
          RR               95
501232    PW              155
          RCB             181
501233    DC              157
          KTK             119
501234    KKR             120
          KXP             119
501235    PW              143
          RR              144
501236    CSK             165
          DEC             146
501237    KXP             136
          MI              159
501238    DC              140
          KTK             141
501239    DEC             149
          KKR             169
501240    CSK             149
          RR              147
501241    MI              160
          PW              139
501242    KKR             139
          KTK             156
501243    DC              179
          DEC             175
501244    KXP             120
          RCB             205
501245    CSK             114
          KKR              61
501246    DC              146
          MI              178
501247    KTK             125
          RCB             128
501248    KXP             119
          PW              120
501249    CSK             196
          RR              133
501250    DEC             136
          PW              137
501251    KXP             163
          MI               87
501252    RCB             151
          RR              146
501253    CSK             176
          DC              158
501254    KTK             178
          KXP             181
501255    KKR              89
          RCB             105
501256    DEC             135
          MI              125
501257    DC              141
          KXP             170
501258    KTK              98
          RR               97
501259    DEC             138
          PW              136
501260    KXP             232
          RCB             121
501261    CSK             152
          KTK             141
501262    KKR             119
          PW              118
501263    MI              133
          RR              134
501264    DEC             198
          KXP             116
501265    DC               56
501266    CSK             128
          RCB             129
501267    KKR             175
          MI              178
501268    CSK             177
          RCB             175
501269    KKR             147
          MI              148
501270    MI              142
          RCB             185
501271    CSK             205
          RCB             147
548306    CSK             112
          MI              115
548307    DC              100
          KKR              97
548308    MI              101
          PW              129
548309    KXP             160
          RR              191
548310    DC              137
          RCB             157
548311    CSK             193
          DEC             119
548312    KKR             142
          RR              164
548313    KXP             144
          PW              166
548314    DEC             138
          MI              142
548315    KKR             165
          RCB             123
548316    CSK             110
          DC              111
548317    MI              197
          RR              170
548318    CSK             208
          RCB             205
548319    KXP             116
          PW              115
548320    KKR             137
          RR              131
548321    DC              162
          DEC             157
548322    CSK             155
          PW              156
548323    KKR             132
          KXP             134
548324    RCB             136
          RR              195
548325    DC               93
          MI               92
548326    DEC             196
          RR              197
548327    PW              182
          RCB             186
548328    KKR             127
          KXP             124
548329    DC              193
          DEC             187
548330    CSK             164
          PW              151
548331    KXP             163
          RCB             166
548332    CSK             147
          RR              146
548333    DC              172
          PW              192
548334    KXP             164
          MI              163
548335    DEC             126
          KKR             127
548336    RCB             189
          RR              143
548337    DC              148
          PW              146
548339    KXP             168
          MI              171
548341    DEC             177
          PW              159
548342    DC              207
          MI              170
548343    CSK             149
          KXP             156
548344    KKR             190
          RCB             143
548345    DC              152
          RR              151
548346    DEC             100
          MI              101
548347    CSK             139
          KKR             140
548348    DEC             186
          PW              173
548349    DC              144
          RR              141
548350    KXP             163
          RCB             158
548351    MI              120
          PW              119
548352    CSK             160
          DEC             150
548353    KKR             150
          PW              143
548354    KXP             134
          RR              177
548355    CSK             173
          MI              174
548356    DEC             181
          RCB             185
548357    DC              153
          KKR             154
548358    PW              125
          RR              126
548359    DEC             145
          KXP             170
548360    MI              141
          RCB             142
548361    CSK             127
          RR              126
548362    PW              138
          RCB             173
548363    KKR             155
          MI              182
548364    CSK             115
          DC              114
548365    PW              125
          RR              170
548366    DEC             190
          KXP             194
548367    MI              173
          RCB             171
548368    CSK             160
          KKR             158
548369    DC              140
          KXP             136
548370    KKR             140
          MI              108
548371    CSK             120
          KXP             123
548372    DC              194
          RCB             215
548373    DEC             128
          RR              126
548374    DC              145
          KXP             141
548375    KKR             136
          PW              102
548376    DEC             132
          RCB             123
548377    MI              163
          RR              162
548378    DC              144
          KKR             162
548379    CSK             187
          MI              149
548380    CSK             222
          DC              136
548381    CSK             190
          KKR             192
597998    DC              128
          KKR             129
597999    MI              154
          RCB             156
598000    PW              104
          SRH             126
598001    DC              160
          RR              165
598002    CSK             139
          MI              148
598003    KXP             100
          PW               99
598004    RCB             145
          SRH             150
598005    KKR             125
          RR              144
598006    DC              165
          MI              209
598007    CSK             139
          KXP             138
598008    KKR             154
          RCB             158

In [47]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

runs_bowler

In [48]:
train_df['runs_bowler'].nunique()

8

In [49]:
train_df['runs_bowler'].unique()

array([0, 1, 4, 6, 5, 2, 3, 7])

who are the top 10  bowler with most runs in ipl history

most expensive overs in an ipl match 4 overs

In [50]:
train_df.groupby(['match_id','bowler'])['runs_bowler'].sum().sort_values(ascending=False).head(10)

match_id  bowler
1473439   jc archer           76
1473464   mohammed shami      75
1473507   w o'rourke          74
1426278   mm sharma           73
1136611   basil thampi        70
1359487   yash dayal          69
1426268   rjw topley          68
1426281   l wood              68
1422126   kt maphaka          66
1178423   mujeeb ur rahman    66
Name: runs_bowler, dtype: int64

In [51]:
train_df.head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,335982,1,KKR,RCB,0,0.1,sc ganguly,1,0,1,p kumar,1,1,1,0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,335982,1,KKR,RCB,0,0.2,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,0,p kumar,0,1,1,1,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,335982,1,KKR,RCB,0,0.3,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,335982,1,KKR,RCB,0,0.4,bb mccullum,2,0,1,p kumar,1,0,0,0,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

runs_not boundry

In [52]:
train_df['runs_not_boundary'].unique()

array([False,  True])

In [53]:
train_df['runs_not_boundary'].value_counts()

runs_not_boundary
False    278177
True         28
Name: count, dtype: int64

ther is no error in this perticular section as it define the runs made by running and not by hitting the boundary

In [54]:
train_df[train_df['runs_not_boundary']==True].head()

,match_id,innings,batting_team,bowling_team,over,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
7415,336014,1,KKR,DEC,19,19.6,lr shukla,6,6,1,rp singh,1,0,6,6,True,NaN,DJ Hussey,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,SC Ganguly,Kolkata Knight Riders,23 runs,Kolkata Knight Riders,bat,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,11,5,2008,2007/08,male,club,NaN,NaN,NaN,6,20,32,Unknown,Unknown,204,120,4,NaN,14,3,0,"('DJ Hussey', 'LR Shukla')",NaN,False
23804,392226,2,KXP,DC,1,1.3,sm katich,2,4,1,pj sangwan,1,0,4,4,True,NaN,S Sohal,1,NaN,NaN,NaN,121.0,NaN,NaN,NaN,NaN,False,B Lee,Kings XI Punjab,6 wickets,Kings XI Punjab,field,OUTsurance Oval,Bloemfontein,15,5,2009,2009,male,club,NaN,NaN,NaN,6,20,46,Unknown,Unknown,10,9,0,NaN,9,4,0,"('S Sohal', 'SM Katich')",NaN,False
47910,501225,2,RR,KTK,4,4.4,r dravid,2,4,1,r vinay kumar,1,0,4,4,True,NaN,SR Watson,1,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,False,SK Warne,Rajasthan Royals,8 wickets,Rajasthan Royals,field,Sawai Mansingh Stadium,Jaipur,24,4,2011,2011,male,club,NaN,NaN,NaN,6,20,28,Unknown,Unknown,32,28,0,NaN,18,16,0,"('R Dravid', 'SR Watson')",NaN,False
54289,501252,2,RCB,RR,5,5.1,ch gayle,1,4,1,j botha,1,0,4,4,True,NaN,TM Dilshan,2,NaN,NaN,NaN,147.0,NaN,NaN,NaN,NaN,False,S Aravind,Royal Challengers Bangalore,9 wickets,Royal Challengers Bangalore,field,Sawai Mansingh Stadium,Jaipur,11,5,2011,2011,male,club,NaN,NaN,NaN,6,20,55,Unknown,Unknown,54,31,0,NaN,21,13,0,"('CH Gayle', 'TM Dilshan')",NaN,False
55278,501257,1,KXP,DC,2,2.3,pc valthaty,1,4,1,ik pathan,1,0,4,4,True,NaN,AC Gilchrist,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,PP Chawla,Kings XI Punjab,29 runs,Delhi Daredevils,field,Himachal Pradesh Cricket Association Stadium,Dharamsala,15,5,2011,2011,male,club,NaN,NaN,NaN,6,20,60,Unknown,Unknown,11,15,0,NaN,5,8,0,"('AC Gilchrist', 'PC Valthaty')",NaN,False

In [55]:
train_df.iloc[:,15:].head()

,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,False,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,False,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,False,NaN,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

extra runs

In [56]:
train_df['extra_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty',
       'penalty, wides', 'byes, noballs', 'legbyes, noballs'],
      dtype=object)

In [57]:
train_df['extra_type'].value_counts()

extra_type
wides               9079
legbyes             4203
noballs             1136
byes                 686
byes, noballs         15
legbyes, noballs      12
penalty, wides         1
penalty                1
Name: count, dtype: int64

In [58]:
train_df['extra_type'].fillna('no_extra_runs',inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_20464\267448785.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['extra_type'].fillna('no_extra_runs',inplace=True)

In [59]:
train_df['extra_type'].value_counts()

extra_type
no_extra_runs       263072
wides                 9079
legbyes               4203
noballs               1136
byes                   686
byes, noballs           15
legbyes, noballs        12
penalty, wides           1
penalty                  1
Name: count, dtype: int64

In [60]:
train_df.isnull().sum()

match_id                  0
innings                   0
batting_team              0
bowling_team              0
over                      0
ball_no                   0
batter                    0
bat_pos                   0
runs_batter               0
balls_faced               0
bowler                    0
valid_ball                0
runs_extras               0
runs_total                0
runs_bowler               0
runs_not_boundary         0
extra_type                0
non_striker               0
non_striker_pos           0
wicket_kind          264382
player_out           264382
fielders             268192
runs_target          144302
review_batter        277333
team_reviewed        277333
review_decision      277333
umpire               277333
umpires_call              0
player_of_match           0
match_won_by              0
win_outcome            4702
toss_winner               0
toss_decision             0
venue                     0
city                      0
day                       0
month                     0
year                      0
season                    0
gender                    0
team_type                 0
superover_winner     274309
result_type          273503
method               274315
balls_per_over            0
overs                     0
event_match_no            0
stage                     0
match_number              0
team_runs                 0
team_balls                0
team_wicket               0
new_batter           264884
batter_runs               0
batter_balls              0
bowler_wicket             0
batting_partners          0
next_batter          264884
striker_out               0
dtype: int64

In [61]:
train_df.iloc[:,16:].head()

,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,legbyes,BB McCullum,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,no_extra_runs,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,wides,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,no_extra_runs,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,no_extra_runs,SC Ganguly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [62]:
train_df['non_striker'].nunique()

692

In [63]:
train_df['non_striker']=train_df['non_striker'].apply(lambda x:x.lower())

In [64]:
train_df['non_striker_pos'].nunique()

11

In [65]:
train_df['non_striker_pos'].unique()

array([ 2,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
train_df['wicket_kind'].nunique()

10

In [67]:
train_df['wicket_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [68]:
train_df['wicket_kind'].value_counts()

wicket_kind
caught                   8665
bowled                   2345
run out                  1153
lbw                       853
caught and bowled         388
stumped                   376
hit wicket                 18
retired hurt               17
retired out                 5
obstructing the field       3
Name: count, dtype: int64

In [69]:
train_df['wicket_kind'].fillna("not out",inplace=True)

C:\Users\karan\AppData\Local\Temp\ipykernel_20464\1949907871.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['wicket_kind'].fillna("not out",inplace=True)

In [70]:
train_df['wicket_kind'].value_counts()

wicket_kind
not out                  264382
caught                     8665
bowled                     2345
run out                    1153
lbw                         853
caught and bowled           388
stumped                     376
hit wicket                   18
retired hurt                 17
retired out                   5
obstructing the field         3
Name: count, dtype: int64

In [71]:
train_df.iloc[:,20:].head()

,player_out,fielders,runs_target,review_batter,team_reviewed,review_decision,umpire,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6,20,1,Unknown,Unknown,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [72]:
train_df['player_out'].value_counts()

player_out
RG Sharma                  237
V Kohli                    219
S Dhawan                   193
KD Karthik                 184
RV Uthappa                 180
SK Raina                   171
AM Rahane                  165
DA Warner                  164
AT Rayudu                  155
SV Samson                  153
MS Dhoni                   142
G Gambhir                  136
F du Plessis               136
MK Pandey                  135
AB de Villiers             130
PA Patel                   126
SR Watson                  126
CH Gayle                   126
SA Yadav                   124
KA Pollard                 121
WP Saha                    121
MA Agarwal                 120
GJ Maxwell                 118
RA Jadeja                  117
KL Rahul                   115
Yuvraj Singh               111
SS Iyer                    110
YK Pathan                  110
Q de Kock                  109
RR Pant                    104
JC Buttler                 104
BB McCullum                104
N Rana                     103
Ishan Kishan               103
M Vijay                    101
SP Narine                  101
V Sehwag                    99
HH Pandya                   98
Shubman Gill                98
AD Russell                  95
RA Tripathi                 88
DA Miller                   87
AR Patel                    87
JH Kallis                   85
DJ Hooda                    85
DR Smith                    84
AJ Finch                    84
Mandeep Singh               82
KH Pandya                   81
PP Shaw                     79
R Dravid                    77
AC Gilchrist                76
NV Ojha                     75
SPD Smith                   72
MP Stoinis                  72
D Padikkal                  71
KK Nair                     71
SR Tendulkar                69
N Pooran                    69
DJ Bravo                    69
Abhishek Sharma             67
KC Sangakkara               65
DPMD Jayawardene            64
R Ashwin                    64
YBK Jaiswal                 64
SE Marsh                    63
RD Gaikwad                  62
EJG Morgan                  62
R Parag                     61
S Dube                      61
KS Williamson               60
MK Tiwary                   59
PP Chawla                   56
Harbhajan Singh             55
KM Jadhav                   54
SC Ganguly                  53
MM Ali                      53
IK Pathan                   53
SS Tiwary                   52
MEK Hussey                  51
SO Hetmyer                  51
JP Duminy                   51
P Simran Singh              51
DJ Hussey                   49
M Vohra                     49
VR Iyer                     49
R Tewatia                   48
JM Bairstow                 48
MR Marsh                    47
S Badrinath                 47
V Shankar                   47
AK Markram                  46
STR Binny                   46
Y Venugopal Rao             44
TM Dilshan                  43
Rashid Khan                 42
BJ Hodge                    42
Shakib Al Hasan             41
JA Morkel                   40
SM Curran                   40
Tilak Varma                 40
LS Livingstone              40
LRPL Taylor                 40
JM Sharma                   39
Abdul Samad                 39
CA Lynn                     39
BA Stokes                   38
P Kumar                     38
MS Bisla                    38
AM Nayar                    38
B Kumar                     38
H Klaasen                   37
RM Patidar                  36
CL White                    36
B Sai Sudharsan             36
RK Singh                    36
MC Henriques                36
A Badoni                    36
M Shahrukh Khan             34
Washington Sundar           33
TM Head                     33
A Mishra                    32
HH Gibbs                    32
TL Suman                    32
PD Salt                     31
DT Christian                31
ML Hayden                   31
AD Mathews                  31
PJ Cummins                  30
R Bhatia                    30
Shahbaz Ahmed               29
HV Patel                    29
MK Lomror                   29
JD Ryder                    28
CH Morris                   28
ST Jayasuriya               28
R Vinay Kumar               28
SN Thakur                   28
KP Pietersen                28
LR Shukla                   27
LMP Simmons                 27
N Wadhera                   27
A Symonds                   27
GJ Bailey                   27
JP Faulkner                 26
Abishek Porel               26
SW Billings                 26
KV Sharma                   26
SN Khan                     26
P Negi                      26
GC Smith                    26
TH David                    26
DP Conway                   25
AP Tare                     24
E Lewis                     24
Gurkeerat Singh             24
Dhruv Jurel                 24
M Manhas                    23
DW Steyn                    22
NLTC Perera                 22
PC Valthaty                 22
CJ Anderson                 22
UT Yadav                    21
JO Holder                   21
AL Menaria                  21
RR Rossouw                  20
SK Warne                    20
J Botha                     20
SP Goswami                  20
SA Asnodkar                 20
R Powell                    20
S Sohal                     20
UBT Chand                   20
GH Vihari                   20
CA Pujara                   19
JJ Roy                      19
A Manohar                   19
JC Archer                   19
VVS Laxman                  19
Shashank Singh              19
Azhar Mahmood               19
DB Ravi Teja                19
M Kaif                      18
Priyansh Arya               18
PK Garg                     18
MM Sharma                   18
RS Bopara                   18
K Gowtham                   18
K Rabada                    18
Rahmanullah Gurbaz          17
R Ravindra                  17
C Green                     17
Nithish Kumar Reddy         17
WG Jacks                    17
Mohammad Nabi               17
T Stubbs                    17
R Sathish                   17
SL Malinga                  16
JD Unadkat                  16
Anuj Rawat                  16
SE Rutherford               16
C de Grandhomme             16
RD Chahar                   16
A Raghuvanshi               16
JR Hopes                    16
Lalit Yadav                 16
MD Mishra                   16
D Brevis                    16
RP Singh                    15
K Goel                      15
J Fraser-McGurk             15
A Ashish Reddy              15
DJG Sammy                   15
OA Shah                     15
Kuldeep Yadav               15
PWH de Silva                15
B Chipli                    15
Ashutosh Sharma             14
S Nadeem                    14
S Gopal                     14
Y Nagar                     14
MV Boucher                  14
Z Khan                      14
MS Wade                     14
Naman Dhir                  14
DB Das                      14
R Sharma                    14
RN ten Doeschate            14
Mohammed Shami              14
RD Rickelton                13
HM Amla                     13
CR Brathwaite               13
TG Southee                  13
MG Johnson                  13
DJ Mitchell                 13
KR Mayers                   13
PBB Rajapaksa               13
AA Jhunjhunwala             13
MN Samuels                  13
MJ McClenaghan              13
MJ Lumb                     12
CA Ingram                   12
C Munro                     12
MJ Guptill                  12
Harpreet Brar               12
RJ Harris                   12
PP Ojha                     12
JEC Franklin                11
M Jansen                    11
LA Pomersbach               11
M Morkel                    11
RE van der Merwe            11
Ramandeep Singh             11
R Dhawan                    11
MA Starc                    11
BCJ Cutting                 11
NM Coulter-Nile             11
P Dogra                     11
DH Yagnik                   10
PA Reddy                    10
N Saini                     10
WD Parnell                  10
B Lee                       10
Atharva Taide               10
MS Gony                     10
AD Nath                     10
CJ Jordan                   10
CM Gautam                   10
FY Fazal                    10
Ravi Bishnoi                10
SM Katich                   10
AB Dinda                    10
MF Maharoof                 10
AB Agarkar                  10
SS Prabhudessai             10
Mohammed Siraj              10
DR Sams                      9
N Jagadeesan                 9
JDS Neesham                  9
SP Fleming                   9
Aman Hakim Khan              9
Anmolpreet Singh             9
AS Raut                      9
Aniket Verma                 9
RT Ponting                   9
AJ Tye                       9
Sachin Baby                  9
TA Boult                     9
Shivam Mavi                  9
M Ashwin                     9
AD Mascarenhas               9
DS Kulkarni                  9
JP Inglis                    9
KK Cooper                    9
HC Brook                     9
Shahid Afridi                8
MJ Santner                   8
YV Takawale                  8
PJ Sangwan                   8
PR Shah                      8
Noor Ahmad                   8
SD Hope                      8
JDP Oram                     8
Bipul Sharma                 8
WPUJC Vaas                   8
Azmatullah Omarzai           8
SM Pollock                   8
DL Vettori                   8
DL Chahar                    8
S Anirudha                   8
L Balaji                     8
W Jaffer                     8
R McLaren                    8
S Vidyut                     8
SD Chitnis                   7
V Suryavanshi                7
JJ Bumrah                    7
V Nigam                      7
Sameer Rizvi                 7
YS Chahal                    7
A Nehra                      7
DJM Short                    7
SK Trivedi                   7
Mohammad Hafeez              7
BJ Rohrer                    7
GD Phillips                  7
Salman Butt                  7
M Kartik                     7
SB Bangar                    7
R Shepherd                   7
DJ Jacobs                    7
SB Styris                    7
Harpreet Singh               7
AC Blizzard                  7
Ankit Sharma                 7
MC Juneja                    7
Sikandar Raza                7
A Mhatre                     7
RJ Quiney                    7
KS Bharat                    7
Misbah-ul-Haq                7
MM Patel                     6
SB Dubey                     6
UT Khawaja                   6
Sandeep Sharma               6
AD Hales                     6
SP Jackson                   6
B Akhil                      6
I Sharma                     6
A Chopra                     6
A Nortje                     6
C Sakariya                   6
Vishnu Vinod                 6
Arshdeep Singh               6
M Muralitharan               6
CR Woakes                    6
MW Short                     6
MJ Clarke                    6
G Coetzee                    6
RE Levi                      6
CJ Ferguson                  6
Harshit Rana                 6
WA Mota                      6
KB Arun Karthik              5
RV Gomez                     5
Arshad Khan                  5
AUK Pathan                   5
Kamran Akmal                 5
TR Birt                      5
AS Yadav                     5
VR Aaron                     5
AG Paunikar                  5
R Rampaul                    5
BB Samantray                 5
LJ Wright                    5
RV Patel                     5
A Mithun                     5
PD Collingwood               5
Rasikh Salam                 5
IR Jaggi                     5
M Rawat                      5
D Wiese                      5
KMA Paul                     5
SK Rasheed                   5
AS Rajpoot                   5
S Badree                     5
A Zampa                      5
Swapnil Singh                5
KK Ahmed                     5
AJ Turner                    5
AB McDonald                  5
TK Curran                    5
AA Bilakhia                  5
L Ronchi                     5
M Klinger                    4
DJ Harris                    4
K Kartikeya                  4
AS Roy                       4
AP Majumdar                  4
Sunny Singh                  4
Yudhvir Singh                4
S Rana                       4
S Sreesanth                  4
Imran Tahir                  4
Anirudh Singh                4
KL Nagarkoti                 4
JR Philippe                  4
CV Varun                     4
AC Voges                     4
KA Jamieson                  4
Kartik Tyagi                 4
Joginder Sharma              4
Shoaib Malik                 4
VG Arora                     4
Harmeet Singh                4
PVD Chameera                 4
RR Sarwan                    4
D Pretorius                  4
NT Ellis                     4
LA Carseldine                4
NS Naik                      4
J Yadav                      4
NK Patel                     4
Anureet Singh                4
A Singh                      4
Navdeep Saini                4
RK Bhui                      4
J Suchith                    4
S Aravind                    4
Yashpal Singh                4
AF Milne                     4
S Kaul                       4
TS Mills                     4
R Sai Kishore                4
PHKD Mendis                  4
D Ferreira                   3
Saurav Chauhan               3
Kumar Kushagra               3
T Kohler-Cadmore             3
Suryansh Shedge              3
R Bishnoi                    3
M Markande                   3
SA Abbott                    3
KC Cariappa                  3
MN van Wyk                   3
RR Powar                     3
Mujeeb Ur Rahman             3
M Prasidh Krishna            3
J Arunkumar                  3
I Udana                      3
Sohail Tanvir                3
T Taibu                      3
BR Dunk                      3
CK Kapugedera                3
SW Tait                      3
NJ Maddinson                 3
TL Seifert                   3
Avesh Khan                   3
BMAJ Mendis                  3
Umar Gul                     3
KW Richardson                3
A Kumble                     3
JA Richardson                3
S Narwal                     3
OF Smith                     3
Akash Deep                   3
HR Shokeen                   3
GB Hogg                      3
RJ Peterson                  3
Mohsin Khan                  3
KS Sharma                    3
YV Dhull                     3
Urvil Patel                  3
T Kohli                      3
PN Mankad                    3
M Theekshana                 3
Simarjeet Singh              3
DJ Thornely                  3
S Chanderpaul                3
B Indrajith                  3
Yash Dayal                   3
LH Ferguson                  3
JM Kemp                      2
Iqbal Abdulla                2
AN Ghosh                     2
BAW Mendis                   2
DS Lehmann                   2
SB Wagh                      2
Vijaykumar Vyshak            2
D Salunkhe                   2
AB Barath                    2
CK Langeveldt                2
AP Dole                      2
HE van der Dussen            2
S Sriram                     2
DJ Willey                    2
RA Bawa                      2
Parvez Rasool                2
T Thushara                   2
T Banton                     2
VH Zol                       2
PV Tambe                     2
VY Mahesh                    2
LPC Silva                    2
DR Shorey                    2
GC Viljoen                   2
IS Sodhi                     2
Ankit Soni                   2
Mustafizur Rahman            2
Shoaib Ahmed                 2
MA Wood                      2
TD Paine                     2
AA Chavan                    2
Sumit Kumar                  2
DG Nalkande                  2
A Kamboj                     2
C Bosch                      2
JG Bethell                   2
A Mukund                     2
F Behardien                  2
Pankaj Singh                 2
SB Joshi                     2
R Minz                       2
A Flintoff                   2
T Henderson                  2
AA Kulkarni                  2
ER Dwivedi                   2
AC Thomas                    2
MA Khote                     2
Sanvir Singh                 2
MD Shanaka                   2
J Syed Mohammad              2
VRV Singh                    2
B Laughlin                   2
MDKJ Perera                  2
J Theron                     2
FA Allen                     2
P Awana                      2
TU Deshpande                 2
Mohammad Asif                2
DT Patil                     2
Virat Singh                  2
AT Carey                     2
JJ van der Wath              2
MG Bracewell                 2
Umran Malik                  2
AU Rashid                    2
RR Raje                      1
D du Preez                   1
BE Hendricks                 1
M de Lange                   1
R Shukla                     1
Shivam Sharma                1
Karanveer Singh              1
FH Edwards                   1
S Lamichhane                 1
JL Denly                     1
SD Lad                       1
A Uniyal                     1
GR Napier                    1
VS Yeligati                  1
Mayank Dagar                 1
Gulbadin Naib                1
AA Noffke                    1
PWA Mulder                   1
Mukesh Kumar                 1
BR Sharath                   1
S Kaushik                    1
MS Bhandage                  1
MJ Suthar                    1
Arshad Khan (2)              1
Tanush Kotian                1
KA Maharaj                   1
KJ Abbott                    1
Kamran Khan                  1
DJ Muthuswami                1
H Das                        1
Shoaib Akhtar                1
PSP Handscomb                1
SB Jakati                    1
P Sahu                       1
A Choudhary                  1
A Nel                        1
BB Sran                      1
Basil Thampi                 1
Younis Khan                  1
LE Plunkett                  1
JPR Scantlebury-Searles      1
P Chopra                     1
P Ray Barman                 1
AN Ahmed                     1
SS Cottrell                  1
JL Pattinson                 1
S Tyagi                      1
C Nanda                      1
C Madan                      1
AS Joseph                    1
SE Bond                      1
RS Gavaskar                  1
AG Murtaza                   1
IC Pandey                    1
Jaskaran Singh               1
KP Appanna                   1
VS Malik                     1
KAJ Roach                    1
TM Srivastava                1
SMSM Senanayake              1
Mohammad Ashraful            1
DJ Malan                     1
UA Birla                     1
X Thalaivan Sargunam         1
M Ntini                      1
GD McGrath                   1
SJ Srivastava                1
S Ladda                      1
SS Shaikh                    1
GHS Garton                   1
DR Martyn                    1
DP Nannes                    1
D Kalyankrishna              1
DNT Zoysa                    1
A Tomar                      1
R Sanjay Yadav               1
Arjun Tendulkar              1
Liton Das                    1
R Ninan                      1
ND Doshi                     1
Y Gnaneswara Rao             1
BA Bhatt                     1
DE Bollinger                 1
B Sumanth                    1
OC McCoy                     1
V Pratap Singh               1
RR Bhatkal                   1
CJ McKay                     1
Sunny Gupta                  1
Mukesh Choudhary             1
XC Bartlett                  1
Naveen-ul-Haq                1
Vivrant Sharma               1
P Dubey                      1
JE Root                      1
KM Asif                      1
S Randiv                     1